// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: licence/v1/admin.proto

package licencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminRequest 保留现有管理面强类型 SDK DTO 的 JSON 编码。
// RPC 本身按业务动作显式建模，不允许携带 HTTP method/path。
type AdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRequest) Reset() {
	*x = AdminRequest{}
	mi := &file_licence_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequest) ProtoMessage() {}

func (x *AdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequest.ProtoReflect.Descriptor instead.
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

// AdminResponse 对齐管理面 {code,msg,data} 信封；data_json 是 data 的原始 JSON。
type AdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResponse) Reset() {
	*x = AdminResponse{}
	mi := &file_licence_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResponse) ProtoMessage() {}

func (x *AdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResponse.ProtoReflect.Descriptor instead.
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminResponse) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

// AdminFileChunk 用于发布物上传和带文件验签。首帧携带 json/file_name，后续帧只携带 chunk。
type AdminFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFileChunk) Reset() {
	*x = AdminFileChunk{}
	mi := &file_licence_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFileChunk) ProtoMessage() {}

func (x *AdminFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFileChunk.ProtoReflect.Descriptor instead.
func (*AdminFileChunk) Descriptor() ([]byte, []int) {
	return file_licence_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminFileChunk) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *AdminFileChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AdminFileChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_licence_v1_admin_proto protoreflect.FileDescriptor

const file_licence_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x16licence/v1/admin.proto\x12\x13licenhub.licence.v1\"\"\n" +
	"\fAdminRequest\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"Z\n" +
	"\rAdminResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\fR\bdataJson\"W\n" +
	"\x0eAdminFileChunk\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk2\x8a\x02\n" +
	"\x10AdminAuthService\x12O\n" +
	"\x06SignIn\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12P\n" +
	"\aSignOut\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12S\n" +
	"\n" +
	"CheckToken\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\x8a\x06\n" +
	"\x19QualificationAdminService\x12[\n" +
	"\x12ApplyQualification\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12`\n" +
	"\x17GetCurrentQualification\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12]\n" +
	"\x14FindMyQualifications\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12[\n" +
	"\x12RowsQualifications\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12[\n" +
	"\x12FindQualifications\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Y\n" +
	"\x10GetQualification\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12\\\n" +
	"\x13ReviewQualification\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12\\\n" +
	"\x13RevokeQualification\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\xd4\x05\n" +
	"\x13ProjectAdminService\x12U\n" +
	"\fRowsProjects\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12U\n" +
	"\fFindProjects\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12S\n" +
	"\n" +
	"GetProject\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rCreateProject\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rUpdateProject\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eRemoveProjects\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eDeleteProjects\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12X\n" +
	"\x0fRestoreProjects\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\xdd\x05\n" +
	"\x14InstanceAdminService\x12V\n" +
	"\rRowsInstances\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rFindInstances\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12T\n" +
	"\vGetInstance\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eCreateInstance\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eUpdateInstance\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12X\n" +
	"\x0fRemoveInstances\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12X\n" +
	"\x0fDeleteInstances\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Y\n" +
	"\x10RestoreInstances\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\x8e\x0f\n" +
	"\x13LicenseAdminService\x12U\n" +
	"\fRowsLicenses\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12U\n" +
	"\fFindLicenses\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12S\n" +
	"\n" +
	"GetLicense\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Z\n" +
	"\x11GetLicensePayload\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12\\\n" +
	"\x13GetLicensePublicKey\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12U\n" +
	"\fApplyLicense\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12a\n" +
	"\x18CancelLicenseApplication\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12`\n" +
	"\x17RowsLicenseApplications\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12^\n" +
	"\x15GetLicenseApplication\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12a\n" +
	"\x18ReviewLicenseApplication\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12U\n" +
	"\fRenewLicense\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eSuspendLicense\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rRevokeLicense\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eReissueLicense\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12[\n" +
	"\x12RowsLicenseHistory\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Z\n" +
	"\x11GetLicenseHistory\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12X\n" +
	"\x0fRowsActivations\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rGetActivation\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Y\n" +
	"\x10FindLicenseSeats\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eGetLicenseSeat\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12[\n" +
	"\x12ReleaseLicenseSeat\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\xd1\x01\n" +
	"\x16SigningKeyAdminService\x12\\\n" +
	"\x13GetSigningPublicKey\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Y\n" +
	"\x10RotateSigningKey\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\xc0\x06\n" +
	"\x14ArtifactAdminService\x12V\n" +
	"\rRowsArtifacts\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rFindArtifacts\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12T\n" +
	"\vGetArtifact\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12[\n" +
	"\x0eUploadArtifact\x12#.licenhub.licence.v1.AdminFileChunk\x1a\".licenhub.licence.v1.AdminResponse(\x01\x12W\n" +
	"\x0eUpdateArtifact\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eVerifyArtifact\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12_\n" +
	"\x12VerifyArtifactFile\x12#.licenhub.licence.v1.AdminFileChunk\x1a\".licenhub.licence.v1.AdminResponse(\x01\x12X\n" +
	"\x0fRemoveArtifacts\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12X\n" +
	"\x0fDeleteArtifacts\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\x86\a\n" +
	"\x13VersionAdminService\x12U\n" +
	"\fRowsVersions\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12U\n" +
	"\fFindVersions\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12S\n" +
	"\n" +
	"GetVersion\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rCreateVersion\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rUpdateVersion\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eReleaseVersion\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eArchiveVersion\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eRemoveVersions\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eDeleteVersions\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12X\n" +
	"\x0fRestoreVersions\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\xe7\x06\n" +
	"\x19ProjectModuleAdminService\x12[\n" +
	"\x12RowsProjectModules\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12[\n" +
	"\x12FindProjectModules\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Y\n" +
	"\x10GetProjectModule\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12\\\n" +
	"\x13CreateProjectModule\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12\\\n" +
	"\x13UpdateProjectModule\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12[\n" +
	"\x12SortProjectModules\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12]\n" +
	"\x14RemoveProjectModules\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12]\n" +
	"\x14DeleteProjectModules\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12^\n" +
	"\x15RestoreProjectModules\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\xcf\x03\n" +
	"\x14SaasMenuAdminService\x12V\n" +
	"\rFindSaasMenus\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12T\n" +
	"\vGetSaasMenu\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12U\n" +
	"\fSaveSaasMenu\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12X\n" +
	"\x0fPublishSaasMenu\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12X\n" +
	"\x0fArchiveSaasMenu\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\xe0\x03\n" +
	"\x17SaasFeatureAdminService\x12Y\n" +
	"\x10FindSaasFeatures\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eGetSaasFeature\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12X\n" +
	"\x0fSaveSaasFeature\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12[\n" +
	"\x12DisableSaasFeature\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Z\n" +
	"\x11DeleteSaasFeature\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\xab\x04\n" +
	"\x14SaasPlanAdminService\x12V\n" +
	"\rFindSaasPlans\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12T\n" +
	"\vGetSaasPlan\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eCreateSaasPlan\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eUpdateSaasPlan\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Z\n" +
	"\x11SetSaasPlanStatus\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12W\n" +
	"\x0eDeleteSaasPlan\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\x93\x0e\n" +
	"\x16SaasTenantAdminService\x12X\n" +
	"\x0fFindSaasTenants\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rGetSaasTenant\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12]\n" +
	"\x14GetSaasTenantPayload\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12\\\n" +
	"\x13SubscribeSaasTenant\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12]\n" +
	"\x14ChangeSaasTenantPlan\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12]\n" +
	"\x14UpdateSaasTenantInfo\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Y\n" +
	"\x10CancelSaasTenant\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Y\n" +
	"\x10DeleteSaasTenant\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Z\n" +
	"\x11SuspendSaasTenant\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Y\n" +
	"\x10ResumeSaasTenant\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Y\n" +
	"\x10RevokeSaasTenant\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12Z\n" +
	"\x11ReissueSaasTenant\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12\\\n" +
	"\x13SyncSaasTenantMenus\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12^\n" +
	"\x15BatchRenewSaasTenants\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12c\n" +
	"\x1aFindSaasTenantApplications\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12a\n" +
	"\x18GetSaasTenantApplication\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12\\\n" +
	"\x13FindSaasTenantUsage\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12b\n" +
	"\x19GetSaasTenantUsageSummary\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12`\n" +
	"\x17ExportSaasTenantHistory\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse2\xb0\x02\n" +
	"\x16SaasReviewAdminService\x12X\n" +
	"\x0fFindSaasReviews\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12V\n" +
	"\rGetSaasReview\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponse\x12d\n" +
	"\x1bReviewSaasTenantApplication\x12!.licenhub.licence.v1.AdminRequest\x1a\".licenhub.licence.v1.AdminResponseB<Z:github.com/inis-io/aide/licence/proto/licence/v1;licencev1b\x06proto3"

var (
	file_licence_v1_admin_proto_rawDescOnce sync.Once
	file_licence_v1_admin_proto_rawDescData []byte
)

func file_licence_v1_admin_proto_rawDescGZIP() []byte {
	file_licence_v1_admin_proto_rawDescOnce.Do(func() {
		file_licence_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_licence_v1_admin_proto_rawDesc), len(file_licence_v1_admin_proto_rawDesc)))
	})
	return file_licence_v1_admin_proto_rawDescData
}

var file_licence_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_licence_v1_admin_proto_goTypes = []any{
	(*AdminRequest)(nil),   // 0: licenhub.licence.v1.AdminRequest
	(*AdminResponse)(nil),  // 1: licenhub.licence.v1.AdminResponse
	(*AdminFileChunk)(nil), // 2: licenhub.licence.v1.AdminFileChunk
}
var file_licence_v1_admin_proto_depIdxs = []int32{
	0,   // 0: licenhub.licence.v1.AdminAuthService.SignIn:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 1: licenhub.licence.v1.AdminAuthService.SignOut:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 2: licenhub.licence.v1.AdminAuthService.CheckToken:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 3: licenhub.licence.v1.QualificationAdminService.ApplyQualification:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 4: licenhub.licence.v1.QualificationAdminService.GetCurrentQualification:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 5: licenhub.licence.v1.QualificationAdminService.FindMyQualifications:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 6: licenhub.licence.v1.QualificationAdminService.RowsQualifications:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 7: licenhub.licence.v1.QualificationAdminService.FindQualifications:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 8: licenhub.licence.v1.QualificationAdminService.GetQualification:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 9: licenhub.licence.v1.QualificationAdminService.ReviewQualification:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 10: licenhub.licence.v1.QualificationAdminService.RevokeQualification:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 11: licenhub.licence.v1.ProjectAdminService.RowsProjects:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 12: licenhub.licence.v1.ProjectAdminService.FindProjects:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 13: licenhub.licence.v1.ProjectAdminService.GetProject:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 14: licenhub.licence.v1.ProjectAdminService.CreateProject:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 15: licenhub.licence.v1.ProjectAdminService.UpdateProject:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 16: licenhub.licence.v1.ProjectAdminService.RemoveProjects:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 17: licenhub.licence.v1.ProjectAdminService.DeleteProjects:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 18: licenhub.licence.v1.ProjectAdminService.RestoreProjects:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 19: licenhub.licence.v1.InstanceAdminService.RowsInstances:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 20: licenhub.licence.v1.InstanceAdminService.FindInstances:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 21: licenhub.licence.v1.InstanceAdminService.GetInstance:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 22: licenhub.licence.v1.InstanceAdminService.CreateInstance:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 23: licenhub.licence.v1.InstanceAdminService.UpdateInstance:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 24: licenhub.licence.v1.InstanceAdminService.RemoveInstances:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 25: licenhub.licence.v1.InstanceAdminService.DeleteInstances:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 26: licenhub.licence.v1.InstanceAdminService.RestoreInstances:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 27: licenhub.licence.v1.LicenseAdminService.RowsLicenses:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 28: licenhub.licence.v1.LicenseAdminService.FindLicenses:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 29: licenhub.licence.v1.LicenseAdminService.GetLicense:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 30: licenhub.licence.v1.LicenseAdminService.GetLicensePayload:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 31: licenhub.licence.v1.LicenseAdminService.GetLicensePublicKey:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 32: licenhub.licence.v1.LicenseAdminService.ApplyLicense:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 33: licenhub.licence.v1.LicenseAdminService.CancelLicenseApplication:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 34: licenhub.licence.v1.LicenseAdminService.RowsLicenseApplications:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 35: licenhub.licence.v1.LicenseAdminService.GetLicenseApplication:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 36: licenhub.licence.v1.LicenseAdminService.ReviewLicenseApplication:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 37: licenhub.licence.v1.LicenseAdminService.RenewLicense:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 38: licenhub.licence.v1.LicenseAdminService.SuspendLicense:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 39: licenhub.licence.v1.LicenseAdminService.RevokeLicense:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 40: licenhub.licence.v1.LicenseAdminService.ReissueLicense:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 41: licenhub.licence.v1.LicenseAdminService.RowsLicenseHistory:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 42: licenhub.licence.v1.LicenseAdminService.GetLicenseHistory:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 43: licenhub.licence.v1.LicenseAdminService.RowsActivations:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 44: licenhub.licence.v1.LicenseAdminService.GetActivation:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 45: licenhub.licence.v1.LicenseAdminService.FindLicenseSeats:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 46: licenhub.licence.v1.LicenseAdminService.GetLicenseSeat:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 47: licenhub.licence.v1.LicenseAdminService.ReleaseLicenseSeat:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 48: licenhub.licence.v1.SigningKeyAdminService.GetSigningPublicKey:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 49: licenhub.licence.v1.SigningKeyAdminService.RotateSigningKey:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 50: licenhub.licence.v1.ArtifactAdminService.RowsArtifacts:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 51: licenhub.licence.v1.ArtifactAdminService.FindArtifacts:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 52: licenhub.licence.v1.ArtifactAdminService.GetArtifact:input_type -> licenhub.licence.v1.AdminRequest
	2,   // 53: licenhub.licence.v1.ArtifactAdminService.UploadArtifact:input_type -> licenhub.licence.v1.AdminFileChunk
	0,   // 54: licenhub.licence.v1.ArtifactAdminService.UpdateArtifact:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 55: licenhub.licence.v1.ArtifactAdminService.VerifyArtifact:input_type -> licenhub.licence.v1.AdminRequest
	2,   // 56: licenhub.licence.v1.ArtifactAdminService.VerifyArtifactFile:input_type -> licenhub.licence.v1.AdminFileChunk
	0,   // 57: licenhub.licence.v1.ArtifactAdminService.RemoveArtifacts:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 58: licenhub.licence.v1.ArtifactAdminService.DeleteArtifacts:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 59: licenhub.licence.v1.VersionAdminService.RowsVersions:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 60: licenhub.licence.v1.VersionAdminService.FindVersions:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 61: licenhub.licence.v1.VersionAdminService.GetVersion:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 62: licenhub.licence.v1.VersionAdminService.CreateVersion:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 63: licenhub.licence.v1.VersionAdminService.UpdateVersion:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 64: licenhub.licence.v1.VersionAdminService.ReleaseVersion:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 65: licenhub.licence.v1.VersionAdminService.ArchiveVersion:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 66: licenhub.licence.v1.VersionAdminService.RemoveVersions:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 67: licenhub.licence.v1.VersionAdminService.DeleteVersions:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 68: licenhub.licence.v1.VersionAdminService.RestoreVersions:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 69: licenhub.licence.v1.ProjectModuleAdminService.RowsProjectModules:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 70: licenhub.licence.v1.ProjectModuleAdminService.FindProjectModules:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 71: licenhub.licence.v1.ProjectModuleAdminService.GetProjectModule:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 72: licenhub.licence.v1.ProjectModuleAdminService.CreateProjectModule:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 73: licenhub.licence.v1.ProjectModuleAdminService.UpdateProjectModule:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 74: licenhub.licence.v1.ProjectModuleAdminService.SortProjectModules:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 75: licenhub.licence.v1.ProjectModuleAdminService.RemoveProjectModules:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 76: licenhub.licence.v1.ProjectModuleAdminService.DeleteProjectModules:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 77: licenhub.licence.v1.ProjectModuleAdminService.RestoreProjectModules:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 78: licenhub.licence.v1.SaasMenuAdminService.FindSaasMenus:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 79: licenhub.licence.v1.SaasMenuAdminService.GetSaasMenu:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 80: licenhub.licence.v1.SaasMenuAdminService.SaveSaasMenu:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 81: licenhub.licence.v1.SaasMenuAdminService.PublishSaasMenu:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 82: licenhub.licence.v1.SaasMenuAdminService.ArchiveSaasMenu:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 83: licenhub.licence.v1.SaasFeatureAdminService.FindSaasFeatures:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 84: licenhub.licence.v1.SaasFeatureAdminService.GetSaasFeature:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 85: licenhub.licence.v1.SaasFeatureAdminService.SaveSaasFeature:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 86: licenhub.licence.v1.SaasFeatureAdminService.DisableSaasFeature:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 87: licenhub.licence.v1.SaasFeatureAdminService.DeleteSaasFeature:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 88: licenhub.licence.v1.SaasPlanAdminService.FindSaasPlans:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 89: licenhub.licence.v1.SaasPlanAdminService.GetSaasPlan:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 90: licenhub.licence.v1.SaasPlanAdminService.CreateSaasPlan:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 91: licenhub.licence.v1.SaasPlanAdminService.UpdateSaasPlan:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 92: licenhub.licence.v1.SaasPlanAdminService.SetSaasPlanStatus:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 93: licenhub.licence.v1.SaasPlanAdminService.DeleteSaasPlan:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 94: licenhub.licence.v1.SaasTenantAdminService.FindSaasTenants:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 95: licenhub.licence.v1.SaasTenantAdminService.GetSaasTenant:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 96: licenhub.licence.v1.SaasTenantAdminService.GetSaasTenantPayload:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 97: licenhub.licence.v1.SaasTenantAdminService.SubscribeSaasTenant:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 98: licenhub.licence.v1.SaasTenantAdminService.ChangeSaasTenantPlan:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 99: licenhub.licence.v1.SaasTenantAdminService.UpdateSaasTenantInfo:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 100: licenhub.licence.v1.SaasTenantAdminService.CancelSaasTenant:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 101: licenhub.licence.v1.SaasTenantAdminService.DeleteSaasTenant:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 102: licenhub.licence.v1.SaasTenantAdminService.SuspendSaasTenant:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 103: licenhub.licence.v1.SaasTenantAdminService.ResumeSaasTenant:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 104: licenhub.licence.v1.SaasTenantAdminService.RevokeSaasTenant:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 105: licenhub.licence.v1.SaasTenantAdminService.ReissueSaasTenant:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 106: licenhub.licence.v1.SaasTenantAdminService.SyncSaasTenantMenus:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 107: licenhub.licence.v1.SaasTenantAdminService.BatchRenewSaasTenants:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 108: licenhub.licence.v1.SaasTenantAdminService.FindSaasTenantApplications:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 109: licenhub.licence.v1.SaasTenantAdminService.GetSaasTenantApplication:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 110: licenhub.licence.v1.SaasTenantAdminService.FindSaasTenantUsage:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 111: licenhub.licence.v1.SaasTenantAdminService.GetSaasTenantUsageSummary:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 112: licenhub.licence.v1.SaasTenantAdminService.ExportSaasTenantHistory:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 113: licenhub.licence.v1.SaasReviewAdminService.FindSaasReviews:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 114: licenhub.licence.v1.SaasReviewAdminService.GetSaasReview:input_type -> licenhub.licence.v1.AdminRequest
	0,   // 115: licenhub.licence.v1.SaasReviewAdminService.ReviewSaasTenantApplication:input_type -> licenhub.licence.v1.AdminRequest
	1,   // 116: licenhub.licence.v1.AdminAuthService.SignIn:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 117: licenhub.licence.v1.AdminAuthService.SignOut:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 118: licenhub.licence.v1.AdminAuthService.CheckToken:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 119: licenhub.licence.v1.QualificationAdminService.ApplyQualification:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 120: licenhub.licence.v1.QualificationAdminService.GetCurrentQualification:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 121: licenhub.licence.v1.QualificationAdminService.FindMyQualifications:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 122: licenhub.licence.v1.QualificationAdminService.RowsQualifications:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 123: licenhub.licence.v1.QualificationAdminService.FindQualifications:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 124: licenhub.licence.v1.QualificationAdminService.GetQualification:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 125: licenhub.licence.v1.QualificationAdminService.ReviewQualification:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 126: licenhub.licence.v1.QualificationAdminService.RevokeQualification:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 127: licenhub.licence.v1.ProjectAdminService.RowsProjects:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 128: licenhub.licence.v1.ProjectAdminService.FindProjects:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 129: licenhub.licence.v1.ProjectAdminService.GetProject:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 130: licenhub.licence.v1.ProjectAdminService.CreateProject:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 131: licenhub.licence.v1.ProjectAdminService.UpdateProject:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 132: licenhub.licence.v1.ProjectAdminService.RemoveProjects:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 133: licenhub.licence.v1.ProjectAdminService.DeleteProjects:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 134: licenhub.licence.v1.ProjectAdminService.RestoreProjects:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 135: licenhub.licence.v1.InstanceAdminService.RowsInstances:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 136: licenhub.licence.v1.InstanceAdminService.FindInstances:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 137: licenhub.licence.v1.InstanceAdminService.GetInstance:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 138: licenhub.licence.v1.InstanceAdminService.CreateInstance:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 139: licenhub.licence.v1.InstanceAdminService.UpdateInstance:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 140: licenhub.licence.v1.InstanceAdminService.RemoveInstances:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 141: licenhub.licence.v1.InstanceAdminService.DeleteInstances:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 142: licenhub.licence.v1.InstanceAdminService.RestoreInstances:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 143: licenhub.licence.v1.LicenseAdminService.RowsLicenses:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 144: licenhub.licence.v1.LicenseAdminService.FindLicenses:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 145: licenhub.licence.v1.LicenseAdminService.GetLicense:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 146: licenhub.licence.v1.LicenseAdminService.GetLicensePayload:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 147: licenhub.licence.v1.LicenseAdminService.GetLicensePublicKey:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 148: licenhub.licence.v1.LicenseAdminService.ApplyLicense:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 149: licenhub.licence.v1.LicenseAdminService.CancelLicenseApplication:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 150: licenhub.licence.v1.LicenseAdminService.RowsLicenseApplications:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 151: licenhub.licence.v1.LicenseAdminService.GetLicenseApplication:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 152: licenhub.licence.v1.LicenseAdminService.ReviewLicenseApplication:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 153: licenhub.licence.v1.LicenseAdminService.RenewLicense:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 154: licenhub.licence.v1.LicenseAdminService.SuspendLicense:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 155: licenhub.licence.v1.LicenseAdminService.RevokeLicense:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 156: licenhub.licence.v1.LicenseAdminService.ReissueLicense:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 157: licenhub.licence.v1.LicenseAdminService.RowsLicenseHistory:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 158: licenhub.licence.v1.LicenseAdminService.GetLicenseHistory:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 159: licenhub.licence.v1.LicenseAdminService.RowsActivations:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 160: licenhub.licence.v1.LicenseAdminService.GetActivation:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 161: licenhub.licence.v1.LicenseAdminService.FindLicenseSeats:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 162: licenhub.licence.v1.LicenseAdminService.GetLicenseSeat:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 163: licenhub.licence.v1.LicenseAdminService.ReleaseLicenseSeat:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 164: licenhub.licence.v1.SigningKeyAdminService.GetSigningPublicKey:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 165: licenhub.licence.v1.SigningKeyAdminService.RotateSigningKey:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 166: licenhub.licence.v1.ArtifactAdminService.RowsArtifacts:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 167: licenhub.licence.v1.ArtifactAdminService.FindArtifacts:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 168: licenhub.licence.v1.ArtifactAdminService.GetArtifact:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 169: licenhub.licence.v1.ArtifactAdminService.UploadArtifact:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 170: licenhub.licence.v1.ArtifactAdminService.UpdateArtifact:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 171: licenhub.licence.v1.ArtifactAdminService.VerifyArtifact:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 172: licenhub.licence.v1.ArtifactAdminService.VerifyArtifactFile:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 173: licenhub.licence.v1.ArtifactAdminService.RemoveArtifacts:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 174: licenhub.licence.v1.ArtifactAdminService.DeleteArtifacts:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 175: licenhub.licence.v1.VersionAdminService.RowsVersions:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 176: licenhub.licence.v1.VersionAdminService.FindVersions:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 177: licenhub.licence.v1.VersionAdminService.GetVersion:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 178: licenhub.licence.v1.VersionAdminService.CreateVersion:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 179: licenhub.licence.v1.VersionAdminService.UpdateVersion:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 180: licenhub.licence.v1.VersionAdminService.ReleaseVersion:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 181: licenhub.licence.v1.VersionAdminService.ArchiveVersion:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 182: licenhub.licence.v1.VersionAdminService.RemoveVersions:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 183: licenhub.licence.v1.VersionAdminService.DeleteVersions:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 184: licenhub.licence.v1.VersionAdminService.RestoreVersions:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 185: licenhub.licence.v1.ProjectModuleAdminService.RowsProjectModules:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 186: licenhub.licence.v1.ProjectModuleAdminService.FindProjectModules:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 187: licenhub.licence.v1.ProjectModuleAdminService.GetProjectModule:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 188: licenhub.licence.v1.ProjectModuleAdminService.CreateProjectModule:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 189: licenhub.licence.v1.ProjectModuleAdminService.UpdateProjectModule:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 190: licenhub.licence.v1.ProjectModuleAdminService.SortProjectModules:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 191: licenhub.licence.v1.ProjectModuleAdminService.RemoveProjectModules:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 192: licenhub.licence.v1.ProjectModuleAdminService.DeleteProjectModules:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 193: licenhub.licence.v1.ProjectModuleAdminService.RestoreProjectModules:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 194: licenhub.licence.v1.SaasMenuAdminService.FindSaasMenus:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 195: licenhub.licence.v1.SaasMenuAdminService.GetSaasMenu:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 196: licenhub.licence.v1.SaasMenuAdminService.SaveSaasMenu:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 197: licenhub.licence.v1.SaasMenuAdminService.PublishSaasMenu:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 198: licenhub.licence.v1.SaasMenuAdminService.ArchiveSaasMenu:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 199: licenhub.licence.v1.SaasFeatureAdminService.FindSaasFeatures:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 200: licenhub.licence.v1.SaasFeatureAdminService.GetSaasFeature:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 201: licenhub.licence.v1.SaasFeatureAdminService.SaveSaasFeature:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 202: licenhub.licence.v1.SaasFeatureAdminService.DisableSaasFeature:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 203: licenhub.licence.v1.SaasFeatureAdminService.DeleteSaasFeature:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 204: licenhub.licence.v1.SaasPlanAdminService.FindSaasPlans:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 205: licenhub.licence.v1.SaasPlanAdminService.GetSaasPlan:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 206: licenhub.licence.v1.SaasPlanAdminService.CreateSaasPlan:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 207: licenhub.licence.v1.SaasPlanAdminService.UpdateSaasPlan:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 208: licenhub.licence.v1.SaasPlanAdminService.SetSaasPlanStatus:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 209: licenhub.licence.v1.SaasPlanAdminService.DeleteSaasPlan:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 210: licenhub.licence.v1.SaasTenantAdminService.FindSaasTenants:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 211: licenhub.licence.v1.SaasTenantAdminService.GetSaasTenant:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 212: licenhub.licence.v1.SaasTenantAdminService.GetSaasTenantPayload:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 213: licenhub.licence.v1.SaasTenantAdminService.SubscribeSaasTenant:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 214: licenhub.licence.v1.SaasTenantAdminService.ChangeSaasTenantPlan:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 215: licenhub.licence.v1.SaasTenantAdminService.UpdateSaasTenantInfo:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 216: licenhub.licence.v1.SaasTenantAdminService.CancelSaasTenant:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 217: licenhub.licence.v1.SaasTenantAdminService.DeleteSaasTenant:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 218: licenhub.licence.v1.SaasTenantAdminService.SuspendSaasTenant:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 219: licenhub.licence.v1.SaasTenantAdminService.ResumeSaasTenant:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 220: licenhub.licence.v1.SaasTenantAdminService.RevokeSaasTenant:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 221: licenhub.licence.v1.SaasTenantAdminService.ReissueSaasTenant:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 222: licenhub.licence.v1.SaasTenantAdminService.SyncSaasTenantMenus:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 223: licenhub.licence.v1.SaasTenantAdminService.BatchRenewSaasTenants:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 224: licenhub.licence.v1.SaasTenantAdminService.FindSaasTenantApplications:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 225: licenhub.licence.v1.SaasTenantAdminService.GetSaasTenantApplication:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 226: licenhub.licence.v1.SaasTenantAdminService.FindSaasTenantUsage:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 227: licenhub.licence.v1.SaasTenantAdminService.GetSaasTenantUsageSummary:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 228: licenhub.licence.v1.SaasTenantAdminService.ExportSaasTenantHistory:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 229: licenhub.licence.v1.SaasReviewAdminService.FindSaasReviews:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 230: licenhub.licence.v1.SaasReviewAdminService.GetSaasReview:output_type -> licenhub.licence.v1.AdminResponse
	1,   // 231: licenhub.licence.v1.SaasReviewAdminService.ReviewSaasTenantApplication:output_type -> licenhub.licence.v1.AdminResponse
	116, // [116:232] is the sub-list for method output_type
	0,   // [0:116] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_licence_v1_admin_proto_init() }
func file_licence_v1_admin_proto_init() {
	if File_licence_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_licence_v1_admin_proto_rawDesc), len(file_licence_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   14,
		},
		GoTypes:           file_licence_v1_admin_proto_goTypes,
		DependencyIndexes: file_licence_v1_admin_proto_depIdxs,
		MessageInfos:      file_licence_v1_admin_proto_msgTypes,
	}.Build()
	File_licence_v1_admin_proto = out.File
	file_licence_v1_admin_proto_goTypes = nil
	file_licence_v1_admin_proto_depIdxs = nil
}
