// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: licence/v1/runtime.proto

package licencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo       string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	InstanceNo      string                 `protobuf:"bytes,2,opt,name=instance_no,json=instanceNo,proto3" json:"instance_no,omitempty"`
	FingerprintHash string                 `protobuf:"bytes,3,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	ClientPublicKey string                 `protobuf:"bytes,4,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	ClientTime      int64                  `protobuf:"varint,5,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	DeviceName      string                 `protobuf:"bytes,6,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *ActivateRequest) GetInstanceNo() string {
	if x != nil {
		return x.InstanceNo
	}
	return ""
}

func (x *ActivateRequest) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *ActivateRequest) GetClientPublicKey() string {
	if x != nil {
		return x.ClientPublicKey
	}
	return ""
}

func (x *ActivateRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *ActivateRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type ValidateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo       string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	FingerprintHash string                 `protobuf:"bytes,2,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Feature         string                 `protobuf:"bytes,4,opt,name=feature,proto3" json:"feature,omitempty"`
	Usage           map[string]int64       `protobuf:"bytes,5,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ClientTime      int64                  `protobuf:"varint,6,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *ValidateRequest) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *ValidateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ValidateRequest) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *ValidateRequest) GetUsage() map[string]int64 {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ValidateRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type CurrentLicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentLicenseRequest) Reset() {
	*x = CurrentLicenseRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentLicenseRequest) ProtoMessage() {}

func (x *CurrentLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentLicenseRequest.ProtoReflect.Descriptor instead.
func (*CurrentLicenseRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *CurrentLicenseRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

// ProvisionRequest - 装机免费自动申领请求。
// template_code 与 provision_token 由官方二进制内写死；install_sn 为安装唯一标识。
type ProvisionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TemplateCode    string                 `protobuf:"bytes,1,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	ProvisionToken  string                 `protobuf:"bytes,2,opt,name=provision_token,json=provisionToken,proto3" json:"provision_token,omitempty"`
	InstallSn       string                 `protobuf:"bytes,3,opt,name=install_sn,json=installSn,proto3" json:"install_sn,omitempty"`
	FingerprintHash string                 `protobuf:"bytes,4,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	DeviceName      string                 `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	ClientTime      int64                  `protobuf:"varint,6,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *ProvisionRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *ProvisionRequest) GetProvisionToken() string {
	if x != nil {
		return x.ProvisionToken
	}
	return ""
}

func (x *ProvisionRequest) GetInstallSn() string {
	if x != nil {
		return x.InstallSn
	}
	return ""
}

func (x *ProvisionRequest) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *ProvisionRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ProvisionRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// RedeemRequest - 商业激活码兑换请求。
type RedeemRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	InstallSn       string                 `protobuf:"bytes,2,opt,name=install_sn,json=installSn,proto3" json:"install_sn,omitempty"`
	FingerprintHash string                 `protobuf:"bytes,3,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	DeviceName      string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	ClientTime      int64                  `protobuf:"varint,5,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RedeemRequest) Reset() {
	*x = RedeemRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemRequest) ProtoMessage() {}

func (x *RedeemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemRequest.ProtoReflect.Descriptor instead.
func (*RedeemRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *RedeemRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RedeemRequest) GetInstallSn() string {
	if x != nil {
		return x.InstallSn
	}
	return ""
}

func (x *RedeemRequest) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *RedeemRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *RedeemRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// ProvisionResponse - 装机自动申领/激活码兑换统一响应。
type ProvisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	LicenseNo     string                 `protobuf:"bytes,3,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	Salt          string                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	BindingPolicy string                 `protobuf:"bytes,5,opt,name=binding_policy,json=bindingPolicy,proto3" json:"binding_policy,omitempty"`
	SeatLimit     int32                  `protobuf:"varint,6,opt,name=seat_limit,json=seatLimit,proto3" json:"seat_limit,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Reissued      bool                   `protobuf:"varint,8,opt,name=reissued,proto3" json:"reissued,omitempty"`
	Message       string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *ProvisionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProvisionResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ProvisionResponse) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *ProvisionResponse) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *ProvisionResponse) GetBindingPolicy() string {
	if x != nil {
		return x.BindingPolicy
	}
	return ""
}

func (x *ProvisionResponse) GetSeatLimit() int32 {
	if x != nil {
		return x.SeatLimit
	}
	return 0
}

func (x *ProvisionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ProvisionResponse) GetReissued() bool {
	if x != nil {
		return x.Reissued
	}
	return false
}

func (x *ProvisionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RuntimeResponse - 许可证运行面统一响应。
// envelope_json 必须是平台签发的 JSON 原文，客户端基于其中 payload 原文验签。
type RuntimeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime      int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	EnvelopeJson    []byte                 `protobuf:"bytes,3,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	ActivationNo    string                 `protobuf:"bytes,4,opt,name=activation_no,json=activationNo,proto3" json:"activation_no,omitempty"`
	ActivationToken string                 `protobuf:"bytes,5,opt,name=activation_token,json=activationToken,proto3" json:"activation_token,omitempty"`
	ExpiresAt       int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Message         string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	SeatNo          string                 `protobuf:"bytes,8,opt,name=seat_no,json=seatNo,proto3" json:"seat_no,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeResponse) Reset() {
	*x = RuntimeResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeResponse) ProtoMessage() {}

func (x *RuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeResponse.ProtoReflect.Descriptor instead.
func (*RuntimeResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *RuntimeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuntimeResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *RuntimeResponse) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

func (x *RuntimeResponse) GetActivationNo() string {
	if x != nil {
		return x.ActivationNo
	}
	return ""
}

func (x *RuntimeResponse) GetActivationToken() string {
	if x != nil {
		return x.ActivationToken
	}
	return ""
}

func (x *RuntimeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RuntimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeResponse) GetSeatNo() string {
	if x != nil {
		return x.SeatNo
	}
	return ""
}

type UpdateCheckRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo       string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	FingerprintHash string                 `protobuf:"bytes,2,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	OsArch          string                 `protobuf:"bytes,3,opt,name=os_arch,json=osArch,proto3" json:"os_arch,omitempty"`
	Version         string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	ClientTime      int64                  `protobuf:"varint,5,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCheckRequest) Reset() {
	*x = UpdateCheckRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckRequest) ProtoMessage() {}

func (x *UpdateCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckRequest.ProtoReflect.Descriptor instead.
func (*UpdateCheckRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCheckRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *UpdateCheckRequest) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *UpdateCheckRequest) GetOsArch() string {
	if x != nil {
		return x.OsArch
	}
	return ""
}

func (x *UpdateCheckRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateCheckRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type UpdateCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Update        bool                   `protobuf:"varint,3,opt,name=update,proto3" json:"update,omitempty"`
	ManifestJson  []byte                 `protobuf:"bytes,4,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCheckResponse) Reset() {
	*x = UpdateCheckResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckResponse) ProtoMessage() {}

func (x *UpdateCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckResponse.ProtoReflect.Descriptor instead.
func (*UpdateCheckResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateCheckResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *UpdateCheckResponse) GetUpdate() bool {
	if x != nil {
		return x.Update
	}
	return false
}

func (x *UpdateCheckResponse) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

func (x *UpdateCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	RecordNo      string                 `protobuf:"bytes,2,opt,name=record_no,json=recordNo,proto3" json:"record_no,omitempty"`
	FromVersion   string                 `protobuf:"bytes,3,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	TargetVersion string                 `protobuf:"bytes,4,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	ArtifactNo    string                 `protobuf:"bytes,5,opt,name=artifact_no,json=artifactNo,proto3" json:"artifact_no,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	ClientTime    int64                  `protobuf:"varint,8,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReportRequest) Reset() {
	*x = UpdateReportRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReportRequest) ProtoMessage() {}

func (x *UpdateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReportRequest.ProtoReflect.Descriptor instead.
func (*UpdateReportRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateReportRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *UpdateReportRequest) GetRecordNo() string {
	if x != nil {
		return x.RecordNo
	}
	return ""
}

func (x *UpdateReportRequest) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *UpdateReportRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *UpdateReportRequest) GetArtifactNo() string {
	if x != nil {
		return x.ArtifactNo
	}
	return ""
}

func (x *UpdateReportRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateReportRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateReportRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type UpdateLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	RecordNo      string                 `protobuf:"bytes,2,opt,name=record_no,json=recordNo,proto3" json:"record_no,omitempty"`
	Lines         []string               `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLogsRequest) Reset() {
	*x = UpdateLogsRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLogsRequest) ProtoMessage() {}

func (x *UpdateLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLogsRequest.ProtoReflect.Descriptor instead.
func (*UpdateLogsRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateLogsRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *UpdateLogsRequest) GetRecordNo() string {
	if x != nil {
		return x.RecordNo
	}
	return ""
}

func (x *UpdateLogsRequest) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type UpdateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	RecordNo      string                 `protobuf:"bytes,3,opt,name=record_no,json=recordNo,proto3" json:"record_no,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReportResponse) Reset() {
	*x = UpdateReportResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReportResponse) ProtoMessage() {}

func (x *UpdateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReportResponse.ProtoReflect.Descriptor instead.
func (*UpdateReportResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateReportResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *UpdateReportResponse) GetRecordNo() string {
	if x != nil {
		return x.RecordNo
	}
	return ""
}

func (x *UpdateReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TenantSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	SinceTime     int64                  `protobuf:"varint,2,opt,name=since_time,json=sinceTime,proto3" json:"since_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSyncRequest) Reset() {
	*x = TenantSyncRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSyncRequest) ProtoMessage() {}

func (x *TenantSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSyncRequest.ProtoReflect.Descriptor instead.
func (*TenantSyncRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *TenantSyncRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *TenantSyncRequest) GetSinceTime() int64 {
	if x != nil {
		return x.SinceTime
	}
	return 0
}

type TenantManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MenusJson     []byte                 `protobuf:"bytes,2,opt,name=menus_json,json=menusJson,proto3" json:"menus_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantManifest) Reset() {
	*x = TenantManifest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantManifest) ProtoMessage() {}

func (x *TenantManifest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantManifest.ProtoReflect.Descriptor instead.
func (*TenantManifest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *TenantManifest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TenantManifest) GetMenusJson() []byte {
	if x != nil {
		return x.MenusJson
	}
	return nil
}

type TenantSyncItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EnvelopeJson  []byte                 `protobuf:"bytes,3,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSyncItem) Reset() {
	*x = TenantSyncItem{}
	mi := &file_licence_v1_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSyncItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSyncItem) ProtoMessage() {}

func (x *TenantSyncItem) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSyncItem.ProtoReflect.Descriptor instead.
func (*TenantSyncItem) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *TenantSyncItem) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *TenantSyncItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantSyncItem) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

type TenantSyncResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime       int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	SyncTime         int64                  `protobuf:"varint,3,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	Tenants          []*TenantSyncItem      `protobuf:"bytes,5,rep,name=tenants,proto3" json:"tenants,omitempty"`
	Message          string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	PlatformManifest *TenantManifest        `protobuf:"bytes,7,opt,name=platform_manifest,json=platformManifest,proto3" json:"platform_manifest,omitempty"`
	TenantManifest   *TenantManifest        `protobuf:"bytes,8,opt,name=tenant_manifest,json=tenantManifest,proto3" json:"tenant_manifest,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TenantSyncResponse) Reset() {
	*x = TenantSyncResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSyncResponse) ProtoMessage() {}

func (x *TenantSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSyncResponse.ProtoReflect.Descriptor instead.
func (*TenantSyncResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *TenantSyncResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *TenantSyncResponse) GetSyncTime() int64 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

func (x *TenantSyncResponse) GetTenants() []*TenantSyncItem {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *TenantSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TenantSyncResponse) GetPlatformManifest() *TenantManifest {
	if x != nil {
		return x.PlatformManifest
	}
	return nil
}

func (x *TenantSyncResponse) GetTenantManifest() *TenantManifest {
	if x != nil {
		return x.TenantManifest
	}
	return nil
}

type TenantSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSearchRequest) Reset() {
	*x = TenantSearchRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSearchRequest) ProtoMessage() {}

func (x *TenantSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSearchRequest.ProtoReflect.Descriptor instead.
func (*TenantSearchRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *TenantSearchRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *TenantSearchRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type TenantSearchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	TenantName    string                 `protobuf:"bytes,2,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSearchItem) Reset() {
	*x = TenantSearchItem{}
	mi := &file_licence_v1_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSearchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSearchItem) ProtoMessage() {}

func (x *TenantSearchItem) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSearchItem.ProtoReflect.Descriptor instead.
func (*TenantSearchItem) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *TenantSearchItem) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *TenantSearchItem) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

type TenantSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Tenants       []*TenantSearchItem    `protobuf:"bytes,3,rep,name=tenants,proto3" json:"tenants,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSearchResponse) Reset() {
	*x = TenantSearchResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSearchResponse) ProtoMessage() {}

func (x *TenantSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSearchResponse.ProtoReflect.Descriptor instead.
func (*TenantSearchResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *TenantSearchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantSearchResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *TenantSearchResponse) GetTenants() []*TenantSearchItem {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *TenantSearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TenantValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	TenantCode    string                 `protobuf:"bytes,2,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Feature       string                 `protobuf:"bytes,4,opt,name=feature,proto3" json:"feature,omitempty"`
	Usage         map[string]int64       `protobuf:"bytes,5,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantValidateRequest) Reset() {
	*x = TenantValidateRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantValidateRequest) ProtoMessage() {}

func (x *TenantValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantValidateRequest.ProtoReflect.Descriptor instead.
func (*TenantValidateRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *TenantValidateRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *TenantValidateRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *TenantValidateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TenantValidateRequest) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *TenantValidateRequest) GetUsage() map[string]int64 {
	if x != nil {
		return x.Usage
	}
	return nil
}

type TenantCurrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	TenantCode    string                 `protobuf:"bytes,2,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantCurrentRequest) Reset() {
	*x = TenantCurrentRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantCurrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantCurrentRequest) ProtoMessage() {}

func (x *TenantCurrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantCurrentRequest.ProtoReflect.Descriptor instead.
func (*TenantCurrentRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *TenantCurrentRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *TenantCurrentRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	EnvelopeJson  []byte                 `protobuf:"bytes,3,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *TenantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *TenantResponse) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

func (x *TenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ProjectConfigSyncRequest/Response 已随项目配置运行面下线，字段号以 reserved 锁定禁止复用。
type ProjectConfigSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectConfigSyncRequest) Reset() {
	*x = ProjectConfigSyncRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectConfigSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectConfigSyncRequest) ProtoMessage() {}

func (x *ProjectConfigSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectConfigSyncRequest.ProtoReflect.Descriptor instead.
func (*ProjectConfigSyncRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{22}
}

type ProjectConfigSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectConfigSyncResponse) Reset() {
	*x = ProjectConfigSyncResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectConfigSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectConfigSyncResponse) ProtoMessage() {}

func (x *ProjectConfigSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectConfigSyncResponse.ProtoReflect.Descriptor instead.
func (*ProjectConfigSyncResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{23}
}

type PlatformConfigSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	ProjectId     int32                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SinceVersion  int32                  `protobuf:"varint,3,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformConfigSyncRequest) Reset() {
	*x = PlatformConfigSyncRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformConfigSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformConfigSyncRequest) ProtoMessage() {}

func (x *PlatformConfigSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformConfigSyncRequest.ProtoReflect.Descriptor instead.
func (*PlatformConfigSyncRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{24}
}

func (x *PlatformConfigSyncRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *PlatformConfigSyncRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PlatformConfigSyncRequest) GetSinceVersion() int32 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

type PlatformConfigSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	EnvelopeJson  []byte                 `protobuf:"bytes,3,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformConfigSyncResponse) Reset() {
	*x = PlatformConfigSyncResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformConfigSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformConfigSyncResponse) ProtoMessage() {}

func (x *PlatformConfigSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformConfigSyncResponse.ProtoReflect.Descriptor instead.
func (*PlatformConfigSyncResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{25}
}

func (x *PlatformConfigSyncResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlatformConfigSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *PlatformConfigSyncResponse) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

func (x *PlatformConfigSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ConfigConsumptionItem - 单配置键消费计数。
type ConfigConsumptionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigConsumptionItem) Reset() {
	*x = ConfigConsumptionItem{}
	mi := &file_licence_v1_runtime_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigConsumptionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigConsumptionItem) ProtoMessage() {}

func (x *ConfigConsumptionItem) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigConsumptionItem.ProtoReflect.Descriptor instead.
func (*ConfigConsumptionItem) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{26}
}

func (x *ConfigConsumptionItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigConsumptionItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ConfigConsumptionReportRequest - 配置消费上报请求。
type ConfigConsumptionReportRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	LicenseNo     string                   `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	Items         []*ConfigConsumptionItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigConsumptionReportRequest) Reset() {
	*x = ConfigConsumptionReportRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigConsumptionReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigConsumptionReportRequest) ProtoMessage() {}

func (x *ConfigConsumptionReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigConsumptionReportRequest.ProtoReflect.Descriptor instead.
func (*ConfigConsumptionReportRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{27}
}

func (x *ConfigConsumptionReportRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *ConfigConsumptionReportRequest) GetItems() []*ConfigConsumptionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// ConfigConsumptionReportResponse - 配置消费上报响应。
type ConfigConsumptionReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigConsumptionReportResponse) Reset() {
	*x = ConfigConsumptionReportResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigConsumptionReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigConsumptionReportResponse) ProtoMessage() {}

func (x *ConfigConsumptionReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigConsumptionReportResponse.ProtoReflect.Descriptor instead.
func (*ConfigConsumptionReportResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{28}
}

func (x *ConfigConsumptionReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfigConsumptionReportResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ConfigConsumptionReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// EventSubscribeRequest - 事件订阅请求。
// since_event_id 为已消费水位（callback_events.id，0 = 从头）；
// timeout_ms 为长轮询 hold 时长（0 = 服务端默认 10000，硬上限 30000）。
type EventSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	SinceEventId  int64                  `protobuf:"varint,2,opt,name=since_event_id,json=sinceEventId,proto3" json:"since_event_id,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubscribeRequest) Reset() {
	*x = EventSubscribeRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscribeRequest) ProtoMessage() {}

func (x *EventSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscribeRequest.ProtoReflect.Descriptor instead.
func (*EventSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{29}
}

func (x *EventSubscribeRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *EventSubscribeRequest) GetSinceEventId() int64 {
	if x != nil {
		return x.SinceEventId
	}
	return 0
}

func (x *EventSubscribeRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// EventMessage - 单条订阅事件。
// envelope_json 必须是平台现场重签的 CallbackEnvelope JSON 原文，客户端基于其中 payload 原文验签。
type EventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EnvelopeJson  []byte                 `protobuf:"bytes,2,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_licence_v1_runtime_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{30}
}

func (x *EventMessage) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventMessage) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

var File_licence_v1_runtime_proto protoreflect.FileDescriptor

const file_licence_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x18licence/v1/runtime.proto\x12\x13licenhub.licence.v1\"\xea\x01\n" +
	"\x0fActivateRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1f\n" +
	"\vinstance_no\x18\x02 \x01(\tR\n" +
	"instanceNo\x12)\n" +
	"\x10fingerprint_hash\x18\x03 \x01(\tR\x0ffingerprintHash\x12*\n" +
	"\x11client_public_key\x18\x04 \x01(\tR\x0fclientPublicKey\x12\x1f\n" +
	"\vclient_time\x18\x05 \x01(\x03R\n" +
	"clientTime\x12\x1f\n" +
	"\vdevice_name\x18\x06 \x01(\tR\n" +
	"deviceName\"\xb1\x02\n" +
	"\x0fValidateRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12)\n" +
	"\x10fingerprint_hash\x18\x02 \x01(\tR\x0ffingerprintHash\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\afeature\x18\x04 \x01(\tR\afeature\x12E\n" +
	"\x05usage\x18\x05 \x03(\v2/.licenhub.licence.v1.ValidateRequest.UsageEntryR\x05usage\x12\x1f\n" +
	"\vclient_time\x18\x06 \x01(\x03R\n" +
	"clientTime\x1a8\n" +
	"\n" +
	"UsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"6\n" +
	"\x15CurrentLicenseRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\"\xec\x01\n" +
	"\x10ProvisionRequest\x12#\n" +
	"\rtemplate_code\x18\x01 \x01(\tR\ftemplateCode\x12'\n" +
	"\x0fprovision_token\x18\x02 \x01(\tR\x0eprovisionToken\x12\x1d\n" +
	"\n" +
	"install_sn\x18\x03 \x01(\tR\tinstallSn\x12)\n" +
	"\x10fingerprint_hash\x18\x04 \x01(\tR\x0ffingerprintHash\x12\x1f\n" +
	"\vdevice_name\x18\x05 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vclient_time\x18\x06 \x01(\x03R\n" +
	"clientTime\"\xaf\x01\n" +
	"\rRedeemRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"install_sn\x18\x02 \x01(\tR\tinstallSn\x12)\n" +
	"\x10fingerprint_hash\x18\x03 \x01(\tR\x0ffingerprintHash\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vclient_time\x18\x05 \x01(\x03R\n" +
	"clientTime\"\x9a\x02\n" +
	"\x11ProvisionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x1d\n" +
	"\n" +
	"license_no\x18\x03 \x01(\tR\tlicenseNo\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\tR\x04salt\x12%\n" +
	"\x0ebinding_policy\x18\x05 \x01(\tR\rbindingPolicy\x12\x1d\n" +
	"\n" +
	"seat_limit\x18\x06 \x01(\x05R\tseatLimit\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x1a\n" +
	"\breissued\x18\b \x01(\bR\breissued\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"\x91\x02\n" +
	"\x0fRuntimeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12#\n" +
	"\renvelope_json\x18\x03 \x01(\fR\fenvelopeJson\x12#\n" +
	"\ractivation_no\x18\x04 \x01(\tR\factivationNo\x12)\n" +
	"\x10activation_token\x18\x05 \x01(\tR\x0factivationToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x17\n" +
	"\aseat_no\x18\b \x01(\tR\x06seatNo\"\xb2\x01\n" +
	"\x12UpdateCheckRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12)\n" +
	"\x10fingerprint_hash\x18\x02 \x01(\tR\x0ffingerprintHash\x12\x17\n" +
	"\aos_arch\x18\x03 \x01(\tR\x06osArch\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vclient_time\x18\x05 \x01(\x03R\n" +
	"clientTime\"\xa5\x01\n" +
	"\x13UpdateCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x16\n" +
	"\x06update\x18\x03 \x01(\bR\x06update\x12#\n" +
	"\rmanifest_json\x18\x04 \x01(\fR\fmanifestJson\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x8f\x02\n" +
	"\x13UpdateReportRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1b\n" +
	"\trecord_no\x18\x02 \x01(\tR\brecordNo\x12!\n" +
	"\ffrom_version\x18\x03 \x01(\tR\vfromVersion\x12%\n" +
	"\x0etarget_version\x18\x04 \x01(\tR\rtargetVersion\x12\x1f\n" +
	"\vartifact_no\x18\x05 \x01(\tR\n" +
	"artifactNo\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1f\n" +
	"\vclient_time\x18\b \x01(\x03R\n" +
	"clientTime\"e\n" +
	"\x11UpdateLogsRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1b\n" +
	"\trecord_no\x18\x02 \x01(\tR\brecordNo\x12\x14\n" +
	"\x05lines\x18\x03 \x03(\tR\x05lines\"\x86\x01\n" +
	"\x14UpdateReportResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x1b\n" +
	"\trecord_no\x18\x03 \x01(\tR\brecordNo\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"Q\n" +
	"\x11TenantSyncRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1d\n" +
	"\n" +
	"since_time\x18\x02 \x01(\x03R\tsinceTime\"I\n" +
	"\x0eTenantManifest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"menus_json\x18\x02 \x01(\fR\tmenusJson\"n\n" +
	"\x0eTenantSyncItem\x12\x1f\n" +
	"\vtenant_code\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\renvelope_json\x18\x03 \x01(\fR\fenvelopeJson\"\xf3\x02\n" +
	"\x12TenantSyncResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x1b\n" +
	"\tsync_time\x18\x03 \x01(\x03R\bsyncTime\x12=\n" +
	"\atenants\x18\x05 \x03(\v2#.licenhub.licence.v1.TenantSyncItemR\atenants\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12P\n" +
	"\x11platform_manifest\x18\a \x01(\v2#.licenhub.licence.v1.TenantManifestR\x10platformManifest\x12L\n" +
	"\x0ftenant_manifest\x18\b \x01(\v2#.licenhub.licence.v1.TenantManifestR\x0etenantManifestJ\x04\b\x04\x10\x05R\bmanifest\"L\n" +
	"\x13TenantSearchRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"T\n" +
	"\x10TenantSearchItem\x12\x1f\n" +
	"\vtenant_code\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x1f\n" +
	"\vtenant_name\x18\x02 \x01(\tR\n" +
	"tenantName\"\xaa\x01\n" +
	"\x14TenantSearchResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12?\n" +
	"\atenants\x18\x03 \x03(\v2%.licenhub.licence.v1.TenantSearchItemR\atenants\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x92\x02\n" +
	"\x15TenantValidateRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1f\n" +
	"\vtenant_code\x18\x02 \x01(\tR\n" +
	"tenantCode\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\afeature\x18\x04 \x01(\tR\afeature\x12K\n" +
	"\x05usage\x18\x05 \x03(\v25.licenhub.licence.v1.TenantValidateRequest.UsageEntryR\x05usage\x1a8\n" +
	"\n" +
	"UsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"V\n" +
	"\x14TenantCurrentRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1f\n" +
	"\vtenant_code\x18\x02 \x01(\tR\n" +
	"tenantCode\"\x88\x01\n" +
	"\x0eTenantResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12#\n" +
	"\renvelope_json\x18\x03 \x01(\fR\fenvelopeJson\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"&\n" +
	"\x18ProjectConfigSyncRequestJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\"3\n" +
	"\x19ProjectConfigSyncResponseJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"~\n" +
	"\x19PlatformConfigSyncRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x05R\tprojectId\x12#\n" +
	"\rsince_version\x18\x03 \x01(\x05R\fsinceVersion\"\x94\x01\n" +
	"\x1aPlatformConfigSyncResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12#\n" +
	"\renvelope_json\x18\x03 \x01(\fR\fenvelopeJson\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"?\n" +
	"\x15ConfigConsumptionItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x81\x01\n" +
	"\x1eConfigConsumptionReportRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12@\n" +
	"\x05items\x18\x02 \x03(\v2*.licenhub.licence.v1.ConfigConsumptionItemR\x05items\"t\n" +
	"\x1fConfigConsumptionReportResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"{\n" +
	"\x15EventSubscribeRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12$\n" +
	"\x0esince_event_id\x18\x02 \x01(\x03R\fsinceEventId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"N\n" +
	"\fEventMessage\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12#\n" +
	"\renvelope_json\x18\x02 \x01(\fR\fenvelopeJson2\xd6\x03\n" +
	"\x15LicenseRuntimeService\x12V\n" +
	"\bActivate\x12$.licenhub.licence.v1.ActivateRequest\x1a$.licenhub.licence.v1.RuntimeResponse\x12V\n" +
	"\bValidate\x12$.licenhub.licence.v1.ValidateRequest\x1a$.licenhub.licence.v1.RuntimeResponse\x12[\n" +
	"\aCurrent\x12*.licenhub.licence.v1.CurrentLicenseRequest\x1a$.licenhub.licence.v1.RuntimeResponse\x12Z\n" +
	"\tProvision\x12%.licenhub.licence.v1.ProvisionRequest\x1a&.licenhub.licence.v1.ProvisionResponse\x12T\n" +
	"\x06Redeem\x12\".licenhub.licence.v1.RedeemRequest\x1a&.licenhub.licence.v1.ProvisionResponse2\xb2\x02\n" +
	"\x14UpdateRuntimeService\x12Z\n" +
	"\x05Check\x12'.licenhub.licence.v1.UpdateCheckRequest\x1a(.licenhub.licence.v1.UpdateCheckResponse\x12]\n" +
	"\x06Report\x12(.licenhub.licence.v1.UpdateReportRequest\x1a).licenhub.licence.v1.UpdateReportResponse\x12_\n" +
	"\n" +
	"AppendLogs\x12&.licenhub.licence.v1.UpdateLogsRequest\x1a).licenhub.licence.v1.UpdateReportResponse2\x84\x03\n" +
	"\x12SaasRuntimeService\x12W\n" +
	"\x04Sync\x12&.licenhub.licence.v1.TenantSyncRequest\x1a'.licenhub.licence.v1.TenantSyncResponse\x12]\n" +
	"\x06Search\x12(.licenhub.licence.v1.TenantSearchRequest\x1a).licenhub.licence.v1.TenantSearchResponse\x12[\n" +
	"\bValidate\x12*.licenhub.licence.v1.TenantValidateRequest\x1a#.licenhub.licence.v1.TenantResponse\x12Y\n" +
	"\aCurrent\x12).licenhub.licence.v1.TenantCurrentRequest\x1a#.licenhub.licence.v1.TenantResponse2\x8e\x02\n" +
	"\x1cPlatformConfigRuntimeService\x12g\n" +
	"\x04Sync\x12..licenhub.licence.v1.PlatformConfigSyncRequest\x1a/.licenhub.licence.v1.PlatformConfigSyncResponse\x12\x84\x01\n" +
	"\x17ReportConfigConsumption\x123.licenhub.licence.v1.ConfigConsumptionReportRequest\x1a4.licenhub.licence.v1.ConfigConsumptionReportResponse2s\n" +
	"\x13EventRuntimeService\x12\\\n" +
	"\tSubscribe\x12*.licenhub.licence.v1.EventSubscribeRequest\x1a!.licenhub.licence.v1.EventMessage0\x01B<Z:github.com/inis-io/aide/licence/proto/licence/v1;licencev1b\x06proto3"

var (
	file_licence_v1_runtime_proto_rawDescOnce sync.Once
	file_licence_v1_runtime_proto_rawDescData []byte
)

func file_licence_v1_runtime_proto_rawDescGZIP() []byte {
	file_licence_v1_runtime_proto_rawDescOnce.Do(func() {
		file_licence_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_licence_v1_runtime_proto_rawDesc), len(file_licence_v1_runtime_proto_rawDesc)))
	})
	return file_licence_v1_runtime_proto_rawDescData
}

var file_licence_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_licence_v1_runtime_proto_goTypes = []any{
	(*ActivateRequest)(nil),                 // 0: licenhub.licence.v1.ActivateRequest
	(*ValidateRequest)(nil),                 // 1: licenhub.licence.v1.ValidateRequest
	(*CurrentLicenseRequest)(nil),           // 2: licenhub.licence.v1.CurrentLicenseRequest
	(*ProvisionRequest)(nil),                // 3: licenhub.licence.v1.ProvisionRequest
	(*RedeemRequest)(nil),                   // 4: licenhub.licence.v1.RedeemRequest
	(*ProvisionResponse)(nil),               // 5: licenhub.licence.v1.ProvisionResponse
	(*RuntimeResponse)(nil),                 // 6: licenhub.licence.v1.RuntimeResponse
	(*UpdateCheckRequest)(nil),              // 7: licenhub.licence.v1.UpdateCheckRequest
	(*UpdateCheckResponse)(nil),             // 8: licenhub.licence.v1.UpdateCheckResponse
	(*UpdateReportRequest)(nil),             // 9: licenhub.licence.v1.UpdateReportRequest
	(*UpdateLogsRequest)(nil),               // 10: licenhub.licence.v1.UpdateLogsRequest
	(*UpdateReportResponse)(nil),            // 11: licenhub.licence.v1.UpdateReportResponse
	(*TenantSyncRequest)(nil),               // 12: licenhub.licence.v1.TenantSyncRequest
	(*TenantManifest)(nil),                  // 13: licenhub.licence.v1.TenantManifest
	(*TenantSyncItem)(nil),                  // 14: licenhub.licence.v1.TenantSyncItem
	(*TenantSyncResponse)(nil),              // 15: licenhub.licence.v1.TenantSyncResponse
	(*TenantSearchRequest)(nil),             // 16: licenhub.licence.v1.TenantSearchRequest
	(*TenantSearchItem)(nil),                // 17: licenhub.licence.v1.TenantSearchItem
	(*TenantSearchResponse)(nil),            // 18: licenhub.licence.v1.TenantSearchResponse
	(*TenantValidateRequest)(nil),           // 19: licenhub.licence.v1.TenantValidateRequest
	(*TenantCurrentRequest)(nil),            // 20: licenhub.licence.v1.TenantCurrentRequest
	(*TenantResponse)(nil),                  // 21: licenhub.licence.v1.TenantResponse
	(*ProjectConfigSyncRequest)(nil),        // 22: licenhub.licence.v1.ProjectConfigSyncRequest
	(*ProjectConfigSyncResponse)(nil),       // 23: licenhub.licence.v1.ProjectConfigSyncResponse
	(*PlatformConfigSyncRequest)(nil),       // 24: licenhub.licence.v1.PlatformConfigSyncRequest
	(*PlatformConfigSyncResponse)(nil),      // 25: licenhub.licence.v1.PlatformConfigSyncResponse
	(*ConfigConsumptionItem)(nil),           // 26: licenhub.licence.v1.ConfigConsumptionItem
	(*ConfigConsumptionReportRequest)(nil),  // 27: licenhub.licence.v1.ConfigConsumptionReportRequest
	(*ConfigConsumptionReportResponse)(nil), // 28: licenhub.licence.v1.ConfigConsumptionReportResponse
	(*EventSubscribeRequest)(nil),           // 29: licenhub.licence.v1.EventSubscribeRequest
	(*EventMessage)(nil),                    // 30: licenhub.licence.v1.EventMessage
	nil,                                     // 31: licenhub.licence.v1.ValidateRequest.UsageEntry
	nil,                                     // 32: licenhub.licence.v1.TenantValidateRequest.UsageEntry
}
var file_licence_v1_runtime_proto_depIdxs = []int32{
	31, // 0: licenhub.licence.v1.ValidateRequest.usage:type_name -> licenhub.licence.v1.ValidateRequest.UsageEntry
	14, // 1: licenhub.licence.v1.TenantSyncResponse.tenants:type_name -> licenhub.licence.v1.TenantSyncItem
	13, // 2: licenhub.licence.v1.TenantSyncResponse.platform_manifest:type_name -> licenhub.licence.v1.TenantManifest
	13, // 3: licenhub.licence.v1.TenantSyncResponse.tenant_manifest:type_name -> licenhub.licence.v1.TenantManifest
	17, // 4: licenhub.licence.v1.TenantSearchResponse.tenants:type_name -> licenhub.licence.v1.TenantSearchItem
	32, // 5: licenhub.licence.v1.TenantValidateRequest.usage:type_name -> licenhub.licence.v1.TenantValidateRequest.UsageEntry
	26, // 6: licenhub.licence.v1.ConfigConsumptionReportRequest.items:type_name -> licenhub.licence.v1.ConfigConsumptionItem
	0,  // 7: licenhub.licence.v1.LicenseRuntimeService.Activate:input_type -> licenhub.licence.v1.ActivateRequest
	1,  // 8: licenhub.licence.v1.LicenseRuntimeService.Validate:input_type -> licenhub.licence.v1.ValidateRequest
	2,  // 9: licenhub.licence.v1.LicenseRuntimeService.Current:input_type -> licenhub.licence.v1.CurrentLicenseRequest
	3,  // 10: licenhub.licence.v1.LicenseRuntimeService.Provision:input_type -> licenhub.licence.v1.ProvisionRequest
	4,  // 11: licenhub.licence.v1.LicenseRuntimeService.Redeem:input_type -> licenhub.licence.v1.RedeemRequest
	7,  // 12: licenhub.licence.v1.UpdateRuntimeService.Check:input_type -> licenhub.licence.v1.UpdateCheckRequest
	9,  // 13: licenhub.licence.v1.UpdateRuntimeService.Report:input_type -> licenhub.licence.v1.UpdateReportRequest
	10, // 14: licenhub.licence.v1.UpdateRuntimeService.AppendLogs:input_type -> licenhub.licence.v1.UpdateLogsRequest
	12, // 15: licenhub.licence.v1.SaasRuntimeService.Sync:input_type -> licenhub.licence.v1.TenantSyncRequest
	16, // 16: licenhub.licence.v1.SaasRuntimeService.Search:input_type -> licenhub.licence.v1.TenantSearchRequest
	19, // 17: licenhub.licence.v1.SaasRuntimeService.Validate:input_type -> licenhub.licence.v1.TenantValidateRequest
	20, // 18: licenhub.licence.v1.SaasRuntimeService.Current:input_type -> licenhub.licence.v1.TenantCurrentRequest
	24, // 19: licenhub.licence.v1.PlatformConfigRuntimeService.Sync:input_type -> licenhub.licence.v1.PlatformConfigSyncRequest
	27, // 20: licenhub.licence.v1.PlatformConfigRuntimeService.ReportConfigConsumption:input_type -> licenhub.licence.v1.ConfigConsumptionReportRequest
	29, // 21: licenhub.licence.v1.EventRuntimeService.Subscribe:input_type -> licenhub.licence.v1.EventSubscribeRequest
	6,  // 22: licenhub.licence.v1.LicenseRuntimeService.Activate:output_type -> licenhub.licence.v1.RuntimeResponse
	6,  // 23: licenhub.licence.v1.LicenseRuntimeService.Validate:output_type -> licenhub.licence.v1.RuntimeResponse
	6,  // 24: licenhub.licence.v1.LicenseRuntimeService.Current:output_type -> licenhub.licence.v1.RuntimeResponse
	5,  // 25: licenhub.licence.v1.LicenseRuntimeService.Provision:output_type -> licenhub.licence.v1.ProvisionResponse
	5,  // 26: licenhub.licence.v1.LicenseRuntimeService.Redeem:output_type -> licenhub.licence.v1.ProvisionResponse
	8,  // 27: licenhub.licence.v1.UpdateRuntimeService.Check:output_type -> licenhub.licence.v1.UpdateCheckResponse
	11, // 28: licenhub.licence.v1.UpdateRuntimeService.Report:output_type -> licenhub.licence.v1.UpdateReportResponse
	11, // 29: licenhub.licence.v1.UpdateRuntimeService.AppendLogs:output_type -> licenhub.licence.v1.UpdateReportResponse
	15, // 30: licenhub.licence.v1.SaasRuntimeService.Sync:output_type -> licenhub.licence.v1.TenantSyncResponse
	18, // 31: licenhub.licence.v1.SaasRuntimeService.Search:output_type -> licenhub.licence.v1.TenantSearchResponse
	21, // 32: licenhub.licence.v1.SaasRuntimeService.Validate:output_type -> licenhub.licence.v1.TenantResponse
	21, // 33: licenhub.licence.v1.SaasRuntimeService.Current:output_type -> licenhub.licence.v1.TenantResponse
	25, // 34: licenhub.licence.v1.PlatformConfigRuntimeService.Sync:output_type -> licenhub.licence.v1.PlatformConfigSyncResponse
	28, // 35: licenhub.licence.v1.PlatformConfigRuntimeService.ReportConfigConsumption:output_type -> licenhub.licence.v1.ConfigConsumptionReportResponse
	30, // 36: licenhub.licence.v1.EventRuntimeService.Subscribe:output_type -> licenhub.licence.v1.EventMessage
	22, // [22:37] is the sub-list for method output_type
	7,  // [7:22] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_licence_v1_runtime_proto_init() }
func file_licence_v1_runtime_proto_init() {
	if File_licence_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_licence_v1_runtime_proto_rawDesc), len(file_licence_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_licence_v1_runtime_proto_goTypes,
		DependencyIndexes: file_licence_v1_runtime_proto_depIdxs,
		MessageInfos:      file_licence_v1_runtime_proto_msgTypes,
	}.Build()
	File_licence_v1_runtime_proto = out.File
	file_licence_v1_runtime_proto_goTypes = nil
	file_licence_v1_runtime_proto_depIdxs = nil
}
