// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: licence/v1/runtime.proto

package licencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo       string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	InstanceNo      string                 `protobuf:"bytes,2,opt,name=instance_no,json=instanceNo,proto3" json:"instance_no,omitempty"`
	FingerprintHash string                 `protobuf:"bytes,3,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	ClientPublicKey string                 `protobuf:"bytes,4,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	ClientTime      int64                  `protobuf:"varint,5,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *ActivateRequest) GetInstanceNo() string {
	if x != nil {
		return x.InstanceNo
	}
	return ""
}

func (x *ActivateRequest) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *ActivateRequest) GetClientPublicKey() string {
	if x != nil {
		return x.ClientPublicKey
	}
	return ""
}

func (x *ActivateRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type ValidateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo       string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	FingerprintHash string                 `protobuf:"bytes,2,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Feature         string                 `protobuf:"bytes,4,opt,name=feature,proto3" json:"feature,omitempty"`
	Usage           map[string]int64       `protobuf:"bytes,5,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ClientTime      int64                  `protobuf:"varint,6,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *ValidateRequest) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *ValidateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ValidateRequest) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *ValidateRequest) GetUsage() map[string]int64 {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ValidateRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type CurrentLicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentLicenseRequest) Reset() {
	*x = CurrentLicenseRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentLicenseRequest) ProtoMessage() {}

func (x *CurrentLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentLicenseRequest.ProtoReflect.Descriptor instead.
func (*CurrentLicenseRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *CurrentLicenseRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

// RuntimeResponse - 许可证运行面统一响应。
// envelope_json 必须是平台签发的 JSON 原文，客户端基于其中 payload 原文验签。
type RuntimeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime      int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	EnvelopeJson    []byte                 `protobuf:"bytes,3,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	ActivationNo    string                 `protobuf:"bytes,4,opt,name=activation_no,json=activationNo,proto3" json:"activation_no,omitempty"`
	ActivationToken string                 `protobuf:"bytes,5,opt,name=activation_token,json=activationToken,proto3" json:"activation_token,omitempty"`
	ExpiresAt       int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Message         string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeResponse) Reset() {
	*x = RuntimeResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeResponse) ProtoMessage() {}

func (x *RuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeResponse.ProtoReflect.Descriptor instead.
func (*RuntimeResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuntimeResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *RuntimeResponse) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

func (x *RuntimeResponse) GetActivationNo() string {
	if x != nil {
		return x.ActivationNo
	}
	return ""
}

func (x *RuntimeResponse) GetActivationToken() string {
	if x != nil {
		return x.ActivationToken
	}
	return ""
}

func (x *RuntimeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RuntimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCheckRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo       string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	FingerprintHash string                 `protobuf:"bytes,2,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	OsArch          string                 `protobuf:"bytes,3,opt,name=os_arch,json=osArch,proto3" json:"os_arch,omitempty"`
	Version         string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	ClientTime      int64                  `protobuf:"varint,5,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCheckRequest) Reset() {
	*x = UpdateCheckRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckRequest) ProtoMessage() {}

func (x *UpdateCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckRequest.ProtoReflect.Descriptor instead.
func (*UpdateCheckRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCheckRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *UpdateCheckRequest) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *UpdateCheckRequest) GetOsArch() string {
	if x != nil {
		return x.OsArch
	}
	return ""
}

func (x *UpdateCheckRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateCheckRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type UpdateCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Update        bool                   `protobuf:"varint,3,opt,name=update,proto3" json:"update,omitempty"`
	ManifestJson  []byte                 `protobuf:"bytes,4,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCheckResponse) Reset() {
	*x = UpdateCheckResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckResponse) ProtoMessage() {}

func (x *UpdateCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckResponse.ProtoReflect.Descriptor instead.
func (*UpdateCheckResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateCheckResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *UpdateCheckResponse) GetUpdate() bool {
	if x != nil {
		return x.Update
	}
	return false
}

func (x *UpdateCheckResponse) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

func (x *UpdateCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	RecordNo      string                 `protobuf:"bytes,2,opt,name=record_no,json=recordNo,proto3" json:"record_no,omitempty"`
	FromVersion   string                 `protobuf:"bytes,3,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	TargetVersion string                 `protobuf:"bytes,4,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	ArtifactNo    string                 `protobuf:"bytes,5,opt,name=artifact_no,json=artifactNo,proto3" json:"artifact_no,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	ClientTime    int64                  `protobuf:"varint,8,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReportRequest) Reset() {
	*x = UpdateReportRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReportRequest) ProtoMessage() {}

func (x *UpdateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReportRequest.ProtoReflect.Descriptor instead.
func (*UpdateReportRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateReportRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *UpdateReportRequest) GetRecordNo() string {
	if x != nil {
		return x.RecordNo
	}
	return ""
}

func (x *UpdateReportRequest) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *UpdateReportRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *UpdateReportRequest) GetArtifactNo() string {
	if x != nil {
		return x.ArtifactNo
	}
	return ""
}

func (x *UpdateReportRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateReportRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateReportRequest) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type UpdateLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	RecordNo      string                 `protobuf:"bytes,2,opt,name=record_no,json=recordNo,proto3" json:"record_no,omitempty"`
	Lines         []string               `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLogsRequest) Reset() {
	*x = UpdateLogsRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLogsRequest) ProtoMessage() {}

func (x *UpdateLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLogsRequest.ProtoReflect.Descriptor instead.
func (*UpdateLogsRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLogsRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *UpdateLogsRequest) GetRecordNo() string {
	if x != nil {
		return x.RecordNo
	}
	return ""
}

func (x *UpdateLogsRequest) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type UpdateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	RecordNo      string                 `protobuf:"bytes,3,opt,name=record_no,json=recordNo,proto3" json:"record_no,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReportResponse) Reset() {
	*x = UpdateReportResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReportResponse) ProtoMessage() {}

func (x *UpdateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReportResponse.ProtoReflect.Descriptor instead.
func (*UpdateReportResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateReportResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *UpdateReportResponse) GetRecordNo() string {
	if x != nil {
		return x.RecordNo
	}
	return ""
}

func (x *UpdateReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TenantSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	SinceTime     int64                  `protobuf:"varint,2,opt,name=since_time,json=sinceTime,proto3" json:"since_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSyncRequest) Reset() {
	*x = TenantSyncRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSyncRequest) ProtoMessage() {}

func (x *TenantSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSyncRequest.ProtoReflect.Descriptor instead.
func (*TenantSyncRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *TenantSyncRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *TenantSyncRequest) GetSinceTime() int64 {
	if x != nil {
		return x.SinceTime
	}
	return 0
}

type TenantManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MenusJson     []byte                 `protobuf:"bytes,2,opt,name=menus_json,json=menusJson,proto3" json:"menus_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantManifest) Reset() {
	*x = TenantManifest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantManifest) ProtoMessage() {}

func (x *TenantManifest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantManifest.ProtoReflect.Descriptor instead.
func (*TenantManifest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *TenantManifest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TenantManifest) GetMenusJson() []byte {
	if x != nil {
		return x.MenusJson
	}
	return nil
}

type TenantSyncItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EnvelopeJson  []byte                 `protobuf:"bytes,3,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSyncItem) Reset() {
	*x = TenantSyncItem{}
	mi := &file_licence_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSyncItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSyncItem) ProtoMessage() {}

func (x *TenantSyncItem) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSyncItem.ProtoReflect.Descriptor instead.
func (*TenantSyncItem) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *TenantSyncItem) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *TenantSyncItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantSyncItem) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

type TenantSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	SyncTime      int64                  `protobuf:"varint,3,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	Manifest      *TenantManifest        `protobuf:"bytes,4,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Tenants       []*TenantSyncItem      `protobuf:"bytes,5,rep,name=tenants,proto3" json:"tenants,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSyncResponse) Reset() {
	*x = TenantSyncResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSyncResponse) ProtoMessage() {}

func (x *TenantSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSyncResponse.ProtoReflect.Descriptor instead.
func (*TenantSyncResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *TenantSyncResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *TenantSyncResponse) GetSyncTime() int64 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

func (x *TenantSyncResponse) GetManifest() *TenantManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *TenantSyncResponse) GetTenants() []*TenantSyncItem {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *TenantSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TenantValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	TenantCode    string                 `protobuf:"bytes,2,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Feature       string                 `protobuf:"bytes,4,opt,name=feature,proto3" json:"feature,omitempty"`
	Usage         map[string]int64       `protobuf:"bytes,5,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantValidateRequest) Reset() {
	*x = TenantValidateRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantValidateRequest) ProtoMessage() {}

func (x *TenantValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantValidateRequest.ProtoReflect.Descriptor instead.
func (*TenantValidateRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *TenantValidateRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *TenantValidateRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *TenantValidateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TenantValidateRequest) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *TenantValidateRequest) GetUsage() map[string]int64 {
	if x != nil {
		return x.Usage
	}
	return nil
}

type TenantCurrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	TenantCode    string                 `protobuf:"bytes,2,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantCurrentRequest) Reset() {
	*x = TenantCurrentRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantCurrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantCurrentRequest) ProtoMessage() {}

func (x *TenantCurrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantCurrentRequest.ProtoReflect.Descriptor instead.
func (*TenantCurrentRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *TenantCurrentRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *TenantCurrentRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	EnvelopeJson  []byte                 `protobuf:"bytes,3,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *TenantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *TenantResponse) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

func (x *TenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProjectConfigSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	SinceVersion  int32                  `protobuf:"varint,2,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectConfigSyncRequest) Reset() {
	*x = ProjectConfigSyncRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectConfigSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectConfigSyncRequest) ProtoMessage() {}

func (x *ProjectConfigSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectConfigSyncRequest.ProtoReflect.Descriptor instead.
func (*ProjectConfigSyncRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *ProjectConfigSyncRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *ProjectConfigSyncRequest) GetSinceVersion() int32 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

type ProjectConfigSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	EnvelopeJson  []byte                 `protobuf:"bytes,3,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectConfigSyncResponse) Reset() {
	*x = ProjectConfigSyncResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectConfigSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectConfigSyncResponse) ProtoMessage() {}

func (x *ProjectConfigSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectConfigSyncResponse.ProtoReflect.Descriptor instead.
func (*ProjectConfigSyncResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *ProjectConfigSyncResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProjectConfigSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ProjectConfigSyncResponse) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

func (x *ProjectConfigSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlatformConfigSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	ProjectId     int32                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SinceVersion  int32                  `protobuf:"varint,3,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformConfigSyncRequest) Reset() {
	*x = PlatformConfigSyncRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformConfigSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformConfigSyncRequest) ProtoMessage() {}

func (x *PlatformConfigSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformConfigSyncRequest.ProtoReflect.Descriptor instead.
func (*PlatformConfigSyncRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *PlatformConfigSyncRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *PlatformConfigSyncRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PlatformConfigSyncRequest) GetSinceVersion() int32 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

type PlatformConfigSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	EnvelopeJson  []byte                 `protobuf:"bytes,3,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformConfigSyncResponse) Reset() {
	*x = PlatformConfigSyncResponse{}
	mi := &file_licence_v1_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformConfigSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformConfigSyncResponse) ProtoMessage() {}

func (x *PlatformConfigSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformConfigSyncResponse.ProtoReflect.Descriptor instead.
func (*PlatformConfigSyncResponse) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *PlatformConfigSyncResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlatformConfigSyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *PlatformConfigSyncResponse) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

func (x *PlatformConfigSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// EventSubscribeRequest - 事件订阅请求。
// since_event_id 为已消费水位（callback_events.id，0 = 从头）；
// timeout_ms 为长轮询 hold 时长（0 = 服务端默认 10000，硬上限 30000）。
type EventSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	SinceEventId  int64                  `protobuf:"varint,2,opt,name=since_event_id,json=sinceEventId,proto3" json:"since_event_id,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubscribeRequest) Reset() {
	*x = EventSubscribeRequest{}
	mi := &file_licence_v1_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscribeRequest) ProtoMessage() {}

func (x *EventSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscribeRequest.ProtoReflect.Descriptor instead.
func (*EventSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *EventSubscribeRequest) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *EventSubscribeRequest) GetSinceEventId() int64 {
	if x != nil {
		return x.SinceEventId
	}
	return 0
}

func (x *EventSubscribeRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// EventMessage - 单条订阅事件。
// envelope_json 必须是平台现场重签的 CallbackEnvelope JSON 原文，客户端基于其中 payload 原文验签。
type EventMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EnvelopeJson  []byte                 `protobuf:"bytes,2,opt,name=envelope_json,json=envelopeJson,proto3" json:"envelope_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_licence_v1_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_licence_v1_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_licence_v1_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *EventMessage) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventMessage) GetEnvelopeJson() []byte {
	if x != nil {
		return x.EnvelopeJson
	}
	return nil
}

var File_licence_v1_runtime_proto protoreflect.FileDescriptor

const file_licence_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x18licence/v1/runtime.proto\x12\x13licenhub.licence.v1\"\xc9\x01\n" +
	"\x0fActivateRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1f\n" +
	"\vinstance_no\x18\x02 \x01(\tR\n" +
	"instanceNo\x12)\n" +
	"\x10fingerprint_hash\x18\x03 \x01(\tR\x0ffingerprintHash\x12*\n" +
	"\x11client_public_key\x18\x04 \x01(\tR\x0fclientPublicKey\x12\x1f\n" +
	"\vclient_time\x18\x05 \x01(\x03R\n" +
	"clientTime\"\xb1\x02\n" +
	"\x0fValidateRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12)\n" +
	"\x10fingerprint_hash\x18\x02 \x01(\tR\x0ffingerprintHash\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\afeature\x18\x04 \x01(\tR\afeature\x12E\n" +
	"\x05usage\x18\x05 \x03(\v2/.licenhub.licence.v1.ValidateRequest.UsageEntryR\x05usage\x12\x1f\n" +
	"\vclient_time\x18\x06 \x01(\x03R\n" +
	"clientTime\x1a8\n" +
	"\n" +
	"UsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"6\n" +
	"\x15CurrentLicenseRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\"\xf8\x01\n" +
	"\x0fRuntimeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12#\n" +
	"\renvelope_json\x18\x03 \x01(\fR\fenvelopeJson\x12#\n" +
	"\ractivation_no\x18\x04 \x01(\tR\factivationNo\x12)\n" +
	"\x10activation_token\x18\x05 \x01(\tR\x0factivationToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\xb2\x01\n" +
	"\x12UpdateCheckRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12)\n" +
	"\x10fingerprint_hash\x18\x02 \x01(\tR\x0ffingerprintHash\x12\x17\n" +
	"\aos_arch\x18\x03 \x01(\tR\x06osArch\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vclient_time\x18\x05 \x01(\x03R\n" +
	"clientTime\"\xa5\x01\n" +
	"\x13UpdateCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x16\n" +
	"\x06update\x18\x03 \x01(\bR\x06update\x12#\n" +
	"\rmanifest_json\x18\x04 \x01(\fR\fmanifestJson\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x8f\x02\n" +
	"\x13UpdateReportRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1b\n" +
	"\trecord_no\x18\x02 \x01(\tR\brecordNo\x12!\n" +
	"\ffrom_version\x18\x03 \x01(\tR\vfromVersion\x12%\n" +
	"\x0etarget_version\x18\x04 \x01(\tR\rtargetVersion\x12\x1f\n" +
	"\vartifact_no\x18\x05 \x01(\tR\n" +
	"artifactNo\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1f\n" +
	"\vclient_time\x18\b \x01(\x03R\n" +
	"clientTime\"e\n" +
	"\x11UpdateLogsRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1b\n" +
	"\trecord_no\x18\x02 \x01(\tR\brecordNo\x12\x14\n" +
	"\x05lines\x18\x03 \x03(\tR\x05lines\"\x86\x01\n" +
	"\x14UpdateReportResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x1b\n" +
	"\trecord_no\x18\x03 \x01(\tR\brecordNo\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"Q\n" +
	"\x11TenantSyncRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1d\n" +
	"\n" +
	"since_time\x18\x02 \x01(\x03R\tsinceTime\"I\n" +
	"\x0eTenantManifest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"menus_json\x18\x02 \x01(\fR\tmenusJson\"n\n" +
	"\x0eTenantSyncItem\x12\x1f\n" +
	"\vtenant_code\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\renvelope_json\x18\x03 \x01(\fR\fenvelopeJson\"\x84\x02\n" +
	"\x12TenantSyncResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x1b\n" +
	"\tsync_time\x18\x03 \x01(\x03R\bsyncTime\x12?\n" +
	"\bmanifest\x18\x04 \x01(\v2#.licenhub.licence.v1.TenantManifestR\bmanifest\x12=\n" +
	"\atenants\x18\x05 \x03(\v2#.licenhub.licence.v1.TenantSyncItemR\atenants\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x92\x02\n" +
	"\x15TenantValidateRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1f\n" +
	"\vtenant_code\x18\x02 \x01(\tR\n" +
	"tenantCode\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\afeature\x18\x04 \x01(\tR\afeature\x12K\n" +
	"\x05usage\x18\x05 \x03(\v25.licenhub.licence.v1.TenantValidateRequest.UsageEntryR\x05usage\x1a8\n" +
	"\n" +
	"UsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"V\n" +
	"\x14TenantCurrentRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1f\n" +
	"\vtenant_code\x18\x02 \x01(\tR\n" +
	"tenantCode\"\x88\x01\n" +
	"\x0eTenantResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12#\n" +
	"\renvelope_json\x18\x03 \x01(\fR\fenvelopeJson\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"^\n" +
	"\x18ProjectConfigSyncRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12#\n" +
	"\rsince_version\x18\x02 \x01(\x05R\fsinceVersion\"\x93\x01\n" +
	"\x19ProjectConfigSyncResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12#\n" +
	"\renvelope_json\x18\x03 \x01(\fR\fenvelopeJson\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"~\n" +
	"\x19PlatformConfigSyncRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x05R\tprojectId\x12#\n" +
	"\rsince_version\x18\x03 \x01(\x05R\fsinceVersion\"\x94\x01\n" +
	"\x1aPlatformConfigSyncResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12#\n" +
	"\renvelope_json\x18\x03 \x01(\fR\fenvelopeJson\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"{\n" +
	"\x15EventSubscribeRequest\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12$\n" +
	"\x0esince_event_id\x18\x02 \x01(\x03R\fsinceEventId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"N\n" +
	"\fEventMessage\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12#\n" +
	"\renvelope_json\x18\x02 \x01(\fR\fenvelopeJson2\xa4\x02\n" +
	"\x15LicenseRuntimeService\x12V\n" +
	"\bActivate\x12$.licenhub.licence.v1.ActivateRequest\x1a$.licenhub.licence.v1.RuntimeResponse\x12V\n" +
	"\bValidate\x12$.licenhub.licence.v1.ValidateRequest\x1a$.licenhub.licence.v1.RuntimeResponse\x12[\n" +
	"\aCurrent\x12*.licenhub.licence.v1.CurrentLicenseRequest\x1a$.licenhub.licence.v1.RuntimeResponse2\xb2\x02\n" +
	"\x14UpdateRuntimeService\x12Z\n" +
	"\x05Check\x12'.licenhub.licence.v1.UpdateCheckRequest\x1a(.licenhub.licence.v1.UpdateCheckResponse\x12]\n" +
	"\x06Report\x12(.licenhub.licence.v1.UpdateReportRequest\x1a).licenhub.licence.v1.UpdateReportResponse\x12_\n" +
	"\n" +
	"AppendLogs\x12&.licenhub.licence.v1.UpdateLogsRequest\x1a).licenhub.licence.v1.UpdateReportResponse2\xa5\x02\n" +
	"\x12SaasRuntimeService\x12W\n" +
	"\x04Sync\x12&.licenhub.licence.v1.TenantSyncRequest\x1a'.licenhub.licence.v1.TenantSyncResponse\x12[\n" +
	"\bValidate\x12*.licenhub.licence.v1.TenantValidateRequest\x1a#.licenhub.licence.v1.TenantResponse\x12Y\n" +
	"\aCurrent\x12).licenhub.licence.v1.TenantCurrentRequest\x1a#.licenhub.licence.v1.TenantResponse2\x84\x01\n" +
	"\x1bProjectConfigRuntimeService\x12e\n" +
	"\x04Sync\x12-.licenhub.licence.v1.ProjectConfigSyncRequest\x1a..licenhub.licence.v1.ProjectConfigSyncResponse2\x87\x01\n" +
	"\x1cPlatformConfigRuntimeService\x12g\n" +
	"\x04Sync\x12..licenhub.licence.v1.PlatformConfigSyncRequest\x1a/.licenhub.licence.v1.PlatformConfigSyncResponse2s\n" +
	"\x13EventRuntimeService\x12\\\n" +
	"\tSubscribe\x12*.licenhub.licence.v1.EventSubscribeRequest\x1a!.licenhub.licence.v1.EventMessage0\x01B<Z:github.com/inis-io/aide/licence/proto/licence/v1;licencev1b\x06proto3"

var (
	file_licence_v1_runtime_proto_rawDescOnce sync.Once
	file_licence_v1_runtime_proto_rawDescData []byte
)

func file_licence_v1_runtime_proto_rawDescGZIP() []byte {
	file_licence_v1_runtime_proto_rawDescOnce.Do(func() {
		file_licence_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_licence_v1_runtime_proto_rawDesc), len(file_licence_v1_runtime_proto_rawDesc)))
	})
	return file_licence_v1_runtime_proto_rawDescData
}

var file_licence_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_licence_v1_runtime_proto_goTypes = []any{
	(*ActivateRequest)(nil),            // 0: licenhub.licence.v1.ActivateRequest
	(*ValidateRequest)(nil),            // 1: licenhub.licence.v1.ValidateRequest
	(*CurrentLicenseRequest)(nil),      // 2: licenhub.licence.v1.CurrentLicenseRequest
	(*RuntimeResponse)(nil),            // 3: licenhub.licence.v1.RuntimeResponse
	(*UpdateCheckRequest)(nil),         // 4: licenhub.licence.v1.UpdateCheckRequest
	(*UpdateCheckResponse)(nil),        // 5: licenhub.licence.v1.UpdateCheckResponse
	(*UpdateReportRequest)(nil),        // 6: licenhub.licence.v1.UpdateReportRequest
	(*UpdateLogsRequest)(nil),          // 7: licenhub.licence.v1.UpdateLogsRequest
	(*UpdateReportResponse)(nil),       // 8: licenhub.licence.v1.UpdateReportResponse
	(*TenantSyncRequest)(nil),          // 9: licenhub.licence.v1.TenantSyncRequest
	(*TenantManifest)(nil),             // 10: licenhub.licence.v1.TenantManifest
	(*TenantSyncItem)(nil),             // 11: licenhub.licence.v1.TenantSyncItem
	(*TenantSyncResponse)(nil),         // 12: licenhub.licence.v1.TenantSyncResponse
	(*TenantValidateRequest)(nil),      // 13: licenhub.licence.v1.TenantValidateRequest
	(*TenantCurrentRequest)(nil),       // 14: licenhub.licence.v1.TenantCurrentRequest
	(*TenantResponse)(nil),             // 15: licenhub.licence.v1.TenantResponse
	(*ProjectConfigSyncRequest)(nil),   // 16: licenhub.licence.v1.ProjectConfigSyncRequest
	(*ProjectConfigSyncResponse)(nil),  // 17: licenhub.licence.v1.ProjectConfigSyncResponse
	(*PlatformConfigSyncRequest)(nil),  // 18: licenhub.licence.v1.PlatformConfigSyncRequest
	(*PlatformConfigSyncResponse)(nil), // 19: licenhub.licence.v1.PlatformConfigSyncResponse
	(*EventSubscribeRequest)(nil),      // 20: licenhub.licence.v1.EventSubscribeRequest
	(*EventMessage)(nil),               // 21: licenhub.licence.v1.EventMessage
	nil,                                // 22: licenhub.licence.v1.ValidateRequest.UsageEntry
	nil,                                // 23: licenhub.licence.v1.TenantValidateRequest.UsageEntry
}
var file_licence_v1_runtime_proto_depIdxs = []int32{
	22, // 0: licenhub.licence.v1.ValidateRequest.usage:type_name -> licenhub.licence.v1.ValidateRequest.UsageEntry
	10, // 1: licenhub.licence.v1.TenantSyncResponse.manifest:type_name -> licenhub.licence.v1.TenantManifest
	11, // 2: licenhub.licence.v1.TenantSyncResponse.tenants:type_name -> licenhub.licence.v1.TenantSyncItem
	23, // 3: licenhub.licence.v1.TenantValidateRequest.usage:type_name -> licenhub.licence.v1.TenantValidateRequest.UsageEntry
	0,  // 4: licenhub.licence.v1.LicenseRuntimeService.Activate:input_type -> licenhub.licence.v1.ActivateRequest
	1,  // 5: licenhub.licence.v1.LicenseRuntimeService.Validate:input_type -> licenhub.licence.v1.ValidateRequest
	2,  // 6: licenhub.licence.v1.LicenseRuntimeService.Current:input_type -> licenhub.licence.v1.CurrentLicenseRequest
	4,  // 7: licenhub.licence.v1.UpdateRuntimeService.Check:input_type -> licenhub.licence.v1.UpdateCheckRequest
	6,  // 8: licenhub.licence.v1.UpdateRuntimeService.Report:input_type -> licenhub.licence.v1.UpdateReportRequest
	7,  // 9: licenhub.licence.v1.UpdateRuntimeService.AppendLogs:input_type -> licenhub.licence.v1.UpdateLogsRequest
	9,  // 10: licenhub.licence.v1.SaasRuntimeService.Sync:input_type -> licenhub.licence.v1.TenantSyncRequest
	13, // 11: licenhub.licence.v1.SaasRuntimeService.Validate:input_type -> licenhub.licence.v1.TenantValidateRequest
	14, // 12: licenhub.licence.v1.SaasRuntimeService.Current:input_type -> licenhub.licence.v1.TenantCurrentRequest
	16, // 13: licenhub.licence.v1.ProjectConfigRuntimeService.Sync:input_type -> licenhub.licence.v1.ProjectConfigSyncRequest
	18, // 14: licenhub.licence.v1.PlatformConfigRuntimeService.Sync:input_type -> licenhub.licence.v1.PlatformConfigSyncRequest
	20, // 15: licenhub.licence.v1.EventRuntimeService.Subscribe:input_type -> licenhub.licence.v1.EventSubscribeRequest
	3,  // 16: licenhub.licence.v1.LicenseRuntimeService.Activate:output_type -> licenhub.licence.v1.RuntimeResponse
	3,  // 17: licenhub.licence.v1.LicenseRuntimeService.Validate:output_type -> licenhub.licence.v1.RuntimeResponse
	3,  // 18: licenhub.licence.v1.LicenseRuntimeService.Current:output_type -> licenhub.licence.v1.RuntimeResponse
	5,  // 19: licenhub.licence.v1.UpdateRuntimeService.Check:output_type -> licenhub.licence.v1.UpdateCheckResponse
	8,  // 20: licenhub.licence.v1.UpdateRuntimeService.Report:output_type -> licenhub.licence.v1.UpdateReportResponse
	8,  // 21: licenhub.licence.v1.UpdateRuntimeService.AppendLogs:output_type -> licenhub.licence.v1.UpdateReportResponse
	12, // 22: licenhub.licence.v1.SaasRuntimeService.Sync:output_type -> licenhub.licence.v1.TenantSyncResponse
	15, // 23: licenhub.licence.v1.SaasRuntimeService.Validate:output_type -> licenhub.licence.v1.TenantResponse
	15, // 24: licenhub.licence.v1.SaasRuntimeService.Current:output_type -> licenhub.licence.v1.TenantResponse
	17, // 25: licenhub.licence.v1.ProjectConfigRuntimeService.Sync:output_type -> licenhub.licence.v1.ProjectConfigSyncResponse
	19, // 26: licenhub.licence.v1.PlatformConfigRuntimeService.Sync:output_type -> licenhub.licence.v1.PlatformConfigSyncResponse
	21, // 27: licenhub.licence.v1.EventRuntimeService.Subscribe:output_type -> licenhub.licence.v1.EventMessage
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_licence_v1_runtime_proto_init() }
func file_licence_v1_runtime_proto_init() {
	if File_licence_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_licence_v1_runtime_proto_rawDesc), len(file_licence_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_licence_v1_runtime_proto_goTypes,
		DependencyIndexes: file_licence_v1_runtime_proto_depIdxs,
		MessageInfos:      file_licence_v1_runtime_proto_msgTypes,
	}.Build()
	File_licence_v1_runtime_proto = out.File
	file_licence_v1_runtime_proto_goTypes = nil
	file_licence_v1_runtime_proto_depIdxs = nil
}
