// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: licence/v1/runtime.proto

package licencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LicenseRuntimeService_Activate_FullMethodName = "/licenhub.licence.v1.LicenseRuntimeService/Activate"
	LicenseRuntimeService_Validate_FullMethodName = "/licenhub.licence.v1.LicenseRuntimeService/Validate"
	LicenseRuntimeService_Current_FullMethodName  = "/licenhub.licence.v1.LicenseRuntimeService/Current"
)

// LicenseRuntimeServiceClient is the client API for LicenseRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LicenseRuntimeService - 许可证实例运行面。
type LicenseRuntimeServiceClient interface {
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
	Current(ctx context.Context, in *CurrentLicenseRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
}

type licenseRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLicenseRuntimeServiceClient(cc grpc.ClientConnInterface) LicenseRuntimeServiceClient {
	return &licenseRuntimeServiceClient{cc}
}

func (c *licenseRuntimeServiceClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, LicenseRuntimeService_Activate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseRuntimeServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, LicenseRuntimeService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseRuntimeServiceClient) Current(ctx context.Context, in *CurrentLicenseRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, LicenseRuntimeService_Current_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LicenseRuntimeServiceServer is the server API for LicenseRuntimeService service.
// All implementations must embed UnimplementedLicenseRuntimeServiceServer
// for forward compatibility.
//
// LicenseRuntimeService - 许可证实例运行面。
type LicenseRuntimeServiceServer interface {
	Activate(context.Context, *ActivateRequest) (*RuntimeResponse, error)
	Validate(context.Context, *ValidateRequest) (*RuntimeResponse, error)
	Current(context.Context, *CurrentLicenseRequest) (*RuntimeResponse, error)
	mustEmbedUnimplementedLicenseRuntimeServiceServer()
}

// UnimplementedLicenseRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLicenseRuntimeServiceServer struct{}

func (UnimplementedLicenseRuntimeServiceServer) Activate(context.Context, *ActivateRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Activate not implemented")
}
func (UnimplementedLicenseRuntimeServiceServer) Validate(context.Context, *ValidateRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedLicenseRuntimeServiceServer) Current(context.Context, *CurrentLicenseRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Current not implemented")
}
func (UnimplementedLicenseRuntimeServiceServer) mustEmbedUnimplementedLicenseRuntimeServiceServer() {}
func (UnimplementedLicenseRuntimeServiceServer) testEmbeddedByValue()                               {}

// UnsafeLicenseRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LicenseRuntimeServiceServer will
// result in compilation errors.
type UnsafeLicenseRuntimeServiceServer interface {
	mustEmbedUnimplementedLicenseRuntimeServiceServer()
}

func RegisterLicenseRuntimeServiceServer(s grpc.ServiceRegistrar, srv LicenseRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedLicenseRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LicenseRuntimeService_ServiceDesc, srv)
}

func _LicenseRuntimeService_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseRuntimeServiceServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LicenseRuntimeService_Activate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseRuntimeServiceServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LicenseRuntimeService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseRuntimeServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LicenseRuntimeService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseRuntimeServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LicenseRuntimeService_Current_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseRuntimeServiceServer).Current(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LicenseRuntimeService_Current_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseRuntimeServiceServer).Current(ctx, req.(*CurrentLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LicenseRuntimeService_ServiceDesc is the grpc.ServiceDesc for LicenseRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LicenseRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenhub.licence.v1.LicenseRuntimeService",
	HandlerType: (*LicenseRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Activate",
			Handler:    _LicenseRuntimeService_Activate_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _LicenseRuntimeService_Validate_Handler,
		},
		{
			MethodName: "Current",
			Handler:    _LicenseRuntimeService_Current_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "licence/v1/runtime.proto",
}

const (
	UpdateRuntimeService_Check_FullMethodName      = "/licenhub.licence.v1.UpdateRuntimeService/Check"
	UpdateRuntimeService_Report_FullMethodName     = "/licenhub.licence.v1.UpdateRuntimeService/Report"
	UpdateRuntimeService_AppendLogs_FullMethodName = "/licenhub.licence.v1.UpdateRuntimeService/AppendLogs"
)

// UpdateRuntimeServiceClient is the client API for UpdateRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UpdateRuntimeService - 在线更新运行面。
type UpdateRuntimeServiceClient interface {
	Check(ctx context.Context, in *UpdateCheckRequest, opts ...grpc.CallOption) (*UpdateCheckResponse, error)
	Report(ctx context.Context, in *UpdateReportRequest, opts ...grpc.CallOption) (*UpdateReportResponse, error)
	AppendLogs(ctx context.Context, in *UpdateLogsRequest, opts ...grpc.CallOption) (*UpdateReportResponse, error)
}

type updateRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateRuntimeServiceClient(cc grpc.ClientConnInterface) UpdateRuntimeServiceClient {
	return &updateRuntimeServiceClient{cc}
}

func (c *updateRuntimeServiceClient) Check(ctx context.Context, in *UpdateCheckRequest, opts ...grpc.CallOption) (*UpdateCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCheckResponse)
	err := c.cc.Invoke(ctx, UpdateRuntimeService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateRuntimeServiceClient) Report(ctx context.Context, in *UpdateReportRequest, opts ...grpc.CallOption) (*UpdateReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReportResponse)
	err := c.cc.Invoke(ctx, UpdateRuntimeService_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateRuntimeServiceClient) AppendLogs(ctx context.Context, in *UpdateLogsRequest, opts ...grpc.CallOption) (*UpdateReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReportResponse)
	err := c.cc.Invoke(ctx, UpdateRuntimeService_AppendLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateRuntimeServiceServer is the server API for UpdateRuntimeService service.
// All implementations must embed UnimplementedUpdateRuntimeServiceServer
// for forward compatibility.
//
// UpdateRuntimeService - 在线更新运行面。
type UpdateRuntimeServiceServer interface {
	Check(context.Context, *UpdateCheckRequest) (*UpdateCheckResponse, error)
	Report(context.Context, *UpdateReportRequest) (*UpdateReportResponse, error)
	AppendLogs(context.Context, *UpdateLogsRequest) (*UpdateReportResponse, error)
	mustEmbedUnimplementedUpdateRuntimeServiceServer()
}

// UnimplementedUpdateRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateRuntimeServiceServer struct{}

func (UnimplementedUpdateRuntimeServiceServer) Check(context.Context, *UpdateCheckRequest) (*UpdateCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedUpdateRuntimeServiceServer) Report(context.Context, *UpdateReportRequest) (*UpdateReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedUpdateRuntimeServiceServer) AppendLogs(context.Context, *UpdateLogsRequest) (*UpdateReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendLogs not implemented")
}
func (UnimplementedUpdateRuntimeServiceServer) mustEmbedUnimplementedUpdateRuntimeServiceServer() {}
func (UnimplementedUpdateRuntimeServiceServer) testEmbeddedByValue()                              {}

// UnsafeUpdateRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateRuntimeServiceServer will
// result in compilation errors.
type UnsafeUpdateRuntimeServiceServer interface {
	mustEmbedUnimplementedUpdateRuntimeServiceServer()
}

func RegisterUpdateRuntimeServiceServer(s grpc.ServiceRegistrar, srv UpdateRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedUpdateRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateRuntimeService_ServiceDesc, srv)
}

func _UpdateRuntimeService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateRuntimeServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateRuntimeService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateRuntimeServiceServer).Check(ctx, req.(*UpdateCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpdateRuntimeService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateRuntimeServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateRuntimeService_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateRuntimeServiceServer).Report(ctx, req.(*UpdateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpdateRuntimeService_AppendLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateRuntimeServiceServer).AppendLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateRuntimeService_AppendLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateRuntimeServiceServer).AppendLogs(ctx, req.(*UpdateLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateRuntimeService_ServiceDesc is the grpc.ServiceDesc for UpdateRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenhub.licence.v1.UpdateRuntimeService",
	HandlerType: (*UpdateRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _UpdateRuntimeService_Check_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _UpdateRuntimeService_Report_Handler,
		},
		{
			MethodName: "AppendLogs",
			Handler:    _UpdateRuntimeService_AppendLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "licence/v1/runtime.proto",
}

const (
	SaasRuntimeService_Sync_FullMethodName     = "/licenhub.licence.v1.SaasRuntimeService/Sync"
	SaasRuntimeService_Validate_FullMethodName = "/licenhub.licence.v1.SaasRuntimeService/Validate"
	SaasRuntimeService_Current_FullMethodName  = "/licenhub.licence.v1.SaasRuntimeService/Current"
)

// SaasRuntimeServiceClient is the client API for SaasRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SaasRuntimeService - SaaS 租户运行面。
type SaasRuntimeServiceClient interface {
	Sync(ctx context.Context, in *TenantSyncRequest, opts ...grpc.CallOption) (*TenantSyncResponse, error)
	Validate(ctx context.Context, in *TenantValidateRequest, opts ...grpc.CallOption) (*TenantResponse, error)
	Current(ctx context.Context, in *TenantCurrentRequest, opts ...grpc.CallOption) (*TenantResponse, error)
}

type saasRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaasRuntimeServiceClient(cc grpc.ClientConnInterface) SaasRuntimeServiceClient {
	return &saasRuntimeServiceClient{cc}
}

func (c *saasRuntimeServiceClient) Sync(ctx context.Context, in *TenantSyncRequest, opts ...grpc.CallOption) (*TenantSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSyncResponse)
	err := c.cc.Invoke(ctx, SaasRuntimeService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saasRuntimeServiceClient) Validate(ctx context.Context, in *TenantValidateRequest, opts ...grpc.CallOption) (*TenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantResponse)
	err := c.cc.Invoke(ctx, SaasRuntimeService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saasRuntimeServiceClient) Current(ctx context.Context, in *TenantCurrentRequest, opts ...grpc.CallOption) (*TenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantResponse)
	err := c.cc.Invoke(ctx, SaasRuntimeService_Current_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaasRuntimeServiceServer is the server API for SaasRuntimeService service.
// All implementations must embed UnimplementedSaasRuntimeServiceServer
// for forward compatibility.
//
// SaasRuntimeService - SaaS 租户运行面。
type SaasRuntimeServiceServer interface {
	Sync(context.Context, *TenantSyncRequest) (*TenantSyncResponse, error)
	Validate(context.Context, *TenantValidateRequest) (*TenantResponse, error)
	Current(context.Context, *TenantCurrentRequest) (*TenantResponse, error)
	mustEmbedUnimplementedSaasRuntimeServiceServer()
}

// UnimplementedSaasRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSaasRuntimeServiceServer struct{}

func (UnimplementedSaasRuntimeServiceServer) Sync(context.Context, *TenantSyncRequest) (*TenantSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedSaasRuntimeServiceServer) Validate(context.Context, *TenantValidateRequest) (*TenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedSaasRuntimeServiceServer) Current(context.Context, *TenantCurrentRequest) (*TenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Current not implemented")
}
func (UnimplementedSaasRuntimeServiceServer) mustEmbedUnimplementedSaasRuntimeServiceServer() {}
func (UnimplementedSaasRuntimeServiceServer) testEmbeddedByValue()                            {}

// UnsafeSaasRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaasRuntimeServiceServer will
// result in compilation errors.
type UnsafeSaasRuntimeServiceServer interface {
	mustEmbedUnimplementedSaasRuntimeServiceServer()
}

func RegisterSaasRuntimeServiceServer(s grpc.ServiceRegistrar, srv SaasRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedSaasRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SaasRuntimeService_ServiceDesc, srv)
}

func _SaasRuntimeService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaasRuntimeServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaasRuntimeService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaasRuntimeServiceServer).Sync(ctx, req.(*TenantSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaasRuntimeService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaasRuntimeServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaasRuntimeService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaasRuntimeServiceServer).Validate(ctx, req.(*TenantValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaasRuntimeService_Current_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantCurrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaasRuntimeServiceServer).Current(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaasRuntimeService_Current_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaasRuntimeServiceServer).Current(ctx, req.(*TenantCurrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaasRuntimeService_ServiceDesc is the grpc.ServiceDesc for SaasRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaasRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenhub.licence.v1.SaasRuntimeService",
	HandlerType: (*SaasRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _SaasRuntimeService_Sync_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _SaasRuntimeService_Validate_Handler,
		},
		{
			MethodName: "Current",
			Handler:    _SaasRuntimeService_Current_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "licence/v1/runtime.proto",
}

const (
	ProjectConfigRuntimeService_Sync_FullMethodName = "/licenhub.licence.v1.ProjectConfigRuntimeService/Sync"
)

// ProjectConfigRuntimeServiceClient is the client API for ProjectConfigRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProjectConfigRuntimeService - 项目配置运行面。
type ProjectConfigRuntimeServiceClient interface {
	Sync(ctx context.Context, in *ProjectConfigSyncRequest, opts ...grpc.CallOption) (*ProjectConfigSyncResponse, error)
}

type projectConfigRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectConfigRuntimeServiceClient(cc grpc.ClientConnInterface) ProjectConfigRuntimeServiceClient {
	return &projectConfigRuntimeServiceClient{cc}
}

func (c *projectConfigRuntimeServiceClient) Sync(ctx context.Context, in *ProjectConfigSyncRequest, opts ...grpc.CallOption) (*ProjectConfigSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectConfigSyncResponse)
	err := c.cc.Invoke(ctx, ProjectConfigRuntimeService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectConfigRuntimeServiceServer is the server API for ProjectConfigRuntimeService service.
// All implementations must embed UnimplementedProjectConfigRuntimeServiceServer
// for forward compatibility.
//
// ProjectConfigRuntimeService - 项目配置运行面。
type ProjectConfigRuntimeServiceServer interface {
	Sync(context.Context, *ProjectConfigSyncRequest) (*ProjectConfigSyncResponse, error)
	mustEmbedUnimplementedProjectConfigRuntimeServiceServer()
}

// UnimplementedProjectConfigRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectConfigRuntimeServiceServer struct{}

func (UnimplementedProjectConfigRuntimeServiceServer) Sync(context.Context, *ProjectConfigSyncRequest) (*ProjectConfigSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedProjectConfigRuntimeServiceServer) mustEmbedUnimplementedProjectConfigRuntimeServiceServer() {
}
func (UnimplementedProjectConfigRuntimeServiceServer) testEmbeddedByValue() {}

// UnsafeProjectConfigRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectConfigRuntimeServiceServer will
// result in compilation errors.
type UnsafeProjectConfigRuntimeServiceServer interface {
	mustEmbedUnimplementedProjectConfigRuntimeServiceServer()
}

func RegisterProjectConfigRuntimeServiceServer(s grpc.ServiceRegistrar, srv ProjectConfigRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedProjectConfigRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectConfigRuntimeService_ServiceDesc, srv)
}

func _ProjectConfigRuntimeService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectConfigSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectConfigRuntimeServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectConfigRuntimeService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectConfigRuntimeServiceServer).Sync(ctx, req.(*ProjectConfigSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectConfigRuntimeService_ServiceDesc is the grpc.ServiceDesc for ProjectConfigRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectConfigRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenhub.licence.v1.ProjectConfigRuntimeService",
	HandlerType: (*ProjectConfigRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _ProjectConfigRuntimeService_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "licence/v1/runtime.proto",
}
