// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: star/v1/star.proto

package starv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StarAck - 通用回执（code=0 成功；非 0 时 message 为人类可读说明）。
type StarAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 业务码（0 = 成功）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 说明（失败时为失败原因）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarAck) Reset() {
	*x = StarAck{}
	mi := &file_star_v1_star_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarAck) ProtoMessage() {}

func (x *StarAck) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarAck.ProtoReflect.Descriptor instead.
func (*StarAck) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{0}
}

func (x *StarAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StarAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StarJoinRequest - 注册/心跳上送。
type StarJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 实例标识（= deployment_instances.instance_no，身份锚定激活体系）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 舰名
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                       // 舰际 gRPC 地址
	Pubkey        string                 `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                           // 实例 Ed25519 公钥 hex（实例级密钥，私钥不出舰）
	AppVersion    string                 `protobuf:"bytes,5,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"` // im 版本（心跳顺带）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarJoinRequest) Reset() {
	*x = StarJoinRequest{}
	mi := &file_star_v1_star_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarJoinRequest) ProtoMessage() {}

func (x *StarJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarJoinRequest.ProtoReflect.Descriptor instead.
func (*StarJoinRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{1}
}

func (x *StarJoinRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StarJoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StarJoinRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *StarJoinRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *StarJoinRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

// StarJoinResponse - 注册/心跳回执。
type StarJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *StarAck               `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`                                  // 通用回执
	StarStatus    string                 `protobuf:"bytes,2,opt,name=star_status,json=starStatus,proto3" json:"star_status,omitempty"`  // 仲裁资格态：active / suspended / left
	TrustScore    int32                  `protobuf:"varint,3,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"` // 信用分（万分位 0~10000，冷启动 6000 = 0.60）
	Since         int64                  `protobuf:"varint,4,opt,name=since,proto3" json:"since,omitempty"`                             // 目录水位（毫秒戳，供 ListPeers 增量拉取）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarJoinResponse) Reset() {
	*x = StarJoinResponse{}
	mi := &file_star_v1_star_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarJoinResponse) ProtoMessage() {}

func (x *StarJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarJoinResponse.ProtoReflect.Descriptor instead.
func (*StarJoinResponse) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{2}
}

func (x *StarJoinResponse) GetAck() *StarAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *StarJoinResponse) GetStarStatus() string {
	if x != nil {
		return x.StarStatus
	}
	return ""
}

func (x *StarJoinResponse) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *StarJoinResponse) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

// StarListPeersRequest - 目录增量拉取请求。
type StarListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         int64                  `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"` // 目录水位（毫秒戳；0 = 全量）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarListPeersRequest) Reset() {
	*x = StarListPeersRequest{}
	mi := &file_star_v1_star_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarListPeersRequest) ProtoMessage() {}

func (x *StarListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarListPeersRequest.ProtoReflect.Descriptor instead.
func (*StarListPeersRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{3}
}

func (x *StarListPeersRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

// StarPeer - 目录同伴条目。
type StarPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`    // 实例标识
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // 舰名
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                          // 舰际 gRPC 地址
	Pubkey        string                 `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                              // 实例 Ed25519 公钥 hex
	StarStatus    string                 `protobuf:"bytes,5,opt,name=star_status,json=starStatus,proto3" json:"star_status,omitempty"`    // 仲裁资格态：active / suspended / left
	TrustScore    int32                  `protobuf:"varint,6,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`   // 信用分（万分位 0~10000）
	AppVersion    string                 `protobuf:"bytes,7,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`    // im 版本
	LastBeatAt    int64                  `protobuf:"varint,8,opt,name=last_beat_at,json=lastBeatAt,proto3" json:"last_beat_at,omitempty"` // 最近心跳（毫秒戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPeer) Reset() {
	*x = StarPeer{}
	mi := &file_star_v1_star_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPeer) ProtoMessage() {}

func (x *StarPeer) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPeer.ProtoReflect.Descriptor instead.
func (*StarPeer) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{4}
}

func (x *StarPeer) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StarPeer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StarPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *StarPeer) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *StarPeer) GetStarStatus() string {
	if x != nil {
		return x.StarStatus
	}
	return ""
}

func (x *StarPeer) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *StarPeer) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *StarPeer) GetLastBeatAt() int64 {
	if x != nil {
		return x.LastBeatAt
	}
	return 0
}

// StarListPeersResponse - 目录增量拉取回执。
type StarListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *StarAck               `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`      // 通用回执
	Peers         []*StarPeer            `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`  // 自 since 以来变更的同伴
	Since         int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"` // 新目录水位（毫秒戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarListPeersResponse) Reset() {
	*x = StarListPeersResponse{}
	mi := &file_star_v1_star_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarListPeersResponse) ProtoMessage() {}

func (x *StarListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarListPeersResponse.ProtoReflect.Descriptor instead.
func (*StarListPeersResponse) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{5}
}

func (x *StarListPeersResponse) GetAck() *StarAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *StarListPeersResponse) GetPeers() []*StarPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *StarListPeersResponse) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

// StarHotIndexItem - 站内热榜条目（上报即该舰全量快照的一部分）。
type StarHotIndexItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteNoteId  string                 `protobuf:"bytes,1,opt,name=remote_note_id,json=remoteNoteId,proto3" json:"remote_note_id,omitempty"` // 源站笔记标识
	Percentile    int32                  `protobuf:"varint,2,opt,name=percentile,proto3" json:"percentile,omitempty"`                          // 站内百分位（万分位 0~10000）
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                               // 分类过滤标签（可空）
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`                               // 语言过滤标签（可空）
	Meta          []byte                 `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`                                       // 摘要元数据 JSON 原始字节（标题/摘要/作者快照/统计快照/origin_url）
	Embedding     []byte                 `protobuf:"bytes,6,opt,name=embedding,proto3" json:"embedding,omitempty"`                             // float16 压缩笔记向量（联邦召回用，可空）
	PublishedAt   int64                  `protobuf:"varint,7,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`     // 笔记发布时间（毫秒戳，freshness 半衰输入）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarHotIndexItem) Reset() {
	*x = StarHotIndexItem{}
	mi := &file_star_v1_star_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarHotIndexItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarHotIndexItem) ProtoMessage() {}

func (x *StarHotIndexItem) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarHotIndexItem.ProtoReflect.Descriptor instead.
func (*StarHotIndexItem) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{6}
}

func (x *StarHotIndexItem) GetRemoteNoteId() string {
	if x != nil {
		return x.RemoteNoteId
	}
	return ""
}

func (x *StarHotIndexItem) GetPercentile() int32 {
	if x != nil {
		return x.Percentile
	}
	return 0
}

func (x *StarHotIndexItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *StarHotIndexItem) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *StarHotIndexItem) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StarHotIndexItem) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *StarHotIndexItem) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

// StarPushHotIndexRequest - 热榜上报请求。
type StarPushHotIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 来源舰实例标识
	Items         []*StarHotIndexItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                             // 热榜条目批（整批覆盖该舰索引）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPushHotIndexRequest) Reset() {
	*x = StarPushHotIndexRequest{}
	mi := &file_star_v1_star_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPushHotIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPushHotIndexRequest) ProtoMessage() {}

func (x *StarPushHotIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPushHotIndexRequest.ProtoReflect.Descriptor instead.
func (*StarPushHotIndexRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{7}
}

func (x *StarPushHotIndexRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StarPushHotIndexRequest) GetItems() []*StarHotIndexItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// StarPushHotIndexResponse - 热榜上报回执。
type StarPushHotIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *StarAck               `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`            // 通用回执
	Accepted      int32                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // 受理条目数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPushHotIndexResponse) Reset() {
	*x = StarPushHotIndexResponse{}
	mi := &file_star_v1_star_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPushHotIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPushHotIndexResponse) ProtoMessage() {}

func (x *StarPushHotIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPushHotIndexResponse.ProtoReflect.Descriptor instead.
func (*StarPushHotIndexResponse) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{8}
}

func (x *StarPushHotIndexResponse) GetAck() *StarAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *StarPushHotIndexResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

// StarPullGlobalHotRequest - 全网榜拉取请求。
type StarPullGlobalHotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopK          int32                  `protobuf:"varint,1,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"` // 拉取条数上限
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`      // 分类过滤（可空 = 不过滤）
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`      // 语言过滤（可空 = 不过滤）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPullGlobalHotRequest) Reset() {
	*x = StarPullGlobalHotRequest{}
	mi := &file_star_v1_star_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPullGlobalHotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPullGlobalHotRequest) ProtoMessage() {}

func (x *StarPullGlobalHotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPullGlobalHotRequest.ProtoReflect.Descriptor instead.
func (*StarPullGlobalHotRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{9}
}

func (x *StarPullGlobalHotRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *StarPullGlobalHotRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *StarPullGlobalHotRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// StarGlobalHotItem - 全网榜条目。
type StarGlobalHotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`         // 来源舰实例标识
	RemoteNoteId  string                 `protobuf:"bytes,2,opt,name=remote_note_id,json=remoteNoteId,proto3" json:"remote_note_id,omitempty"` // 源站笔记标识
	ScoreNet      int64                  `protobuf:"varint,3,opt,name=score_net,json=scoreNet,proto3" json:"score_net,omitempty"`              // 归一热度分（万分位；percentile × 半衰 × trust，pull 时计算）
	Meta          []byte                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`                                       // 摘要元数据 JSON 原始字节
	Embedding     []byte                 `protobuf:"bytes,5,opt,name=embedding,proto3" json:"embedding,omitempty"`                             // float16 压缩笔记向量（可空）
	OriginUrl     string                 `protobuf:"bytes,6,opt,name=origin_url,json=originUrl,proto3" json:"origin_url,omitempty"`            // 源站笔记链接
	PublishedAt   int64                  `protobuf:"varint,7,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`     // 笔记发布时间（毫秒戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarGlobalHotItem) Reset() {
	*x = StarGlobalHotItem{}
	mi := &file_star_v1_star_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarGlobalHotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarGlobalHotItem) ProtoMessage() {}

func (x *StarGlobalHotItem) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarGlobalHotItem.ProtoReflect.Descriptor instead.
func (*StarGlobalHotItem) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{10}
}

func (x *StarGlobalHotItem) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StarGlobalHotItem) GetRemoteNoteId() string {
	if x != nil {
		return x.RemoteNoteId
	}
	return ""
}

func (x *StarGlobalHotItem) GetScoreNet() int64 {
	if x != nil {
		return x.ScoreNet
	}
	return 0
}

func (x *StarGlobalHotItem) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StarGlobalHotItem) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *StarGlobalHotItem) GetOriginUrl() string {
	if x != nil {
		return x.OriginUrl
	}
	return ""
}

func (x *StarGlobalHotItem) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

// StarPullGlobalHotResponse - 全网榜拉取回执（score_net 降序）。
type StarPullGlobalHotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *StarAck               `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`     // 通用回执
	Items         []*StarGlobalHotItem   `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"` // 全网榜条目
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPullGlobalHotResponse) Reset() {
	*x = StarPullGlobalHotResponse{}
	mi := &file_star_v1_star_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPullGlobalHotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPullGlobalHotResponse) ProtoMessage() {}

func (x *StarPullGlobalHotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPullGlobalHotResponse.ProtoReflect.Descriptor instead.
func (*StarPullGlobalHotResponse) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{11}
}

func (x *StarPullGlobalHotResponse) GetAck() *StarAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *StarPullGlobalHotResponse) GetItems() []*StarGlobalHotItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// StarCreditPurchaseRequest - 点数购入请求（幂等键 request_id = purchase_no）。
type StarCreditPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseNo    string                 `protobuf:"bytes,1,opt,name=purchase_no,json=purchaseNo,proto3" json:"purchase_no,omitempty"` // 购入单号（幂等键）
	Points        int64                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`                          // 购入点数
	AmountFen     int64                  `protobuf:"varint,3,opt,name=amount_fen,json=amountFen,proto3" json:"amount_fen,omitempty"`   // 支付金额（万分）
	RateFen       int64                  `protobuf:"varint,4,opt,name=rate_fen,json=rateFen,proto3" json:"rate_fen,omitempty"`         // 汇率快照（1 点 = rate_fen 万分，默认 10000）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarCreditPurchaseRequest) Reset() {
	*x = StarCreditPurchaseRequest{}
	mi := &file_star_v1_star_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarCreditPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarCreditPurchaseRequest) ProtoMessage() {}

func (x *StarCreditPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarCreditPurchaseRequest.ProtoReflect.Descriptor instead.
func (*StarCreditPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{12}
}

func (x *StarCreditPurchaseRequest) GetPurchaseNo() string {
	if x != nil {
		return x.PurchaseNo
	}
	return ""
}

func (x *StarCreditPurchaseRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *StarCreditPurchaseRequest) GetAmountFen() int64 {
	if x != nil {
		return x.AmountFen
	}
	return 0
}

func (x *StarCreditPurchaseRequest) GetRateFen() int64 {
	if x != nil {
		return x.RateFen
	}
	return 0
}

// StarCreditGrantOutRequest - 点数发放核销请求（幂等键 request_id = grant_no）。
type StarCreditGrantOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantNo       string                 `protobuf:"bytes,1,opt,name=grant_no,json=grantNo,proto3" json:"grant_no,omitempty"`          // 发放核销单号（幂等键）
	Points        int64                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`                          // 发放点数
	TargetNote    string                 `protobuf:"bytes,3,opt,name=target_note,json=targetNote,proto3" json:"target_note,omitempty"` // 目标说明（发放到站内用户的备注）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarCreditGrantOutRequest) Reset() {
	*x = StarCreditGrantOutRequest{}
	mi := &file_star_v1_star_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarCreditGrantOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarCreditGrantOutRequest) ProtoMessage() {}

func (x *StarCreditGrantOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarCreditGrantOutRequest.ProtoReflect.Descriptor instead.
func (*StarCreditGrantOutRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{13}
}

func (x *StarCreditGrantOutRequest) GetGrantNo() string {
	if x != nil {
		return x.GrantNo
	}
	return ""
}

func (x *StarCreditGrantOutRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *StarCreditGrantOutRequest) GetTargetNote() string {
	if x != nil {
		return x.TargetNote
	}
	return ""
}

// StarCreditGrantOutResponse - 点数发放核销回执。
type StarCreditGrantOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *StarAck               `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`                                        // 通用回执
	BalanceAfter  int64                  `protobuf:"varint,2,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"` // 核销后点数池余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarCreditGrantOutResponse) Reset() {
	*x = StarCreditGrantOutResponse{}
	mi := &file_star_v1_star_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarCreditGrantOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarCreditGrantOutResponse) ProtoMessage() {}

func (x *StarCreditGrantOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarCreditGrantOutResponse.ProtoReflect.Descriptor instead.
func (*StarCreditGrantOutResponse) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{14}
}

func (x *StarCreditGrantOutResponse) GetAck() *StarAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *StarCreditGrantOutResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

// StarPromoteOrderCreateRequest - 投流单创建请求（幂等键 request_id = promote_no）。
type StarPromoteOrderCreateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PromoteNo          string                 `protobuf:"bytes,1,opt,name=promote_no,json=promoteNo,proto3" json:"promote_no,omitempty"`                              // 投流单号（幂等键，全联邦唯一）
	NoteOriginInstance string                 `protobuf:"bytes,2,opt,name=note_origin_instance,json=noteOriginInstance,proto3" json:"note_origin_instance,omitempty"` // 被投流笔记的源舰实例标识
	RemoteNoteId       string                 `protobuf:"bytes,3,opt,name=remote_note_id,json=remoteNoteId,proto3" json:"remote_note_id,omitempty"`                   // 源站笔记标识
	FromInstanceId     string                 `protobuf:"bytes,4,opt,name=from_instance_id,json=fromInstanceId,proto3" json:"from_instance_id,omitempty"`             // 发起舰实例标识（hold 账户归属）
	Points             int64                  `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`                                                    // 投入点数
	AmountFen          int64                  `protobuf:"varint,6,opt,name=amount_fen,json=amountFen,proto3" json:"amount_fen,omitempty"`                             // 折算金额（万分，汇率快照）
	TargetViews        int64                  `protobuf:"varint,7,opt,name=target_views,json=targetViews,proto3" json:"target_views,omitempty"`                       // 目标阅读量
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StarPromoteOrderCreateRequest) Reset() {
	*x = StarPromoteOrderCreateRequest{}
	mi := &file_star_v1_star_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPromoteOrderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPromoteOrderCreateRequest) ProtoMessage() {}

func (x *StarPromoteOrderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPromoteOrderCreateRequest.ProtoReflect.Descriptor instead.
func (*StarPromoteOrderCreateRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{15}
}

func (x *StarPromoteOrderCreateRequest) GetPromoteNo() string {
	if x != nil {
		return x.PromoteNo
	}
	return ""
}

func (x *StarPromoteOrderCreateRequest) GetNoteOriginInstance() string {
	if x != nil {
		return x.NoteOriginInstance
	}
	return ""
}

func (x *StarPromoteOrderCreateRequest) GetRemoteNoteId() string {
	if x != nil {
		return x.RemoteNoteId
	}
	return ""
}

func (x *StarPromoteOrderCreateRequest) GetFromInstanceId() string {
	if x != nil {
		return x.FromInstanceId
	}
	return ""
}

func (x *StarPromoteOrderCreateRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *StarPromoteOrderCreateRequest) GetAmountFen() int64 {
	if x != nil {
		return x.AmountFen
	}
	return 0
}

func (x *StarPromoteOrderCreateRequest) GetTargetViews() int64 {
	if x != nil {
		return x.TargetViews
	}
	return 0
}

// StarPromoteOrderSettleRequest - 投流结算请求（幂等键 request_id = promote_no）。
type StarPromoteOrderSettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromoteNo     string                 `protobuf:"bytes,1,opt,name=promote_no,json=promoteNo,proto3" json:"promote_no,omitempty"`        // 投流单号（幂等键）
	DoneViews     int64                  `protobuf:"varint,2,opt,name=done_views,json=doneViews,proto3" json:"done_views,omitempty"`       // 实际达成阅读量（ReportPromoteStats 归集）
	TargetViews   int64                  `protobuf:"varint,3,opt,name=target_views,json=targetViews,proto3" json:"target_views,omitempty"` // 目标阅读量
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                               // 结算原因（complete / 到期 / 人工复核等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPromoteOrderSettleRequest) Reset() {
	*x = StarPromoteOrderSettleRequest{}
	mi := &file_star_v1_star_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPromoteOrderSettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPromoteOrderSettleRequest) ProtoMessage() {}

func (x *StarPromoteOrderSettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPromoteOrderSettleRequest.ProtoReflect.Descriptor instead.
func (*StarPromoteOrderSettleRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{16}
}

func (x *StarPromoteOrderSettleRequest) GetPromoteNo() string {
	if x != nil {
		return x.PromoteNo
	}
	return ""
}

func (x *StarPromoteOrderSettleRequest) GetDoneViews() int64 {
	if x != nil {
		return x.DoneViews
	}
	return 0
}

func (x *StarPromoteOrderSettleRequest) GetTargetViews() int64 {
	if x != nil {
		return x.TargetViews
	}
	return 0
}

func (x *StarPromoteOrderSettleRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// StarSettleTargetLine - 分账目标舰明细行。
type StarSettleTargetLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 目标舰实例标识
	Fen           int64                  `protobuf:"varint,2,opt,name=fen,proto3" json:"fen,omitempty"`                                // 分账金额（万分，按有效阅读占比瓜分）
	Views         int64                  `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`                            // 该舰有效阅读量（accepted 口径）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarSettleTargetLine) Reset() {
	*x = StarSettleTargetLine{}
	mi := &file_star_v1_star_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarSettleTargetLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarSettleTargetLine) ProtoMessage() {}

func (x *StarSettleTargetLine) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarSettleTargetLine.ProtoReflect.Descriptor instead.
func (*StarSettleTargetLine) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{17}
}

func (x *StarSettleTargetLine) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StarSettleTargetLine) GetFen() int64 {
	if x != nil {
		return x.Fen
	}
	return 0
}

func (x *StarSettleTargetLine) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

// StarSettleBill - 分账快照（投流结算返回，同时落 star_promote_orders.settle_snapshot）。
type StarSettleBill struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SettleNo      string                  `protobuf:"bytes,1,opt,name=settle_no,json=settleNo,proto3" json:"settle_no,omitempty"`           // 结算单号（hub 生成，SET-{年}-%06d）
	AmountFen     int64                   `protobuf:"varint,2,opt,name=amount_fen,json=amountFen,proto3" json:"amount_fen,omitempty"`       // 原 hold 金额（万分）
	RefundFen     int64                   `protobuf:"varint,3,opt,name=refund_fen,json=refundFen,proto3" json:"refund_fen,omitempty"`       // 退款金额（万分，未达成部分 release）
	SourceFen     int64                   `protobuf:"varint,4,opt,name=source_fen,json=sourceFen,proto3" json:"source_fen,omitempty"`       // 源舰长分账（万分，结算额 × 20%）
	TargetFen     int64                   `protobuf:"varint,5,opt,name=target_fen,json=targetFen,proto3" json:"target_fen,omitempty"`       // 目标舰群分账合计（万分，结算额 × 50%）
	PlatformFen   int64                   `protobuf:"varint,6,opt,name=platform_fen,json=platformFen,proto3" json:"platform_fen,omitempty"` // 平台分账（万分，结算额 × 30%）
	TargetLines   []*StarSettleTargetLine `protobuf:"bytes,7,rep,name=target_lines,json=targetLines,proto3" json:"target_lines,omitempty"`  // 目标舰群明细行
	SettledAt     int64                   `protobuf:"varint,8,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`       // 结算时间（毫秒戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarSettleBill) Reset() {
	*x = StarSettleBill{}
	mi := &file_star_v1_star_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarSettleBill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarSettleBill) ProtoMessage() {}

func (x *StarSettleBill) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarSettleBill.ProtoReflect.Descriptor instead.
func (*StarSettleBill) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{18}
}

func (x *StarSettleBill) GetSettleNo() string {
	if x != nil {
		return x.SettleNo
	}
	return ""
}

func (x *StarSettleBill) GetAmountFen() int64 {
	if x != nil {
		return x.AmountFen
	}
	return 0
}

func (x *StarSettleBill) GetRefundFen() int64 {
	if x != nil {
		return x.RefundFen
	}
	return 0
}

func (x *StarSettleBill) GetSourceFen() int64 {
	if x != nil {
		return x.SourceFen
	}
	return 0
}

func (x *StarSettleBill) GetTargetFen() int64 {
	if x != nil {
		return x.TargetFen
	}
	return 0
}

func (x *StarSettleBill) GetPlatformFen() int64 {
	if x != nil {
		return x.PlatformFen
	}
	return 0
}

func (x *StarSettleBill) GetTargetLines() []*StarSettleTargetLine {
	if x != nil {
		return x.TargetLines
	}
	return nil
}

func (x *StarSettleBill) GetSettledAt() int64 {
	if x != nil {
		return x.SettledAt
	}
	return 0
}

// StarPromoteOrderSettleResponse - 投流结算回执。
type StarPromoteOrderSettleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *StarAck               `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`   // 通用回执
	Bill          *StarSettleBill        `protobuf:"bytes,2,opt,name=bill,proto3" json:"bill,omitempty"` // 分账快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPromoteOrderSettleResponse) Reset() {
	*x = StarPromoteOrderSettleResponse{}
	mi := &file_star_v1_star_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPromoteOrderSettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPromoteOrderSettleResponse) ProtoMessage() {}

func (x *StarPromoteOrderSettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPromoteOrderSettleResponse.ProtoReflect.Descriptor instead.
func (*StarPromoteOrderSettleResponse) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{19}
}

func (x *StarPromoteOrderSettleResponse) GetAck() *StarAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *StarPromoteOrderSettleResponse) GetBill() *StarSettleBill {
	if x != nil {
		return x.Bill
	}
	return nil
}

// StarPromoteOrderCancelRequest - 投流取消/退款请求（幂等键 request_id = promote_no）。
type StarPromoteOrderCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromoteNo     string                 `protobuf:"bytes,1,opt,name=promote_no,json=promoteNo,proto3" json:"promote_no,omitempty"`        // 投流单号（幂等键）
	RefundRatio   int32                  `protobuf:"varint,2,opt,name=refund_ratio,json=refundRatio,proto3" json:"refund_ratio,omitempty"` // 退款比例（万分位 0~10000，release 解冻比例）
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                               // 取消原因（拒审 / 撤销 / 到期等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPromoteOrderCancelRequest) Reset() {
	*x = StarPromoteOrderCancelRequest{}
	mi := &file_star_v1_star_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPromoteOrderCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPromoteOrderCancelRequest) ProtoMessage() {}

func (x *StarPromoteOrderCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPromoteOrderCancelRequest.ProtoReflect.Descriptor instead.
func (*StarPromoteOrderCancelRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{20}
}

func (x *StarPromoteOrderCancelRequest) GetPromoteNo() string {
	if x != nil {
		return x.PromoteNo
	}
	return ""
}

func (x *StarPromoteOrderCancelRequest) GetRefundRatio() int32 {
	if x != nil {
		return x.RefundRatio
	}
	return 0
}

func (x *StarPromoteOrderCancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// StarPromoteOrderCancelResponse - 投流取消/退款回执。
type StarPromoteOrderCancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *StarAck               `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`                               // 通用回执
	RefundFen     int64                  `protobuf:"varint,2,opt,name=refund_fen,json=refundFen,proto3" json:"refund_fen,omitempty"` // 实际退款金额（万分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarPromoteOrderCancelResponse) Reset() {
	*x = StarPromoteOrderCancelResponse{}
	mi := &file_star_v1_star_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarPromoteOrderCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarPromoteOrderCancelResponse) ProtoMessage() {}

func (x *StarPromoteOrderCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarPromoteOrderCancelResponse.ProtoReflect.Descriptor instead.
func (*StarPromoteOrderCancelResponse) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{21}
}

func (x *StarPromoteOrderCancelResponse) GetAck() *StarAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *StarPromoteOrderCancelResponse) GetRefundFen() int64 {
	if x != nil {
		return x.RefundFen
	}
	return 0
}

// StarReportPromoteStatsRequest - 投流阅读上报请求
// （promote_no + from_instance_id + period_hour 归集 upsert）。
type StarReportPromoteStatsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PromoteNo      string                 `protobuf:"bytes,1,opt,name=promote_no,json=promoteNo,proto3" json:"promote_no,omitempty"`                  // 投流单号
	FromInstanceId string                 `protobuf:"bytes,2,opt,name=from_instance_id,json=fromInstanceId,proto3" json:"from_instance_id,omitempty"` // 上报舰（目标舰）实例标识
	PeriodHour     int64                  `protobuf:"varint,3,opt,name=period_hour,json=periodHour,proto3" json:"period_hour,omitempty"`              // 归集周期小时起点（毫秒戳）
	Views          int64                  `protobuf:"varint,4,opt,name=views,proto3" json:"views,omitempty"`                                          // 本周期阅读量
	UniqueViewers  int64                  `protobuf:"varint,5,opt,name=unique_viewers,json=uniqueViewers,proto3" json:"unique_viewers,omitempty"`     // 本周期去重阅读人数
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                         // 口径：accepted（有效）/ quarantined（隔离，不参与分账）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StarReportPromoteStatsRequest) Reset() {
	*x = StarReportPromoteStatsRequest{}
	mi := &file_star_v1_star_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarReportPromoteStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarReportPromoteStatsRequest) ProtoMessage() {}

func (x *StarReportPromoteStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarReportPromoteStatsRequest.ProtoReflect.Descriptor instead.
func (*StarReportPromoteStatsRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{22}
}

func (x *StarReportPromoteStatsRequest) GetPromoteNo() string {
	if x != nil {
		return x.PromoteNo
	}
	return ""
}

func (x *StarReportPromoteStatsRequest) GetFromInstanceId() string {
	if x != nil {
		return x.FromInstanceId
	}
	return ""
}

func (x *StarReportPromoteStatsRequest) GetPeriodHour() int64 {
	if x != nil {
		return x.PeriodHour
	}
	return 0
}

func (x *StarReportPromoteStatsRequest) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *StarReportPromoteStatsRequest) GetUniqueViewers() int64 {
	if x != nil {
		return x.UniqueViewers
	}
	return 0
}

func (x *StarReportPromoteStatsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// StarReportOutcomeRequest - 仲裁结果上报请求（幂等键 request_id = report_no）。
type StarReportOutcomeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReportNo         string                 `protobuf:"bytes,1,opt,name=report_no,json=reportNo,proto3" json:"report_no,omitempty"`                           // 举报单号（幂等键）
	FromInstanceId   string                 `protobuf:"bytes,2,opt,name=from_instance_id,json=fromInstanceId,proto3" json:"from_instance_id,omitempty"`       // 举报发起舰实例标识
	TargetInstanceId string                 `protobuf:"bytes,3,opt,name=target_instance_id,json=targetInstanceId,proto3" json:"target_instance_id,omitempty"` // 被举报舰（= 源舰）实例标识
	RemoteNoteId     string                 `protobuf:"bytes,4,opt,name=remote_note_id,json=remoteNoteId,proto3" json:"remote_note_id,omitempty"`             // 源站笔记标识
	Reason           string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                               // 举报原因
	Outcome          string                 `protobuf:"bytes,6,opt,name=outcome,proto3" json:"outcome,omitempty"`                                             // 处置结果：pending / upheld（成立）/ rejected（驳回）
	OutcomeAt        int64                  `protobuf:"varint,7,opt,name=outcome_at,json=outcomeAt,proto3" json:"outcome_at,omitempty"`                       // 处置时间（毫秒戳）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StarReportOutcomeRequest) Reset() {
	*x = StarReportOutcomeRequest{}
	mi := &file_star_v1_star_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarReportOutcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarReportOutcomeRequest) ProtoMessage() {}

func (x *StarReportOutcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_v1_star_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarReportOutcomeRequest.ProtoReflect.Descriptor instead.
func (*StarReportOutcomeRequest) Descriptor() ([]byte, []int) {
	return file_star_v1_star_proto_rawDescGZIP(), []int{23}
}

func (x *StarReportOutcomeRequest) GetReportNo() string {
	if x != nil {
		return x.ReportNo
	}
	return ""
}

func (x *StarReportOutcomeRequest) GetFromInstanceId() string {
	if x != nil {
		return x.FromInstanceId
	}
	return ""
}

func (x *StarReportOutcomeRequest) GetTargetInstanceId() string {
	if x != nil {
		return x.TargetInstanceId
	}
	return ""
}

func (x *StarReportOutcomeRequest) GetRemoteNoteId() string {
	if x != nil {
		return x.RemoteNoteId
	}
	return ""
}

func (x *StarReportOutcomeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StarReportOutcomeRequest) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *StarReportOutcomeRequest) GetOutcomeAt() int64 {
	if x != nil {
		return x.OutcomeAt
	}
	return 0
}

var File_star_v1_star_proto protoreflect.FileDescriptor

const file_star_v1_star_proto_rawDesc = "" +
	"\n" +
	"\x12star/v1/star.proto\x12\x10licenhub.star.v1\"7\n" +
	"\aStarAck\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\x0fStarJoinRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06pubkey\x18\x04 \x01(\tR\x06pubkey\x12\x1f\n" +
	"\vapp_version\x18\x05 \x01(\tR\n" +
	"appVersion\"\x97\x01\n" +
	"\x10StarJoinResponse\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.licenhub.star.v1.StarAckR\x03ack\x12\x1f\n" +
	"\vstar_status\x18\x02 \x01(\tR\n" +
	"starStatus\x12\x1f\n" +
	"\vtrust_score\x18\x03 \x01(\x05R\n" +
	"trustScore\x12\x14\n" +
	"\x05since\x18\x04 \x01(\x03R\x05since\",\n" +
	"\x14StarListPeersRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x03R\x05since\"\xf8\x01\n" +
	"\bStarPeer\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06pubkey\x18\x04 \x01(\tR\x06pubkey\x12\x1f\n" +
	"\vstar_status\x18\x05 \x01(\tR\n" +
	"starStatus\x12\x1f\n" +
	"\vtrust_score\x18\x06 \x01(\x05R\n" +
	"trustScore\x12\x1f\n" +
	"\vapp_version\x18\a \x01(\tR\n" +
	"appVersion\x12 \n" +
	"\flast_beat_at\x18\b \x01(\x03R\n" +
	"lastBeatAt\"\x8c\x01\n" +
	"\x15StarListPeersResponse\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.licenhub.star.v1.StarAckR\x03ack\x120\n" +
	"\x05peers\x18\x02 \x03(\v2\x1a.licenhub.star.v1.StarPeerR\x05peers\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\"\xe5\x01\n" +
	"\x10StarHotIndexItem\x12$\n" +
	"\x0eremote_note_id\x18\x01 \x01(\tR\fremoteNoteId\x12\x1e\n" +
	"\n" +
	"percentile\x18\x02 \x01(\x05R\n" +
	"percentile\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x12\n" +
	"\x04meta\x18\x05 \x01(\fR\x04meta\x12\x1c\n" +
	"\tembedding\x18\x06 \x01(\fR\tembedding\x12!\n" +
	"\fpublished_at\x18\a \x01(\x03R\vpublishedAt\"t\n" +
	"\x17StarPushHotIndexRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x128\n" +
	"\x05items\x18\x02 \x03(\v2\".licenhub.star.v1.StarHotIndexItemR\x05items\"c\n" +
	"\x18StarPushHotIndexResponse\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.licenhub.star.v1.StarAckR\x03ack\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\"g\n" +
	"\x18StarPullGlobalHotRequest\x12\x13\n" +
	"\x05top_k\x18\x01 \x01(\x05R\x04topK\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"\xeb\x01\n" +
	"\x11StarGlobalHotItem\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12$\n" +
	"\x0eremote_note_id\x18\x02 \x01(\tR\fremoteNoteId\x12\x1b\n" +
	"\tscore_net\x18\x03 \x01(\x03R\bscoreNet\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\fR\x04meta\x12\x1c\n" +
	"\tembedding\x18\x05 \x01(\fR\tembedding\x12\x1d\n" +
	"\n" +
	"origin_url\x18\x06 \x01(\tR\toriginUrl\x12!\n" +
	"\fpublished_at\x18\a \x01(\x03R\vpublishedAt\"\x83\x01\n" +
	"\x19StarPullGlobalHotResponse\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.licenhub.star.v1.StarAckR\x03ack\x129\n" +
	"\x05items\x18\x02 \x03(\v2#.licenhub.star.v1.StarGlobalHotItemR\x05items\"\x8e\x01\n" +
	"\x19StarCreditPurchaseRequest\x12\x1f\n" +
	"\vpurchase_no\x18\x01 \x01(\tR\n" +
	"purchaseNo\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x03R\x06points\x12\x1d\n" +
	"\n" +
	"amount_fen\x18\x03 \x01(\x03R\tamountFen\x12\x19\n" +
	"\brate_fen\x18\x04 \x01(\x03R\arateFen\"o\n" +
	"\x19StarCreditGrantOutRequest\x12\x19\n" +
	"\bgrant_no\x18\x01 \x01(\tR\agrantNo\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x03R\x06points\x12\x1f\n" +
	"\vtarget_note\x18\x03 \x01(\tR\n" +
	"targetNote\"n\n" +
	"\x1aStarCreditGrantOutResponse\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.licenhub.star.v1.StarAckR\x03ack\x12#\n" +
	"\rbalance_after\x18\x02 \x01(\x03R\fbalanceAfter\"\x9a\x02\n" +
	"\x1dStarPromoteOrderCreateRequest\x12\x1d\n" +
	"\n" +
	"promote_no\x18\x01 \x01(\tR\tpromoteNo\x120\n" +
	"\x14note_origin_instance\x18\x02 \x01(\tR\x12noteOriginInstance\x12$\n" +
	"\x0eremote_note_id\x18\x03 \x01(\tR\fremoteNoteId\x12(\n" +
	"\x10from_instance_id\x18\x04 \x01(\tR\x0efromInstanceId\x12\x16\n" +
	"\x06points\x18\x05 \x01(\x03R\x06points\x12\x1d\n" +
	"\n" +
	"amount_fen\x18\x06 \x01(\x03R\tamountFen\x12!\n" +
	"\ftarget_views\x18\a \x01(\x03R\vtargetViews\"\x98\x01\n" +
	"\x1dStarPromoteOrderSettleRequest\x12\x1d\n" +
	"\n" +
	"promote_no\x18\x01 \x01(\tR\tpromoteNo\x12\x1d\n" +
	"\n" +
	"done_views\x18\x02 \x01(\x03R\tdoneViews\x12!\n" +
	"\ftarget_views\x18\x03 \x01(\x03R\vtargetViews\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"_\n" +
	"\x14StarSettleTargetLine\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x10\n" +
	"\x03fen\x18\x02 \x01(\x03R\x03fen\x12\x14\n" +
	"\x05views\x18\x03 \x01(\x03R\x05views\"\xb6\x02\n" +
	"\x0eStarSettleBill\x12\x1b\n" +
	"\tsettle_no\x18\x01 \x01(\tR\bsettleNo\x12\x1d\n" +
	"\n" +
	"amount_fen\x18\x02 \x01(\x03R\tamountFen\x12\x1d\n" +
	"\n" +
	"refund_fen\x18\x03 \x01(\x03R\trefundFen\x12\x1d\n" +
	"\n" +
	"source_fen\x18\x04 \x01(\x03R\tsourceFen\x12\x1d\n" +
	"\n" +
	"target_fen\x18\x05 \x01(\x03R\ttargetFen\x12!\n" +
	"\fplatform_fen\x18\x06 \x01(\x03R\vplatformFen\x12I\n" +
	"\ftarget_lines\x18\a \x03(\v2&.licenhub.star.v1.StarSettleTargetLineR\vtargetLines\x12\x1d\n" +
	"\n" +
	"settled_at\x18\b \x01(\x03R\tsettledAt\"\x83\x01\n" +
	"\x1eStarPromoteOrderSettleResponse\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.licenhub.star.v1.StarAckR\x03ack\x124\n" +
	"\x04bill\x18\x02 \x01(\v2 .licenhub.star.v1.StarSettleBillR\x04bill\"y\n" +
	"\x1dStarPromoteOrderCancelRequest\x12\x1d\n" +
	"\n" +
	"promote_no\x18\x01 \x01(\tR\tpromoteNo\x12!\n" +
	"\frefund_ratio\x18\x02 \x01(\x05R\vrefundRatio\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"l\n" +
	"\x1eStarPromoteOrderCancelResponse\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.licenhub.star.v1.StarAckR\x03ack\x12\x1d\n" +
	"\n" +
	"refund_fen\x18\x02 \x01(\x03R\trefundFen\"\xde\x01\n" +
	"\x1dStarReportPromoteStatsRequest\x12\x1d\n" +
	"\n" +
	"promote_no\x18\x01 \x01(\tR\tpromoteNo\x12(\n" +
	"\x10from_instance_id\x18\x02 \x01(\tR\x0efromInstanceId\x12\x1f\n" +
	"\vperiod_hour\x18\x03 \x01(\x03R\n" +
	"periodHour\x12\x14\n" +
	"\x05views\x18\x04 \x01(\x03R\x05views\x12%\n" +
	"\x0eunique_viewers\x18\x05 \x01(\x03R\runiqueViewers\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x86\x02\n" +
	"\x18StarReportOutcomeRequest\x12\x1b\n" +
	"\treport_no\x18\x01 \x01(\tR\breportNo\x12(\n" +
	"\x10from_instance_id\x18\x02 \x01(\tR\x0efromInstanceId\x12,\n" +
	"\x12target_instance_id\x18\x03 \x01(\tR\x10targetInstanceId\x12$\n" +
	"\x0eremote_note_id\x18\x04 \x01(\tR\fremoteNoteId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x18\n" +
	"\aoutcome\x18\x06 \x01(\tR\aoutcome\x12\x1d\n" +
	"\n" +
	"outcome_at\x18\a \x01(\x03R\toutcomeAt2\xc3\x01\n" +
	"\x14StarDirectoryService\x12M\n" +
	"\x04Join\x12!.licenhub.star.v1.StarJoinRequest\x1a\".licenhub.star.v1.StarJoinResponse\x12\\\n" +
	"\tListPeers\x12&.licenhub.star.v1.StarListPeersRequest\x1a'.licenhub.star.v1.StarListPeersResponse2\xe3\x01\n" +
	"\x10StarIndexService\x12e\n" +
	"\fPushHotIndex\x12).licenhub.star.v1.StarPushHotIndexRequest\x1a*.licenhub.star.v1.StarPushHotIndexResponse\x12h\n" +
	"\rPullGlobalHot\x12*.licenhub.star.v1.StarPullGlobalHotRequest\x1a+.licenhub.star.v1.StarPullGlobalHotResponse2\x91\x05\n" +
	"\x12StarBillingService\x12X\n" +
	"\x0eCreditPurchase\x12+.licenhub.star.v1.StarCreditPurchaseRequest\x1a\x19.licenhub.star.v1.StarAck\x12k\n" +
	"\x0eCreditGrantOut\x12+.licenhub.star.v1.StarCreditGrantOutRequest\x1a,.licenhub.star.v1.StarCreditGrantOutResponse\x12`\n" +
	"\x12PromoteOrderCreate\x12/.licenhub.star.v1.StarPromoteOrderCreateRequest\x1a\x19.licenhub.star.v1.StarAck\x12w\n" +
	"\x12PromoteOrderSettle\x12/.licenhub.star.v1.StarPromoteOrderSettleRequest\x1a0.licenhub.star.v1.StarPromoteOrderSettleResponse\x12w\n" +
	"\x12PromoteOrderCancel\x12/.licenhub.star.v1.StarPromoteOrderCancelRequest\x1a0.licenhub.star.v1.StarPromoteOrderCancelResponse\x12`\n" +
	"\x12ReportPromoteStats\x12/.licenhub.star.v1.StarReportPromoteStatsRequest\x1a\x19.licenhub.star.v1.StarAck2p\n" +
	"\x16StarArbitrationService\x12V\n" +
	"\rReportOutcome\x12*.licenhub.star.v1.StarReportOutcomeRequest\x1a\x19.licenhub.star.v1.StarAckB6Z4github.com/inis-io/aide/licence/proto/star/v1;starv1b\x06proto3"

var (
	file_star_v1_star_proto_rawDescOnce sync.Once
	file_star_v1_star_proto_rawDescData []byte
)

func file_star_v1_star_proto_rawDescGZIP() []byte {
	file_star_v1_star_proto_rawDescOnce.Do(func() {
		file_star_v1_star_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_star_v1_star_proto_rawDesc), len(file_star_v1_star_proto_rawDesc)))
	})
	return file_star_v1_star_proto_rawDescData
}

var file_star_v1_star_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_star_v1_star_proto_goTypes = []any{
	(*StarAck)(nil),                        // 0: licenhub.star.v1.StarAck
	(*StarJoinRequest)(nil),                // 1: licenhub.star.v1.StarJoinRequest
	(*StarJoinResponse)(nil),               // 2: licenhub.star.v1.StarJoinResponse
	(*StarListPeersRequest)(nil),           // 3: licenhub.star.v1.StarListPeersRequest
	(*StarPeer)(nil),                       // 4: licenhub.star.v1.StarPeer
	(*StarListPeersResponse)(nil),          // 5: licenhub.star.v1.StarListPeersResponse
	(*StarHotIndexItem)(nil),               // 6: licenhub.star.v1.StarHotIndexItem
	(*StarPushHotIndexRequest)(nil),        // 7: licenhub.star.v1.StarPushHotIndexRequest
	(*StarPushHotIndexResponse)(nil),       // 8: licenhub.star.v1.StarPushHotIndexResponse
	(*StarPullGlobalHotRequest)(nil),       // 9: licenhub.star.v1.StarPullGlobalHotRequest
	(*StarGlobalHotItem)(nil),              // 10: licenhub.star.v1.StarGlobalHotItem
	(*StarPullGlobalHotResponse)(nil),      // 11: licenhub.star.v1.StarPullGlobalHotResponse
	(*StarCreditPurchaseRequest)(nil),      // 12: licenhub.star.v1.StarCreditPurchaseRequest
	(*StarCreditGrantOutRequest)(nil),      // 13: licenhub.star.v1.StarCreditGrantOutRequest
	(*StarCreditGrantOutResponse)(nil),     // 14: licenhub.star.v1.StarCreditGrantOutResponse
	(*StarPromoteOrderCreateRequest)(nil),  // 15: licenhub.star.v1.StarPromoteOrderCreateRequest
	(*StarPromoteOrderSettleRequest)(nil),  // 16: licenhub.star.v1.StarPromoteOrderSettleRequest
	(*StarSettleTargetLine)(nil),           // 17: licenhub.star.v1.StarSettleTargetLine
	(*StarSettleBill)(nil),                 // 18: licenhub.star.v1.StarSettleBill
	(*StarPromoteOrderSettleResponse)(nil), // 19: licenhub.star.v1.StarPromoteOrderSettleResponse
	(*StarPromoteOrderCancelRequest)(nil),  // 20: licenhub.star.v1.StarPromoteOrderCancelRequest
	(*StarPromoteOrderCancelResponse)(nil), // 21: licenhub.star.v1.StarPromoteOrderCancelResponse
	(*StarReportPromoteStatsRequest)(nil),  // 22: licenhub.star.v1.StarReportPromoteStatsRequest
	(*StarReportOutcomeRequest)(nil),       // 23: licenhub.star.v1.StarReportOutcomeRequest
}
var file_star_v1_star_proto_depIdxs = []int32{
	0,  // 0: licenhub.star.v1.StarJoinResponse.ack:type_name -> licenhub.star.v1.StarAck
	0,  // 1: licenhub.star.v1.StarListPeersResponse.ack:type_name -> licenhub.star.v1.StarAck
	4,  // 2: licenhub.star.v1.StarListPeersResponse.peers:type_name -> licenhub.star.v1.StarPeer
	6,  // 3: licenhub.star.v1.StarPushHotIndexRequest.items:type_name -> licenhub.star.v1.StarHotIndexItem
	0,  // 4: licenhub.star.v1.StarPushHotIndexResponse.ack:type_name -> licenhub.star.v1.StarAck
	0,  // 5: licenhub.star.v1.StarPullGlobalHotResponse.ack:type_name -> licenhub.star.v1.StarAck
	10, // 6: licenhub.star.v1.StarPullGlobalHotResponse.items:type_name -> licenhub.star.v1.StarGlobalHotItem
	0,  // 7: licenhub.star.v1.StarCreditGrantOutResponse.ack:type_name -> licenhub.star.v1.StarAck
	17, // 8: licenhub.star.v1.StarSettleBill.target_lines:type_name -> licenhub.star.v1.StarSettleTargetLine
	0,  // 9: licenhub.star.v1.StarPromoteOrderSettleResponse.ack:type_name -> licenhub.star.v1.StarAck
	18, // 10: licenhub.star.v1.StarPromoteOrderSettleResponse.bill:type_name -> licenhub.star.v1.StarSettleBill
	0,  // 11: licenhub.star.v1.StarPromoteOrderCancelResponse.ack:type_name -> licenhub.star.v1.StarAck
	1,  // 12: licenhub.star.v1.StarDirectoryService.Join:input_type -> licenhub.star.v1.StarJoinRequest
	3,  // 13: licenhub.star.v1.StarDirectoryService.ListPeers:input_type -> licenhub.star.v1.StarListPeersRequest
	7,  // 14: licenhub.star.v1.StarIndexService.PushHotIndex:input_type -> licenhub.star.v1.StarPushHotIndexRequest
	9,  // 15: licenhub.star.v1.StarIndexService.PullGlobalHot:input_type -> licenhub.star.v1.StarPullGlobalHotRequest
	12, // 16: licenhub.star.v1.StarBillingService.CreditPurchase:input_type -> licenhub.star.v1.StarCreditPurchaseRequest
	13, // 17: licenhub.star.v1.StarBillingService.CreditGrantOut:input_type -> licenhub.star.v1.StarCreditGrantOutRequest
	15, // 18: licenhub.star.v1.StarBillingService.PromoteOrderCreate:input_type -> licenhub.star.v1.StarPromoteOrderCreateRequest
	16, // 19: licenhub.star.v1.StarBillingService.PromoteOrderSettle:input_type -> licenhub.star.v1.StarPromoteOrderSettleRequest
	20, // 20: licenhub.star.v1.StarBillingService.PromoteOrderCancel:input_type -> licenhub.star.v1.StarPromoteOrderCancelRequest
	22, // 21: licenhub.star.v1.StarBillingService.ReportPromoteStats:input_type -> licenhub.star.v1.StarReportPromoteStatsRequest
	23, // 22: licenhub.star.v1.StarArbitrationService.ReportOutcome:input_type -> licenhub.star.v1.StarReportOutcomeRequest
	2,  // 23: licenhub.star.v1.StarDirectoryService.Join:output_type -> licenhub.star.v1.StarJoinResponse
	5,  // 24: licenhub.star.v1.StarDirectoryService.ListPeers:output_type -> licenhub.star.v1.StarListPeersResponse
	8,  // 25: licenhub.star.v1.StarIndexService.PushHotIndex:output_type -> licenhub.star.v1.StarPushHotIndexResponse
	11, // 26: licenhub.star.v1.StarIndexService.PullGlobalHot:output_type -> licenhub.star.v1.StarPullGlobalHotResponse
	0,  // 27: licenhub.star.v1.StarBillingService.CreditPurchase:output_type -> licenhub.star.v1.StarAck
	14, // 28: licenhub.star.v1.StarBillingService.CreditGrantOut:output_type -> licenhub.star.v1.StarCreditGrantOutResponse
	0,  // 29: licenhub.star.v1.StarBillingService.PromoteOrderCreate:output_type -> licenhub.star.v1.StarAck
	19, // 30: licenhub.star.v1.StarBillingService.PromoteOrderSettle:output_type -> licenhub.star.v1.StarPromoteOrderSettleResponse
	21, // 31: licenhub.star.v1.StarBillingService.PromoteOrderCancel:output_type -> licenhub.star.v1.StarPromoteOrderCancelResponse
	0,  // 32: licenhub.star.v1.StarBillingService.ReportPromoteStats:output_type -> licenhub.star.v1.StarAck
	0,  // 33: licenhub.star.v1.StarArbitrationService.ReportOutcome:output_type -> licenhub.star.v1.StarAck
	23, // [23:34] is the sub-list for method output_type
	12, // [12:23] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_star_v1_star_proto_init() }
func file_star_v1_star_proto_init() {
	if File_star_v1_star_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_star_v1_star_proto_rawDesc), len(file_star_v1_star_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_star_v1_star_proto_goTypes,
		DependencyIndexes: file_star_v1_star_proto_depIdxs,
		MessageInfos:      file_star_v1_star_proto_msgTypes,
	}.Build()
	File_star_v1_star_proto = out.File
	file_star_v1_star_proto_goTypes = nil
	file_star_v1_star_proto_depIdxs = nil
}
