// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: star/v1/star.proto

package starv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StarDirectoryService_Join_FullMethodName      = "/licenhub.star.v1.StarDirectoryService/Join"
	StarDirectoryService_ListPeers_FullMethodName = "/licenhub.star.v1.StarDirectoryService/ListPeers"
)

// StarDirectoryServiceClient is the client API for StarDirectoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StarDirectoryService - 星链目录：实例登记/心跳/目录增量下发。
type StarDirectoryServiceClient interface {
	// Join - 注册/心跳（upsert 天然幂等）：上报实例身份与公钥，
	// 返回仲裁资格态 star_status / 信用分 trust_score / 目录水位 since。
	// 公钥轮换 v1 简化：上送即覆盖，hub 写审计。
	Join(ctx context.Context, in *StarJoinRequest, opts ...grpc.CallOption) (*StarJoinResponse, error)
	// ListPeers - 目录增量拉取：按 since 水位下发变更同伴，返回新水位。
	ListPeers(ctx context.Context, in *StarListPeersRequest, opts ...grpc.CallOption) (*StarListPeersResponse, error)
}

type starDirectoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStarDirectoryServiceClient(cc grpc.ClientConnInterface) StarDirectoryServiceClient {
	return &starDirectoryServiceClient{cc}
}

func (c *starDirectoryServiceClient) Join(ctx context.Context, in *StarJoinRequest, opts ...grpc.CallOption) (*StarJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarJoinResponse)
	err := c.cc.Invoke(ctx, StarDirectoryService_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starDirectoryServiceClient) ListPeers(ctx context.Context, in *StarListPeersRequest, opts ...grpc.CallOption) (*StarListPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarListPeersResponse)
	err := c.cc.Invoke(ctx, StarDirectoryService_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarDirectoryServiceServer is the server API for StarDirectoryService service.
// All implementations must embed UnimplementedStarDirectoryServiceServer
// for forward compatibility.
//
// StarDirectoryService - 星链目录：实例登记/心跳/目录增量下发。
type StarDirectoryServiceServer interface {
	// Join - 注册/心跳（upsert 天然幂等）：上报实例身份与公钥，
	// 返回仲裁资格态 star_status / 信用分 trust_score / 目录水位 since。
	// 公钥轮换 v1 简化：上送即覆盖，hub 写审计。
	Join(context.Context, *StarJoinRequest) (*StarJoinResponse, error)
	// ListPeers - 目录增量拉取：按 since 水位下发变更同伴，返回新水位。
	ListPeers(context.Context, *StarListPeersRequest) (*StarListPeersResponse, error)
	mustEmbedUnimplementedStarDirectoryServiceServer()
}

// UnimplementedStarDirectoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStarDirectoryServiceServer struct{}

func (UnimplementedStarDirectoryServiceServer) Join(context.Context, *StarJoinRequest) (*StarJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedStarDirectoryServiceServer) ListPeers(context.Context, *StarListPeersRequest) (*StarListPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedStarDirectoryServiceServer) mustEmbedUnimplementedStarDirectoryServiceServer() {}
func (UnimplementedStarDirectoryServiceServer) testEmbeddedByValue()                              {}

// UnsafeStarDirectoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarDirectoryServiceServer will
// result in compilation errors.
type UnsafeStarDirectoryServiceServer interface {
	mustEmbedUnimplementedStarDirectoryServiceServer()
}

func RegisterStarDirectoryServiceServer(s grpc.ServiceRegistrar, srv StarDirectoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedStarDirectoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StarDirectoryService_ServiceDesc, srv)
}

func _StarDirectoryService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarDirectoryServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarDirectoryService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarDirectoryServiceServer).Join(ctx, req.(*StarJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarDirectoryService_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarDirectoryServiceServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarDirectoryService_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarDirectoryServiceServer).ListPeers(ctx, req.(*StarListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StarDirectoryService_ServiceDesc is the grpc.ServiceDesc for StarDirectoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarDirectoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenhub.star.v1.StarDirectoryService",
	HandlerType: (*StarDirectoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _StarDirectoryService_Join_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _StarDirectoryService_ListPeers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "star/v1/star.proto",
}

const (
	StarIndexService_PushHotIndex_FullMethodName  = "/licenhub.star.v1.StarIndexService/PushHotIndex"
	StarIndexService_PullGlobalHot_FullMethodName = "/licenhub.star.v1.StarIndexService/PullGlobalHot"
)

// StarIndexServiceClient is the client API for StarIndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StarIndexService - 热度索引：站内热榜上报（百分位制，不上正文）与全网榜下发。
type StarIndexServiceClient interface {
	// PushHotIndex - 热榜上报：批量条目（上报即该舰全量快照，整批覆盖该舰索引，
	// 快照幂等）；返回受理条目数。
	PushHotIndex(ctx context.Context, in *StarPushHotIndexRequest, opts ...grpc.CallOption) (*StarPushHotIndexResponse, error)
	// PullGlobalHot - 全网榜拉取：topK + 分类/语言过滤，score_net 归一后降序下发。
	PullGlobalHot(ctx context.Context, in *StarPullGlobalHotRequest, opts ...grpc.CallOption) (*StarPullGlobalHotResponse, error)
}

type starIndexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStarIndexServiceClient(cc grpc.ClientConnInterface) StarIndexServiceClient {
	return &starIndexServiceClient{cc}
}

func (c *starIndexServiceClient) PushHotIndex(ctx context.Context, in *StarPushHotIndexRequest, opts ...grpc.CallOption) (*StarPushHotIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarPushHotIndexResponse)
	err := c.cc.Invoke(ctx, StarIndexService_PushHotIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starIndexServiceClient) PullGlobalHot(ctx context.Context, in *StarPullGlobalHotRequest, opts ...grpc.CallOption) (*StarPullGlobalHotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarPullGlobalHotResponse)
	err := c.cc.Invoke(ctx, StarIndexService_PullGlobalHot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarIndexServiceServer is the server API for StarIndexService service.
// All implementations must embed UnimplementedStarIndexServiceServer
// for forward compatibility.
//
// StarIndexService - 热度索引：站内热榜上报（百分位制，不上正文）与全网榜下发。
type StarIndexServiceServer interface {
	// PushHotIndex - 热榜上报：批量条目（上报即该舰全量快照，整批覆盖该舰索引，
	// 快照幂等）；返回受理条目数。
	PushHotIndex(context.Context, *StarPushHotIndexRequest) (*StarPushHotIndexResponse, error)
	// PullGlobalHot - 全网榜拉取：topK + 分类/语言过滤，score_net 归一后降序下发。
	PullGlobalHot(context.Context, *StarPullGlobalHotRequest) (*StarPullGlobalHotResponse, error)
	mustEmbedUnimplementedStarIndexServiceServer()
}

// UnimplementedStarIndexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStarIndexServiceServer struct{}

func (UnimplementedStarIndexServiceServer) PushHotIndex(context.Context, *StarPushHotIndexRequest) (*StarPushHotIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushHotIndex not implemented")
}
func (UnimplementedStarIndexServiceServer) PullGlobalHot(context.Context, *StarPullGlobalHotRequest) (*StarPullGlobalHotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullGlobalHot not implemented")
}
func (UnimplementedStarIndexServiceServer) mustEmbedUnimplementedStarIndexServiceServer() {}
func (UnimplementedStarIndexServiceServer) testEmbeddedByValue()                          {}

// UnsafeStarIndexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarIndexServiceServer will
// result in compilation errors.
type UnsafeStarIndexServiceServer interface {
	mustEmbedUnimplementedStarIndexServiceServer()
}

func RegisterStarIndexServiceServer(s grpc.ServiceRegistrar, srv StarIndexServiceServer) {
	// If the following call pancis, it indicates UnimplementedStarIndexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StarIndexService_ServiceDesc, srv)
}

func _StarIndexService_PushHotIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarPushHotIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarIndexServiceServer).PushHotIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarIndexService_PushHotIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarIndexServiceServer).PushHotIndex(ctx, req.(*StarPushHotIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarIndexService_PullGlobalHot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarPullGlobalHotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarIndexServiceServer).PullGlobalHot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarIndexService_PullGlobalHot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarIndexServiceServer).PullGlobalHot(ctx, req.(*StarPullGlobalHotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StarIndexService_ServiceDesc is the grpc.ServiceDesc for StarIndexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarIndexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenhub.star.v1.StarIndexService",
	HandlerType: (*StarIndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushHotIndex",
			Handler:    _StarIndexService_PushHotIndex_Handler,
		},
		{
			MethodName: "PullGlobalHot",
			Handler:    _StarIndexService_PullGlobalHot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "star/v1/star.proto",
}

const (
	StarBillingService_CreditPurchase_FullMethodName     = "/licenhub.star.v1.StarBillingService/CreditPurchase"
	StarBillingService_CreditGrantOut_FullMethodName     = "/licenhub.star.v1.StarBillingService/CreditGrantOut"
	StarBillingService_PromoteOrderCreate_FullMethodName = "/licenhub.star.v1.StarBillingService/PromoteOrderCreate"
	StarBillingService_PromoteOrderSettle_FullMethodName = "/licenhub.star.v1.StarBillingService/PromoteOrderSettle"
	StarBillingService_PromoteOrderCancel_FullMethodName = "/licenhub.star.v1.StarBillingService/PromoteOrderCancel"
	StarBillingService_ReportPromoteStats_FullMethodName = "/licenhub.star.v1.StarBillingService/ReportPromoteStats"
)

// StarBillingServiceClient is the client API for StarBillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StarBillingService - 清结算：点数发行（舰长批发）+ 投流单 hold/settle/refund + 分账。
// 资金走平台钱包既有 Hold/Settle/Release/Refund/Split 机制（禁止第二套资金表）；
// 一切写操作幂等键 = 业务单号，经 metadata x-request-id 透传。
type StarBillingServiceClient interface {
	// CreditPurchase - 点数购入：舰长钱包 consume → 点数池入账（汇率快照）；
	// 幂等键 request_id = purchase_no。
	CreditPurchase(ctx context.Context, in *StarCreditPurchaseRequest, opts ...grpc.CallOption) (*StarAck, error)
	// CreditGrantOut - 点数发放核销：舰长点数池扣减（发放到站内用户，
	// im 侧入账凭证回执）；幂等键 request_id = grant_no。
	CreditGrantOut(ctx context.Context, in *StarCreditGrantOutRequest, opts ...grpc.CallOption) (*StarCreditGrantOutResponse, error)
	// PromoteOrderCreate - 投流单创建：发起舰长钱包 hold（点数 × 汇率）；
	// 幂等键 request_id = promote_no（经 metadata x-request-id 透传）。
	PromoteOrderCreate(ctx context.Context, in *StarPromoteOrderCreateRequest, opts ...grpc.CallOption) (*StarAck, error)
	// PromoteOrderSettle - 投流结算：按比例 r = min(done,target)/target 结算，
	// 差额退款，结算额拆账 源舰 20% / 目标舰群 50%（按有效阅读占比瓜分）/ 平台 30%，
	// 返回 SettleBill 分账快照；幂等键 request_id = promote_no（分账流水各带派生键）。
	PromoteOrderSettle(ctx context.Context, in *StarPromoteOrderSettleRequest, opts ...grpc.CallOption) (*StarPromoteOrderSettleResponse, error)
	// PromoteOrderCancel - 投流取消/退款：release 解冻差额（拒审/撤销/到期按比例）；
	// 幂等键 request_id = promote_no。
	PromoteOrderCancel(ctx context.Context, in *StarPromoteOrderCancelRequest, opts ...grpc.CallOption) (*StarPromoteOrderCancelResponse, error)
	// ReportPromoteStats - 投流阅读上报：目标舰按 promote_no 归集有效阅读
	// （promote_no + from_instance_id + period_hour 归集 upsert，天然幂等）。
	ReportPromoteStats(ctx context.Context, in *StarReportPromoteStatsRequest, opts ...grpc.CallOption) (*StarAck, error)
}

type starBillingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStarBillingServiceClient(cc grpc.ClientConnInterface) StarBillingServiceClient {
	return &starBillingServiceClient{cc}
}

func (c *starBillingServiceClient) CreditPurchase(ctx context.Context, in *StarCreditPurchaseRequest, opts ...grpc.CallOption) (*StarAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarAck)
	err := c.cc.Invoke(ctx, StarBillingService_CreditPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starBillingServiceClient) CreditGrantOut(ctx context.Context, in *StarCreditGrantOutRequest, opts ...grpc.CallOption) (*StarCreditGrantOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarCreditGrantOutResponse)
	err := c.cc.Invoke(ctx, StarBillingService_CreditGrantOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starBillingServiceClient) PromoteOrderCreate(ctx context.Context, in *StarPromoteOrderCreateRequest, opts ...grpc.CallOption) (*StarAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarAck)
	err := c.cc.Invoke(ctx, StarBillingService_PromoteOrderCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starBillingServiceClient) PromoteOrderSettle(ctx context.Context, in *StarPromoteOrderSettleRequest, opts ...grpc.CallOption) (*StarPromoteOrderSettleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarPromoteOrderSettleResponse)
	err := c.cc.Invoke(ctx, StarBillingService_PromoteOrderSettle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starBillingServiceClient) PromoteOrderCancel(ctx context.Context, in *StarPromoteOrderCancelRequest, opts ...grpc.CallOption) (*StarPromoteOrderCancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarPromoteOrderCancelResponse)
	err := c.cc.Invoke(ctx, StarBillingService_PromoteOrderCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starBillingServiceClient) ReportPromoteStats(ctx context.Context, in *StarReportPromoteStatsRequest, opts ...grpc.CallOption) (*StarAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarAck)
	err := c.cc.Invoke(ctx, StarBillingService_ReportPromoteStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarBillingServiceServer is the server API for StarBillingService service.
// All implementations must embed UnimplementedStarBillingServiceServer
// for forward compatibility.
//
// StarBillingService - 清结算：点数发行（舰长批发）+ 投流单 hold/settle/refund + 分账。
// 资金走平台钱包既有 Hold/Settle/Release/Refund/Split 机制（禁止第二套资金表）；
// 一切写操作幂等键 = 业务单号，经 metadata x-request-id 透传。
type StarBillingServiceServer interface {
	// CreditPurchase - 点数购入：舰长钱包 consume → 点数池入账（汇率快照）；
	// 幂等键 request_id = purchase_no。
	CreditPurchase(context.Context, *StarCreditPurchaseRequest) (*StarAck, error)
	// CreditGrantOut - 点数发放核销：舰长点数池扣减（发放到站内用户，
	// im 侧入账凭证回执）；幂等键 request_id = grant_no。
	CreditGrantOut(context.Context, *StarCreditGrantOutRequest) (*StarCreditGrantOutResponse, error)
	// PromoteOrderCreate - 投流单创建：发起舰长钱包 hold（点数 × 汇率）；
	// 幂等键 request_id = promote_no（经 metadata x-request-id 透传）。
	PromoteOrderCreate(context.Context, *StarPromoteOrderCreateRequest) (*StarAck, error)
	// PromoteOrderSettle - 投流结算：按比例 r = min(done,target)/target 结算，
	// 差额退款，结算额拆账 源舰 20% / 目标舰群 50%（按有效阅读占比瓜分）/ 平台 30%，
	// 返回 SettleBill 分账快照；幂等键 request_id = promote_no（分账流水各带派生键）。
	PromoteOrderSettle(context.Context, *StarPromoteOrderSettleRequest) (*StarPromoteOrderSettleResponse, error)
	// PromoteOrderCancel - 投流取消/退款：release 解冻差额（拒审/撤销/到期按比例）；
	// 幂等键 request_id = promote_no。
	PromoteOrderCancel(context.Context, *StarPromoteOrderCancelRequest) (*StarPromoteOrderCancelResponse, error)
	// ReportPromoteStats - 投流阅读上报：目标舰按 promote_no 归集有效阅读
	// （promote_no + from_instance_id + period_hour 归集 upsert，天然幂等）。
	ReportPromoteStats(context.Context, *StarReportPromoteStatsRequest) (*StarAck, error)
	mustEmbedUnimplementedStarBillingServiceServer()
}

// UnimplementedStarBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStarBillingServiceServer struct{}

func (UnimplementedStarBillingServiceServer) CreditPurchase(context.Context, *StarCreditPurchaseRequest) (*StarAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreditPurchase not implemented")
}
func (UnimplementedStarBillingServiceServer) CreditGrantOut(context.Context, *StarCreditGrantOutRequest) (*StarCreditGrantOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreditGrantOut not implemented")
}
func (UnimplementedStarBillingServiceServer) PromoteOrderCreate(context.Context, *StarPromoteOrderCreateRequest) (*StarAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteOrderCreate not implemented")
}
func (UnimplementedStarBillingServiceServer) PromoteOrderSettle(context.Context, *StarPromoteOrderSettleRequest) (*StarPromoteOrderSettleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteOrderSettle not implemented")
}
func (UnimplementedStarBillingServiceServer) PromoteOrderCancel(context.Context, *StarPromoteOrderCancelRequest) (*StarPromoteOrderCancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteOrderCancel not implemented")
}
func (UnimplementedStarBillingServiceServer) ReportPromoteStats(context.Context, *StarReportPromoteStatsRequest) (*StarAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportPromoteStats not implemented")
}
func (UnimplementedStarBillingServiceServer) mustEmbedUnimplementedStarBillingServiceServer() {}
func (UnimplementedStarBillingServiceServer) testEmbeddedByValue()                            {}

// UnsafeStarBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarBillingServiceServer will
// result in compilation errors.
type UnsafeStarBillingServiceServer interface {
	mustEmbedUnimplementedStarBillingServiceServer()
}

func RegisterStarBillingServiceServer(s grpc.ServiceRegistrar, srv StarBillingServiceServer) {
	// If the following call pancis, it indicates UnimplementedStarBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StarBillingService_ServiceDesc, srv)
}

func _StarBillingService_CreditPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarCreditPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarBillingServiceServer).CreditPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarBillingService_CreditPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarBillingServiceServer).CreditPurchase(ctx, req.(*StarCreditPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarBillingService_CreditGrantOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarCreditGrantOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarBillingServiceServer).CreditGrantOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarBillingService_CreditGrantOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarBillingServiceServer).CreditGrantOut(ctx, req.(*StarCreditGrantOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarBillingService_PromoteOrderCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarPromoteOrderCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarBillingServiceServer).PromoteOrderCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarBillingService_PromoteOrderCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarBillingServiceServer).PromoteOrderCreate(ctx, req.(*StarPromoteOrderCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarBillingService_PromoteOrderSettle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarPromoteOrderSettleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarBillingServiceServer).PromoteOrderSettle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarBillingService_PromoteOrderSettle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarBillingServiceServer).PromoteOrderSettle(ctx, req.(*StarPromoteOrderSettleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarBillingService_PromoteOrderCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarPromoteOrderCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarBillingServiceServer).PromoteOrderCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarBillingService_PromoteOrderCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarBillingServiceServer).PromoteOrderCancel(ctx, req.(*StarPromoteOrderCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarBillingService_ReportPromoteStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarReportPromoteStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarBillingServiceServer).ReportPromoteStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarBillingService_ReportPromoteStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarBillingServiceServer).ReportPromoteStats(ctx, req.(*StarReportPromoteStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StarBillingService_ServiceDesc is the grpc.ServiceDesc for StarBillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarBillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenhub.star.v1.StarBillingService",
	HandlerType: (*StarBillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreditPurchase",
			Handler:    _StarBillingService_CreditPurchase_Handler,
		},
		{
			MethodName: "CreditGrantOut",
			Handler:    _StarBillingService_CreditGrantOut_Handler,
		},
		{
			MethodName: "PromoteOrderCreate",
			Handler:    _StarBillingService_PromoteOrderCreate_Handler,
		},
		{
			MethodName: "PromoteOrderSettle",
			Handler:    _StarBillingService_PromoteOrderSettle_Handler,
		},
		{
			MethodName: "PromoteOrderCancel",
			Handler:    _StarBillingService_PromoteOrderCancel_Handler,
		},
		{
			MethodName: "ReportPromoteStats",
			Handler:    _StarBillingService_ReportPromoteStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "star/v1/star.proto",
}

const (
	StarArbitrationService_ReportOutcome_FullMethodName = "/licenhub.star.v1.StarArbitrationService/ReportOutcome"
)

// StarArbitrationServiceClient is the client API for StarArbitrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StarArbitrationService - 仲裁归集：举报处置结果上报（举报路由本身舰际直达）。
type StarArbitrationServiceClient interface {
	// ReportOutcome - 仲裁结果上报：源舰处置后主动上报（举报舰可申诉补录）；
	// 幂等键 request_id = report_no。
	ReportOutcome(ctx context.Context, in *StarReportOutcomeRequest, opts ...grpc.CallOption) (*StarAck, error)
}

type starArbitrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStarArbitrationServiceClient(cc grpc.ClientConnInterface) StarArbitrationServiceClient {
	return &starArbitrationServiceClient{cc}
}

func (c *starArbitrationServiceClient) ReportOutcome(ctx context.Context, in *StarReportOutcomeRequest, opts ...grpc.CallOption) (*StarAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarAck)
	err := c.cc.Invoke(ctx, StarArbitrationService_ReportOutcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarArbitrationServiceServer is the server API for StarArbitrationService service.
// All implementations must embed UnimplementedStarArbitrationServiceServer
// for forward compatibility.
//
// StarArbitrationService - 仲裁归集：举报处置结果上报（举报路由本身舰际直达）。
type StarArbitrationServiceServer interface {
	// ReportOutcome - 仲裁结果上报：源舰处置后主动上报（举报舰可申诉补录）；
	// 幂等键 request_id = report_no。
	ReportOutcome(context.Context, *StarReportOutcomeRequest) (*StarAck, error)
	mustEmbedUnimplementedStarArbitrationServiceServer()
}

// UnimplementedStarArbitrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStarArbitrationServiceServer struct{}

func (UnimplementedStarArbitrationServiceServer) ReportOutcome(context.Context, *StarReportOutcomeRequest) (*StarAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportOutcome not implemented")
}
func (UnimplementedStarArbitrationServiceServer) mustEmbedUnimplementedStarArbitrationServiceServer() {
}
func (UnimplementedStarArbitrationServiceServer) testEmbeddedByValue() {}

// UnsafeStarArbitrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarArbitrationServiceServer will
// result in compilation errors.
type UnsafeStarArbitrationServiceServer interface {
	mustEmbedUnimplementedStarArbitrationServiceServer()
}

func RegisterStarArbitrationServiceServer(s grpc.ServiceRegistrar, srv StarArbitrationServiceServer) {
	// If the following call pancis, it indicates UnimplementedStarArbitrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StarArbitrationService_ServiceDesc, srv)
}

func _StarArbitrationService_ReportOutcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarReportOutcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarArbitrationServiceServer).ReportOutcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StarArbitrationService_ReportOutcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarArbitrationServiceServer).ReportOutcome(ctx, req.(*StarReportOutcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StarArbitrationService_ServiceDesc is the grpc.ServiceDesc for StarArbitrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarArbitrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenhub.star.v1.StarArbitrationService",
	HandlerType: (*StarArbitrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportOutcome",
			Handler:    _StarArbitrationService_ReportOutcome_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "star/v1/star.proto",
}
