// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: apis/v1/runtime.proto

package apisv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApisRuntimeService_Invoke_FullMethodName   = "/licenhub.apis.v1.ApisRuntimeService/Invoke"
	ApisRuntimeService_IPLocate_FullMethodName = "/licenhub.apis.v1.ApisRuntimeService/IPLocate"
	ApisRuntimeService_Usage_FullMethodName    = "/licenhub.apis.v1.ApisRuntimeService/Usage"
	ApisRuntimeService_MailSend_FullMethodName = "/licenhub.apis.v1.ApisRuntimeService/MailSend"
)

// ApisRuntimeServiceClient is the client API for ApisRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApisRuntimeService - API 商城运行面（许可证凭证认证，非 IAM 登录态）。
//
// 凭证不进消息：activation token / 时间戳 / nonce / 签名 / 签名版本全部走 gRPC metadata
// （x-license-token / x-license-timestamp / x-license-nonce / x-license-sign /
// x-license-sign-version，与 HTTP 头族一一对应）；调用级幂等键走 metadata x-request-id
// （等价 HTTP X-Request-Id，04 §2.2），故四个请求消息都不含凭证与 request_id 字段。
// 签名 canonical 沿用运行面既有口径（licence/protocol.GRPCContent）：
//
//	GRPC\n{fullMethod}\n{timestamp}\n{nonce}\n{sha256(deterministic protobuf request)}
//
// 其中 {fullMethod} 取生成代码的 *_FullMethodName 常量原值（含前导 /，如
// /licenhub.apis.v1.ApisRuntimeService/Invoke）；协议矩阵第 3 列书写的真名不含前导 /，
// 二者仅差首字符——拼 canonical 时一律照抄常量，禁止自行拼接。
//
// 错误映射（实现属服务端适配层，两协议语义等价）：业务码以 licen-hub
// app/service/apis 的 ServiceError.Code 为唯一事实源，gRPC 侧经 status.Status + 结构化 detail
// 返回（04 §1 注：status 映射只对运行面 proto 适用，管理面继续走 JSON 信封）。业务码集合：
//
//	INVALID_ARGUMENT / UNAUTHORIZED / FORBIDDEN / NO_ENTITLEMENT / QUOTA_EXCEEDED /
//	INSUFFICIENT_BALANCE / SPEND_LIMIT_EXCEEDED / ACCOUNT_FROZEN / CONCURRENCY_LIMITED /
//	RATE_LIMITED / UPSTREAM_ERROR / IP_NOT_FOUND / CAPABILITY_NOT_FOUND / NOT_FOUND /
//	CONFLICT / INVALID_STATE / INTERNAL_ERROR
//
// detail 携带闸门上下文（retryAfterMs / scope / resetAt / limit / monthSpent 等），与 HTTP
// 运行面失败信封的 detail 字段一致；gRPC 状态码映射（InvalidArgument / Unauthenticated /
// PermissionDenied / FailedPrecondition / ResourceExhausted / NotFound / Internal …）由适配层
// 从业务码推导，客户端以业务码为准。
type ApisRuntimeServiceClient interface {
	// Invoke - 通用能力调用（所有能力的完备兜底：capability + action + params）。
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	// IPLocate - IP 归属地查询（typed 便捷方法，内部收敛为同一调用管线，不做额外逻辑）。
	IPLocate(ctx context.Context, in *IPLocateRequest, opts ...grpc.CallOption) (*IPLocateResponse, error)
	// Usage - 调用流水自助查询（只读；身份由凭证推导，只能查自己）。
	Usage(ctx context.Context, in *UsageRequest, opts ...grpc.CallOption) (*UsageResponse, error)
	// MailSend - 邮件代发（typed 便捷方法，内部收敛为同一调用管线，不做额外逻辑）。
	// 正文原样投递（不做模板替换、不自动追加验证码），按实际收件人数计量（每封计 1）。
	MailSend(ctx context.Context, in *MailSendRequest, opts ...grpc.CallOption) (*MailSendResponse, error)
}

type apisRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApisRuntimeServiceClient(cc grpc.ClientConnInterface) ApisRuntimeServiceClient {
	return &apisRuntimeServiceClient{cc}
}

func (c *apisRuntimeServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, ApisRuntimeService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apisRuntimeServiceClient) IPLocate(ctx context.Context, in *IPLocateRequest, opts ...grpc.CallOption) (*IPLocateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPLocateResponse)
	err := c.cc.Invoke(ctx, ApisRuntimeService_IPLocate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apisRuntimeServiceClient) Usage(ctx context.Context, in *UsageRequest, opts ...grpc.CallOption) (*UsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageResponse)
	err := c.cc.Invoke(ctx, ApisRuntimeService_Usage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apisRuntimeServiceClient) MailSend(ctx context.Context, in *MailSendRequest, opts ...grpc.CallOption) (*MailSendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MailSendResponse)
	err := c.cc.Invoke(ctx, ApisRuntimeService_MailSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApisRuntimeServiceServer is the server API for ApisRuntimeService service.
// All implementations must embed UnimplementedApisRuntimeServiceServer
// for forward compatibility.
//
// ApisRuntimeService - API 商城运行面（许可证凭证认证，非 IAM 登录态）。
//
// 凭证不进消息：activation token / 时间戳 / nonce / 签名 / 签名版本全部走 gRPC metadata
// （x-license-token / x-license-timestamp / x-license-nonce / x-license-sign /
// x-license-sign-version，与 HTTP 头族一一对应）；调用级幂等键走 metadata x-request-id
// （等价 HTTP X-Request-Id，04 §2.2），故四个请求消息都不含凭证与 request_id 字段。
// 签名 canonical 沿用运行面既有口径（licence/protocol.GRPCContent）：
//
//	GRPC\n{fullMethod}\n{timestamp}\n{nonce}\n{sha256(deterministic protobuf request)}
//
// 其中 {fullMethod} 取生成代码的 *_FullMethodName 常量原值（含前导 /，如
// /licenhub.apis.v1.ApisRuntimeService/Invoke）；协议矩阵第 3 列书写的真名不含前导 /，
// 二者仅差首字符——拼 canonical 时一律照抄常量，禁止自行拼接。
//
// 错误映射（实现属服务端适配层，两协议语义等价）：业务码以 licen-hub
// app/service/apis 的 ServiceError.Code 为唯一事实源，gRPC 侧经 status.Status + 结构化 detail
// 返回（04 §1 注：status 映射只对运行面 proto 适用，管理面继续走 JSON 信封）。业务码集合：
//
//	INVALID_ARGUMENT / UNAUTHORIZED / FORBIDDEN / NO_ENTITLEMENT / QUOTA_EXCEEDED /
//	INSUFFICIENT_BALANCE / SPEND_LIMIT_EXCEEDED / ACCOUNT_FROZEN / CONCURRENCY_LIMITED /
//	RATE_LIMITED / UPSTREAM_ERROR / IP_NOT_FOUND / CAPABILITY_NOT_FOUND / NOT_FOUND /
//	CONFLICT / INVALID_STATE / INTERNAL_ERROR
//
// detail 携带闸门上下文（retryAfterMs / scope / resetAt / limit / monthSpent 等），与 HTTP
// 运行面失败信封的 detail 字段一致；gRPC 状态码映射（InvalidArgument / Unauthenticated /
// PermissionDenied / FailedPrecondition / ResourceExhausted / NotFound / Internal …）由适配层
// 从业务码推导，客户端以业务码为准。
type ApisRuntimeServiceServer interface {
	// Invoke - 通用能力调用（所有能力的完备兜底：capability + action + params）。
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	// IPLocate - IP 归属地查询（typed 便捷方法，内部收敛为同一调用管线，不做额外逻辑）。
	IPLocate(context.Context, *IPLocateRequest) (*IPLocateResponse, error)
	// Usage - 调用流水自助查询（只读；身份由凭证推导，只能查自己）。
	Usage(context.Context, *UsageRequest) (*UsageResponse, error)
	// MailSend - 邮件代发（typed 便捷方法，内部收敛为同一调用管线，不做额外逻辑）。
	// 正文原样投递（不做模板替换、不自动追加验证码），按实际收件人数计量（每封计 1）。
	MailSend(context.Context, *MailSendRequest) (*MailSendResponse, error)
	mustEmbedUnimplementedApisRuntimeServiceServer()
}

// UnimplementedApisRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApisRuntimeServiceServer struct{}

func (UnimplementedApisRuntimeServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedApisRuntimeServiceServer) IPLocate(context.Context, *IPLocateRequest) (*IPLocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IPLocate not implemented")
}
func (UnimplementedApisRuntimeServiceServer) Usage(context.Context, *UsageRequest) (*UsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Usage not implemented")
}
func (UnimplementedApisRuntimeServiceServer) MailSend(context.Context, *MailSendRequest) (*MailSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MailSend not implemented")
}
func (UnimplementedApisRuntimeServiceServer) mustEmbedUnimplementedApisRuntimeServiceServer() {}
func (UnimplementedApisRuntimeServiceServer) testEmbeddedByValue()                            {}

// UnsafeApisRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApisRuntimeServiceServer will
// result in compilation errors.
type UnsafeApisRuntimeServiceServer interface {
	mustEmbedUnimplementedApisRuntimeServiceServer()
}

func RegisterApisRuntimeServiceServer(s grpc.ServiceRegistrar, srv ApisRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedApisRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApisRuntimeService_ServiceDesc, srv)
}

func _ApisRuntimeService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApisRuntimeServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApisRuntimeService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApisRuntimeServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApisRuntimeService_IPLocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPLocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApisRuntimeServiceServer).IPLocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApisRuntimeService_IPLocate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApisRuntimeServiceServer).IPLocate(ctx, req.(*IPLocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApisRuntimeService_Usage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApisRuntimeServiceServer).Usage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApisRuntimeService_Usage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApisRuntimeServiceServer).Usage(ctx, req.(*UsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApisRuntimeService_MailSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApisRuntimeServiceServer).MailSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApisRuntimeService_MailSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApisRuntimeServiceServer).MailSend(ctx, req.(*MailSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApisRuntimeService_ServiceDesc is the grpc.ServiceDesc for ApisRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApisRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "licenhub.apis.v1.ApisRuntimeService",
	HandlerType: (*ApisRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _ApisRuntimeService_Invoke_Handler,
		},
		{
			MethodName: "IPLocate",
			Handler:    _ApisRuntimeService_IPLocate_Handler,
		},
		{
			MethodName: "Usage",
			Handler:    _ApisRuntimeService_Usage_Handler,
		},
		{
			MethodName: "MailSend",
			Handler:    _ApisRuntimeService_MailSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis/v1/runtime.proto",
}
