// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: apis/v1/runtime.proto

package apisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InvokeRequest - 通用调用入参（镜像运行面 InvokeParams，凭证族 Proof 与 requestId 走 metadata）。
type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`                 // 能力编码（如 ip-locate；须已注册且有在售产品）
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                         // 动作（单动作能力可为空）
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`                         // 业务参数（能力自定义，与 HTTP 请求体同构）
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // 显式产品选择（同一能力多产品；0 = 服务端按订阅/排序解析）
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`                    // 调用方声明的最大计量数（默认 1，受能力上限收紧）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_apis_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_apis_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InvokeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InvokeRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *InvokeRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *InvokeRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// InvokeResponse - 通用调用响应（对应 HTTP 运行面信封 data.{result,receipt}，04 §2.3）。
type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Struct       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`   // 能力出参（结构由能力定义）
	Receipt       *Receipt               `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"` // 计量回执（跨协议字段一致）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_apis_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_apis_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// IPLocateRequest - IP 归属地查询请求（typed 便捷方法；能力与动作由服务端固定）。
type IPLocateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // 待查询 IP（IPv4 公网地址）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPLocateRequest) Reset() {
	*x = IPLocateRequest{}
	mi := &file_apis_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPLocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPLocateRequest) ProtoMessage() {}

func (x *IPLocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPLocateRequest.ProtoReflect.Descriptor instead.
func (*IPLocateRequest) Descriptor() ([]byte, []int) {
	return file_apis_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *IPLocateRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// IPLocateResult - IP 归属地归一化结果（能力出参，与 HTTP data.result 字段一致，07 §6）。
type IPLocateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`                              // 查询的 IP
	Nation        string                 `protobuf:"bytes,2,opt,name=nation,proto3" json:"nation,omitempty"`                      // 国家（高德源固定「中国」，离线源取如「美国」）
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`                  // 省份/州
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`                          // 城市
	Adcode        string                 `protobuf:"bytes,5,opt,name=adcode,proto3" json:"adcode,omitempty"`                      // 城市行政编码（仅高德源有，可空）
	Rectangle     string                 `protobuf:"bytes,6,opt,name=rectangle,proto3" json:"rectangle,omitempty"`                // 城市矩形范围（仅高德源有，可空）
	Isp           string                 `protobuf:"bytes,7,opt,name=isp,proto3" json:"isp,omitempty"`                            // 运营商（仅离线源有，可空）
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`                      // 数据来源：amap / ip2region
	CacheHit      bool                   `protobuf:"varint,9,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"` // 是否命中 12h 平台缓存（计费折扣依据，与 receipt.cache_hit 一致）
	Stale         bool                   `protobuf:"varint,10,opt,name=stale,proto3" json:"stale,omitempty"`                      // 是否为回源失败降级返回的过期库数据（正常缺省 false）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPLocateResult) Reset() {
	*x = IPLocateResult{}
	mi := &file_apis_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPLocateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPLocateResult) ProtoMessage() {}

func (x *IPLocateResult) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPLocateResult.ProtoReflect.Descriptor instead.
func (*IPLocateResult) Descriptor() ([]byte, []int) {
	return file_apis_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *IPLocateResult) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPLocateResult) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

func (x *IPLocateResult) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *IPLocateResult) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *IPLocateResult) GetAdcode() string {
	if x != nil {
		return x.Adcode
	}
	return ""
}

func (x *IPLocateResult) GetRectangle() string {
	if x != nil {
		return x.Rectangle
	}
	return ""
}

func (x *IPLocateResult) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *IPLocateResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IPLocateResult) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *IPLocateResult) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

// IPLocateResponse - IP 归属地查询响应（07 §9 的 typed 契约）。
type IPLocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *IPLocateResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Receipt       *Receipt               `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPLocateResponse) Reset() {
	*x = IPLocateResponse{}
	mi := &file_apis_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPLocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPLocateResponse) ProtoMessage() {}

func (x *IPLocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPLocateResponse.ProtoReflect.Descriptor instead.
func (*IPLocateResponse) Descriptor() ([]byte, []int) {
	return file_apis_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *IPLocateResponse) GetResult() *IPLocateResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *IPLocateResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// Receipt - 计量回执：计费的客户侧凭证，跨协议字段一致（04 §2.3 与 03 §4）。
type Receipt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                 // 调用级幂等键原样回显（HTTP X-Request-Id / metadata x-request-id）
	ChargeMode     string                 `protobuf:"bytes,2,opt,name=charge_mode,json=chargeMode,proto3" json:"charge_mode,omitempty"`              // 主计费模式：free_quota / trial / subscription_quota / metered_balance
	CacheHit       bool                   `protobuf:"varint,3,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`                   // 是否命中平台缓存（折扣由本字段 + amount 实收体现）
	Quantity       int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                                   // 本次实际计量数
	Amount         int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                                       // 本次实收金额（分；免费、体验与订阅额度内为 0）
	QuotaRemaining int64                  `protobuf:"varint,6,opt,name=quota_remaining,json=quotaRemaining,proto3" json:"quota_remaining,omitempty"` // 主计费模式对应的剩余额度（按量与不限量时为 0）
	BalanceAfter   int64                  `protobuf:"varint,7,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`       // 余额账户可用余额（分；未开户为 0）
	ServerTime     int64                  `protobuf:"varint,8,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`             // 服务端时间（毫秒，供客户校时）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_apis_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_apis_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *Receipt) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Receipt) GetChargeMode() string {
	if x != nil {
		return x.ChargeMode
	}
	return ""
}

func (x *Receipt) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *Receipt) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Receipt) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Receipt) GetQuotaRemaining() int64 {
	if x != nil {
		return x.QuotaRemaining
	}
	return 0
}

func (x *Receipt) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *Receipt) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// UsageRequest - 调用流水自助查询请求：UsageRecordQuery 的客户端可用子集。
// 不含 user_id / sub_id / activation_no——运行面身份由许可证凭证决定（只能查自己），
// user_id 由服务端从凭证推导，客户端不可指定。
type UsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                 // 页码（从 1 起；0 = 服务端默认 1）
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                               // 每页条数（0 = 服务端默认 10；上限 1000，超出按 1000 处理）
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`                                // 排序：空 = id desc；服务端按白名单裁决
	Capability    string                 `protobuf:"bytes,4,opt,name=capability,proto3" json:"capability,omitempty"`                      // 能力编码筛选（空 = 不限）
	ProductId     int64                  `protobuf:"varint,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`      // 产品筛选（0 = 不限）
	ChargeMode    string                 `protobuf:"bytes,6,opt,name=charge_mode,json=chargeMode,proto3" json:"charge_mode,omitempty"`    // 计费模式筛选（空 = 不限）
	Result        string                 `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`                              // 调用结果筛选：success / provider_error / rejected / settle_error
	CacheHit      string                 `protobuf:"bytes,8,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`          // 缓存命中三态筛选："" 不限 / "true" 仅命中 / "false" 仅未命中
	RequestId     string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`       // 流水筛选：完整行 request_id 精确匹配（空 = 不限；拆分计量与拒绝/失败行带 :a/:b/:rej/:err 派生后缀，按调用级 id 查不全；与本次调用的 metadata x-request-id 幂等键无关）
	CreateAt      []int64                `protobuf:"varint,10,rep,packed,name=create_at,json=createAt,proto3" json:"create_at,omitempty"` // 调用时间区间 [起, 止]（毫秒戳；0 或省略 = 不限，最多 2 个元素）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageRequest) Reset() {
	*x = UsageRequest{}
	mi := &file_apis_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRequest) ProtoMessage() {}

func (x *UsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRequest.ProtoReflect.Descriptor instead.
func (*UsageRequest) Descriptor() ([]byte, []int) {
	return file_apis_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *UsageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UsageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *UsageRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *UsageRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *UsageRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UsageRequest) GetChargeMode() string {
	if x != nil {
		return x.ChargeMode
	}
	return ""
}

func (x *UsageRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *UsageRequest) GetCacheHit() string {
	if x != nil {
		return x.CacheHit
	}
	return ""
}

func (x *UsageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UsageRequest) GetCreateAt() []int64 {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

// UsageResponse - 调用流水查询响应（对应 HTTP 分页信封 data.{records,count,page}）。
type UsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*UsageRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 满足条件的总条数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`   // 当前页码（服务端归一后的实际值）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageResponse) Reset() {
	*x = UsageResponse{}
	mi := &file_apis_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageResponse) ProtoMessage() {}

func (x *UsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageResponse.ProtoReflect.Descriptor instead.
func (*UsageResponse) Descriptor() ([]byte, []int) {
	return file_apis_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *UsageResponse) GetRecords() []*UsageRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *UsageResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UsageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// UsageRecord - 调用流水行（只追加；字段与 licen-hub ApisUsageRecord 的 JSON 一一对应）。
type UsageRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 调用级幂等键（拆分计量派生 :a/:b 后缀）
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 归属用户（运行面恒为凭证推导的本人）
	Capability    string                 `protobuf:"bytes,4,opt,name=capability,proto3" json:"capability,omitempty"`
	ProductId     int64                  `protobuf:"varint,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ActivationNo  string                 `protobuf:"bytes,6,opt,name=activation_no,json=activationNo,proto3" json:"activation_no,omitempty"` // 激活记录编号（排障定位与分实例统计；空 = 未关联激活）
	SubId         int64                  `protobuf:"varint,7,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`                     // 命中的订阅 ID（纯按量调用为 0）
	Quantity      int64                  `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ChargeMode    string                 `protobuf:"bytes,9,opt,name=charge_mode,json=chargeMode,proto3" json:"charge_mode,omitempty"`
	CacheHit      bool                   `protobuf:"varint,10,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	Amount        int64                  `protobuf:"varint,11,opt,name=amount,proto3" json:"amount,omitempty"`                           // 本次扣费（分；免费、体验与订阅额度内为 0）
	Result        string                 `protobuf:"bytes,12,opt,name=result,proto3" json:"result,omitempty"`                            // 调用结果：success / provider_error / rejected / settle_error
	UpstreamMs    int64                  `protobuf:"varint,13,opt,name=upstream_ms,json=upstreamMs,proto3" json:"upstream_ms,omitempty"` // 上游耗时（毫秒，监控用）
	CreateAt      int64                  `protobuf:"varint,14,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`       // 创建时间（毫秒戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageRecord) Reset() {
	*x = UsageRecord{}
	mi := &file_apis_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRecord) ProtoMessage() {}

func (x *UsageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_apis_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRecord.ProtoReflect.Descriptor instead.
func (*UsageRecord) Descriptor() ([]byte, []int) {
	return file_apis_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *UsageRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsageRecord) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UsageRecord) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UsageRecord) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *UsageRecord) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UsageRecord) GetActivationNo() string {
	if x != nil {
		return x.ActivationNo
	}
	return ""
}

func (x *UsageRecord) GetSubId() int64 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *UsageRecord) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UsageRecord) GetChargeMode() string {
	if x != nil {
		return x.ChargeMode
	}
	return ""
}

func (x *UsageRecord) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *UsageRecord) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UsageRecord) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *UsageRecord) GetUpstreamMs() int64 {
	if x != nil {
		return x.UpstreamMs
	}
	return 0
}

func (x *UsageRecord) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

var File_apis_v1_runtime_proto protoreflect.FileDescriptor

const file_apis_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x15apis/v1/runtime.proto\x12\x10licenhub.apis.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb3\x01\n" +
	"\rInvokeRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\"v\n" +
	"\x0eInvokeResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06result\x123\n" +
	"\areceipt\x18\x02 \x01(\v2\x19.licenhub.apis.v1.ReceiptR\areceipt\"!\n" +
	"\x0fIPLocateRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xfb\x01\n" +
	"\x0eIPLocateResult\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06nation\x18\x02 \x01(\tR\x06nation\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x16\n" +
	"\x06adcode\x18\x05 \x01(\tR\x06adcode\x12\x1c\n" +
	"\trectangle\x18\x06 \x01(\tR\trectangle\x12\x10\n" +
	"\x03isp\x18\a \x01(\tR\x03isp\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x1b\n" +
	"\tcache_hit\x18\t \x01(\bR\bcacheHit\x12\x14\n" +
	"\x05stale\x18\n" +
	" \x01(\bR\x05stale\"\x81\x01\n" +
	"\x10IPLocateResponse\x128\n" +
	"\x06result\x18\x01 \x01(\v2 .licenhub.apis.v1.IPLocateResultR\x06result\x123\n" +
	"\areceipt\x18\x02 \x01(\v2\x19.licenhub.apis.v1.ReceiptR\areceipt\"\x89\x02\n" +
	"\aReceipt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vcharge_mode\x18\x02 \x01(\tR\n" +
	"chargeMode\x12\x1b\n" +
	"\tcache_hit\x18\x03 \x01(\bR\bcacheHit\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12'\n" +
	"\x0fquota_remaining\x18\x06 \x01(\x03R\x0equotaRemaining\x12#\n" +
	"\rbalance_after\x18\a \x01(\x03R\fbalanceAfter\x12\x1f\n" +
	"\vserver_time\x18\b \x01(\x03R\n" +
	"serverTime\"\x9f\x02\n" +
	"\fUsageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\x12\x1e\n" +
	"\n" +
	"capability\x18\x04 \x01(\tR\n" +
	"capability\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\x03R\tproductId\x12\x1f\n" +
	"\vcharge_mode\x18\x06 \x01(\tR\n" +
	"chargeMode\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12\x1b\n" +
	"\tcache_hit\x18\b \x01(\tR\bcacheHit\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\x12\x1b\n" +
	"\tcreate_at\x18\n" +
	" \x03(\x03R\bcreateAt\"r\n" +
	"\rUsageResponse\x127\n" +
	"\arecords\x18\x01 \x03(\v2\x1d.licenhub.apis.v1.UsageRecordR\arecords\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"\x98\x03\n" +
	"\vUsageRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"capability\x18\x04 \x01(\tR\n" +
	"capability\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\x03R\tproductId\x12#\n" +
	"\ractivation_no\x18\x06 \x01(\tR\factivationNo\x12\x15\n" +
	"\x06sub_id\x18\a \x01(\x03R\x05subId\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x03R\bquantity\x12\x1f\n" +
	"\vcharge_mode\x18\t \x01(\tR\n" +
	"chargeMode\x12\x1b\n" +
	"\tcache_hit\x18\n" +
	" \x01(\bR\bcacheHit\x12\x16\n" +
	"\x06amount\x18\v \x01(\x03R\x06amount\x12\x16\n" +
	"\x06result\x18\f \x01(\tR\x06result\x12\x1f\n" +
	"\vupstream_ms\x18\r \x01(\x03R\n" +
	"upstreamMs\x12\x1b\n" +
	"\tcreate_at\x18\x0e \x01(\x03R\bcreateAt2\xfe\x01\n" +
	"\x12ApisRuntimeService\x12K\n" +
	"\x06Invoke\x12\x1f.licenhub.apis.v1.InvokeRequest\x1a .licenhub.apis.v1.InvokeResponse\x12Q\n" +
	"\bIPLocate\x12!.licenhub.apis.v1.IPLocateRequest\x1a\".licenhub.apis.v1.IPLocateResponse\x12H\n" +
	"\x05Usage\x12\x1e.licenhub.apis.v1.UsageRequest\x1a\x1f.licenhub.apis.v1.UsageResponseB6Z4github.com/inis-io/aide/licence/proto/apis/v1;apisv1b\x06proto3"

var (
	file_apis_v1_runtime_proto_rawDescOnce sync.Once
	file_apis_v1_runtime_proto_rawDescData []byte
)

func file_apis_v1_runtime_proto_rawDescGZIP() []byte {
	file_apis_v1_runtime_proto_rawDescOnce.Do(func() {
		file_apis_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_v1_runtime_proto_rawDesc), len(file_apis_v1_runtime_proto_rawDesc)))
	})
	return file_apis_v1_runtime_proto_rawDescData
}

var file_apis_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_apis_v1_runtime_proto_goTypes = []any{
	(*InvokeRequest)(nil),    // 0: licenhub.apis.v1.InvokeRequest
	(*InvokeResponse)(nil),   // 1: licenhub.apis.v1.InvokeResponse
	(*IPLocateRequest)(nil),  // 2: licenhub.apis.v1.IPLocateRequest
	(*IPLocateResult)(nil),   // 3: licenhub.apis.v1.IPLocateResult
	(*IPLocateResponse)(nil), // 4: licenhub.apis.v1.IPLocateResponse
	(*Receipt)(nil),          // 5: licenhub.apis.v1.Receipt
	(*UsageRequest)(nil),     // 6: licenhub.apis.v1.UsageRequest
	(*UsageResponse)(nil),    // 7: licenhub.apis.v1.UsageResponse
	(*UsageRecord)(nil),      // 8: licenhub.apis.v1.UsageRecord
	(*structpb.Struct)(nil),  // 9: google.protobuf.Struct
}
var file_apis_v1_runtime_proto_depIdxs = []int32{
	9, // 0: licenhub.apis.v1.InvokeRequest.params:type_name -> google.protobuf.Struct
	9, // 1: licenhub.apis.v1.InvokeResponse.result:type_name -> google.protobuf.Struct
	5, // 2: licenhub.apis.v1.InvokeResponse.receipt:type_name -> licenhub.apis.v1.Receipt
	3, // 3: licenhub.apis.v1.IPLocateResponse.result:type_name -> licenhub.apis.v1.IPLocateResult
	5, // 4: licenhub.apis.v1.IPLocateResponse.receipt:type_name -> licenhub.apis.v1.Receipt
	8, // 5: licenhub.apis.v1.UsageResponse.records:type_name -> licenhub.apis.v1.UsageRecord
	0, // 6: licenhub.apis.v1.ApisRuntimeService.Invoke:input_type -> licenhub.apis.v1.InvokeRequest
	2, // 7: licenhub.apis.v1.ApisRuntimeService.IPLocate:input_type -> licenhub.apis.v1.IPLocateRequest
	6, // 8: licenhub.apis.v1.ApisRuntimeService.Usage:input_type -> licenhub.apis.v1.UsageRequest
	1, // 9: licenhub.apis.v1.ApisRuntimeService.Invoke:output_type -> licenhub.apis.v1.InvokeResponse
	4, // 10: licenhub.apis.v1.ApisRuntimeService.IPLocate:output_type -> licenhub.apis.v1.IPLocateResponse
	7, // 11: licenhub.apis.v1.ApisRuntimeService.Usage:output_type -> licenhub.apis.v1.UsageResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_apis_v1_runtime_proto_init() }
func file_apis_v1_runtime_proto_init() {
	if File_apis_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_v1_runtime_proto_rawDesc), len(file_apis_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_v1_runtime_proto_goTypes,
		DependencyIndexes: file_apis_v1_runtime_proto_depIdxs,
		MessageInfos:      file_apis_v1_runtime_proto_msgTypes,
	}.Build()
	File_apis_v1_runtime_proto = out.File
	file_apis_v1_runtime_proto_goTypes = nil
	file_apis_v1_runtime_proto_depIdxs = nil
}
